/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "esp32s3_arch.H"
#include  "esp32s3_arch_ref.H"

//!/Default constructor.
esp32s3_arch_ref::esp32s3_arch_ref(esp32s3_arch& arch) : ac_arch_ref<esp32s3_parms::ac_word, esp32s3_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  IROM(arch.IROM_mport),   IRAM(arch.IRAM_mport),   DRAM(arch.DRAM_mport),   PSRAM(arch.PSRAM_mport),   DM(arch.DM_mport),   AR(arch.AR),   QR(arch.QR),   sar(arch.sar),   lcount(arch.lcount),   lbeg(arch.lbeg),   lend(arch.lend),   ps(arch.ps),   accx(arch.accx) {}

