/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "esp32s3_arch.H"


esp32s3_arch::esp32s3_arch() :
  ac_arch_dec_if<esp32s3_parms::ac_word, esp32s3_parms::ac_Hword>(esp32s3_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  IROM("IROM", 16777216U),
  IROM_mport(*this, IROM),
  IRAM("IRAM", 131072U),
  IRAM_mport(*this, IRAM),
  DRAM("DRAM", 393216U),
  DRAM_mport(*this, DRAM),
  PSRAM("PSRAM", 8388608U),
  PSRAM_mport(*this, PSRAM),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  AR("AR"),
  QR("QR"),
  sar("sar", 0),
  lcount("lcount", 0),
  lbeg("lbeg", 0),
  lend("lend", 0),
  ps("ps", 0),
  accx("accx", 0) {

  ac_mt_endian = esp32s3_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = esp32s3_parms::AC_PROC_ENDIAN;

  INST_PORT = &IROM_mport;
  DATA_PORT = &IROM_mport;
}

int esp32s3_arch::globalId = 0;