/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "m6502_isa.H"

//!Fields table declaration.
ac_dec_field m6502_parms::m6502_isa::fields[m6502_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 8, 7, 1, 0, 0, NULL},
  {"op", 8, 7, 1, 0, 0, &(m6502_parms::m6502_isa::fields[2])},
  {"imm", 8, 15, 2, 0, 0, NULL},
  {"op", 8, 7, 1, 0, 0, &(m6502_parms::m6502_isa::fields[4])},
  {"zp", 8, 15, 2, 0, 0, NULL},
  {"op", 8, 7, 1, 0, 0, &(m6502_parms::m6502_isa::fields[6])},
  {"addr", 16, 23, 3, 0, 0, NULL},
  {"op", 8, 7, 1, 0, 0, &(m6502_parms::m6502_isa::fields[8])},
  {"bdisp", 8, 15, 4, 0, 1, NULL}
};

ac_dec_format m6502_parms::m6502_isa::formats[m6502_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_Imp", 8, &(m6502_parms::m6502_isa::fields[0]), &(m6502_parms::m6502_isa::formats[1])},
  {2, "Type_Imm", 16, &(m6502_parms::m6502_isa::fields[1]), &(m6502_parms::m6502_isa::formats[2])},
  {3, "Type_ZP", 16, &(m6502_parms::m6502_isa::fields[3]), &(m6502_parms::m6502_isa::formats[3])},
  {4, "Type_Abs", 24, &(m6502_parms::m6502_isa::fields[5]), &(m6502_parms::m6502_isa::formats[4])},
  {5, "Type_Branch", 16, &(m6502_parms::m6502_isa::fields[7]), NULL}
};

ac_dec_list m6502_parms::m6502_isa::dec_list[m6502_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 170, NULL},
  {"op", 1, 138, NULL},
  {"op", 1, 168, NULL},
  {"op", 1, 152, NULL},
  {"op", 1, 232, NULL},
  {"op", 1, 202, NULL},
  {"op", 1, 200, NULL},
  {"op", 1, 136, NULL},
  {"op", 1, 24, NULL},
  {"op", 1, 56, NULL},
  {"op", 1, 234, NULL},
  {"op", 1, 0, NULL},
  {"op", 1, 169, NULL},
  {"op", 1, 162, NULL},
  {"op", 1, 160, NULL},
  {"op", 1, 105, NULL},
  {"op", 1, 233, NULL},
  {"op", 1, 41, NULL},
  {"op", 1, 9, NULL},
  {"op", 1, 73, NULL},
  {"op", 1, 201, NULL},
  {"op", 1, 224, NULL},
  {"op", 1, 192, NULL},
  {"op", 1, 165, NULL},
  {"op", 1, 133, NULL},
  {"op", 1, 166, NULL},
  {"op", 1, 134, NULL},
  {"op", 1, 164, NULL},
  {"op", 1, 132, NULL},
  {"op", 1, 173, NULL},
  {"op", 1, 141, NULL},
  {"op", 1, 76, NULL},
  {"op", 1, 208, NULL},
  {"op", 1, 240, NULL},
  {"op", 1, 176, NULL},
  {"op", 1, 144, NULL},
  {"op", 1, 48, NULL},
  {"op", 1, 16, NULL}
};

ac_dec_instr m6502_parms::m6502_isa::instructions[m6502_parms::AC_DEC_INSTR_NUMBER] = {
  {"tax", 1, "tax", "tax", "Type_Imp", 1, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[0]), 0, &(m6502_parms::m6502_isa::instructions[1])},
  {"txa", 1, "txa", "txa", "Type_Imp", 2, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[1]), 0, &(m6502_parms::m6502_isa::instructions[2])},
  {"tay", 1, "tay", "tay", "Type_Imp", 3, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[2]), 0, &(m6502_parms::m6502_isa::instructions[3])},
  {"tya", 1, "tya", "tya", "Type_Imp", 4, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[3]), 0, &(m6502_parms::m6502_isa::instructions[4])},
  {"inx", 1, "inx", "inx", "Type_Imp", 5, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[4]), 0, &(m6502_parms::m6502_isa::instructions[5])},
  {"dex", 1, "dex", "dex", "Type_Imp", 6, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[5]), 0, &(m6502_parms::m6502_isa::instructions[6])},
  {"iny", 1, "iny", "iny", "Type_Imp", 7, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[6]), 0, &(m6502_parms::m6502_isa::instructions[7])},
  {"dey", 1, "dey", "dey", "Type_Imp", 8, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[7]), 0, &(m6502_parms::m6502_isa::instructions[8])},
  {"clc", 1, "clc", "clc", "Type_Imp", 9, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[8]), 0, &(m6502_parms::m6502_isa::instructions[9])},
  {"sec", 1, "sec", "sec", "Type_Imp", 10, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[9]), 0, &(m6502_parms::m6502_isa::instructions[10])},
  {"nop_op", 1, "nop", "nop", "Type_Imp", 11, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[10]), 0, &(m6502_parms::m6502_isa::instructions[11])},
  {"brk_op", 1, "brk", "brk", "Type_Imp", 12, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[11]), 0, &(m6502_parms::m6502_isa::instructions[12])},
  {"lda_imm", 2, "lda", "lda #%imm", "Type_Imm", 13, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[12]), 0, &(m6502_parms::m6502_isa::instructions[13])},
  {"ldx_imm", 2, "ldx", "ldx #%imm", "Type_Imm", 14, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[13]), 0, &(m6502_parms::m6502_isa::instructions[14])},
  {"ldy_imm", 2, "ldy", "ldy #%imm", "Type_Imm", 15, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[14]), 0, &(m6502_parms::m6502_isa::instructions[15])},
  {"adc_imm", 2, "adc", "adc #%imm", "Type_Imm", 16, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[15]), 0, &(m6502_parms::m6502_isa::instructions[16])},
  {"sbc_imm", 2, "sbc", "sbc #%imm", "Type_Imm", 17, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[16]), 0, &(m6502_parms::m6502_isa::instructions[17])},
  {"and_imm", 2, "and", "and #%imm", "Type_Imm", 18, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[17]), 0, &(m6502_parms::m6502_isa::instructions[18])},
  {"ora_imm", 2, "ora", "ora #%imm", "Type_Imm", 19, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[18]), 0, &(m6502_parms::m6502_isa::instructions[19])},
  {"eor_imm", 2, "eor", "eor #%imm", "Type_Imm", 20, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[19]), 0, &(m6502_parms::m6502_isa::instructions[20])},
  {"cmp_imm", 2, "cmp", "cmp #%imm", "Type_Imm", 21, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[20]), 0, &(m6502_parms::m6502_isa::instructions[21])},
  {"cpx_imm", 2, "cpx", "cpx #%imm", "Type_Imm", 22, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[21]), 0, &(m6502_parms::m6502_isa::instructions[22])},
  {"cpy_imm", 2, "cpy", "cpy #%imm", "Type_Imm", 23, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[22]), 0, &(m6502_parms::m6502_isa::instructions[23])},
  {"lda_zp", 2, "lda", "lda %zp", "Type_ZP", 24, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[23]), 0, &(m6502_parms::m6502_isa::instructions[24])},
  {"sta_zp", 2, "sta", "sta %zp", "Type_ZP", 25, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[24]), 0, &(m6502_parms::m6502_isa::instructions[25])},
  {"ldx_zp", 2, "ldx", "ldx %zp", "Type_ZP", 26, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[25]), 0, &(m6502_parms::m6502_isa::instructions[26])},
  {"stx_zp", 2, "stx", "stx %zp", "Type_ZP", 27, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[26]), 0, &(m6502_parms::m6502_isa::instructions[27])},
  {"ldy_zp", 2, "ldy", "ldy %zp", "Type_ZP", 28, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[27]), 0, &(m6502_parms::m6502_isa::instructions[28])},
  {"sty_zp", 2, "sty", "sty %zp", "Type_ZP", 29, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[28]), 0, &(m6502_parms::m6502_isa::instructions[29])},
  {"lda_abs", 3, "lda", "lda %addr", "Type_Abs", 30, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[29]), 0, &(m6502_parms::m6502_isa::instructions[30])},
  {"sta_abs", 3, "sta", "sta %addr", "Type_Abs", 31, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[30]), 0, &(m6502_parms::m6502_isa::instructions[31])},
  {"jmp_abs", 3, "jmp", "jmp %addr", "Type_Abs", 32, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[31]), 0, &(m6502_parms::m6502_isa::instructions[32])},
  {"bne", 2, "bne", "bne %bdisp", "Type_Branch", 33, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[32]), 0, &(m6502_parms::m6502_isa::instructions[33])},
  {"beq", 2, "beq", "beq %bdisp", "Type_Branch", 34, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[33]), 0, &(m6502_parms::m6502_isa::instructions[34])},
  {"bcs", 2, "bcs", "bcs %bdisp", "Type_Branch", 35, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[34]), 0, &(m6502_parms::m6502_isa::instructions[35])},
  {"bcc", 2, "bcc", "bcc %bdisp", "Type_Branch", 36, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[35]), 0, &(m6502_parms::m6502_isa::instructions[36])},
  {"bmi", 2, "bmi", "bmi %bdisp", "Type_Branch", 37, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[36]), 0, &(m6502_parms::m6502_isa::instructions[37])},
  {"bpl", 2, "bpl", "bpl %bdisp", "Type_Branch", 38, 1, 1, 1, &(m6502_parms::m6502_isa::dec_list[37]), 0, NULL}
};

const ac_instr_info
m6502_parms::m6502_isa::instr_table[m6502_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 1),
  ac_instr_info(1, "tax", "tax", 1),
  ac_instr_info(2, "txa", "txa", 1),
  ac_instr_info(3, "tay", "tay", 1),
  ac_instr_info(4, "tya", "tya", 1),
  ac_instr_info(5, "inx", "inx", 1),
  ac_instr_info(6, "dex", "dex", 1),
  ac_instr_info(7, "iny", "iny", 1),
  ac_instr_info(8, "dey", "dey", 1),
  ac_instr_info(9, "clc", "clc", 1),
  ac_instr_info(10, "sec", "sec", 1),
  ac_instr_info(11, "nop_op", "nop", 1),
  ac_instr_info(12, "brk_op", "brk", 1),
  ac_instr_info(13, "lda_imm", "lda", 2),
  ac_instr_info(14, "ldx_imm", "ldx", 2),
  ac_instr_info(15, "ldy_imm", "ldy", 2),
  ac_instr_info(16, "adc_imm", "adc", 2),
  ac_instr_info(17, "sbc_imm", "sbc", 2),
  ac_instr_info(18, "and_imm", "and", 2),
  ac_instr_info(19, "ora_imm", "ora", 2),
  ac_instr_info(20, "eor_imm", "eor", 2),
  ac_instr_info(21, "cmp_imm", "cmp", 2),
  ac_instr_info(22, "cpx_imm", "cpx", 2),
  ac_instr_info(23, "cpy_imm", "cpy", 2),
  ac_instr_info(24, "lda_zp", "lda", 2),
  ac_instr_info(25, "sta_zp", "sta", 2),
  ac_instr_info(26, "ldx_zp", "ldx", 2),
  ac_instr_info(27, "stx_zp", "stx", 2),
  ac_instr_info(28, "ldy_zp", "ldy", 2),
  ac_instr_info(29, "sty_zp", "sty", 2),
  ac_instr_info(30, "lda_abs", "lda", 3),
  ac_instr_info(31, "sta_abs", "sta", 3),
  ac_instr_info(32, "jmp_abs", "jmp", 3),
  ac_instr_info(33, "bne", "bne", 2),
  ac_instr_info(34, "beq", "beq", 2),
  ac_instr_info(35, "bcs", "bcs", 2),
  ac_instr_info(36, "bcc", "bcc", 2),
  ac_instr_info(37, "bmi", "bmi", 2),
  ac_instr_info(38, "bpl", "bpl", 2)
};

const unsigned m6502_parms::m6502_isa::instr_format_table[m6502_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  4,
  4,
  4,
  5,
  5,
  5,
  5,
  5,
  5
};
