/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "m6502_arch.H"


m6502_arch::m6502_arch() :
  ac_arch_dec_if<m6502_parms::ac_word, m6502_parms::ac_Hword>(m6502_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 65536U),
  DM_mport(*this, DM),
  a("a", 0),
  x("x", 0),
  y("y", 0),
  sp_reg("sp_reg", 0),
  status("status", 0) {

  ac_mt_endian = m6502_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = m6502_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int m6502_arch::globalId = 0;