/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "c6x.H"
#include  "c6x_isa.cpp"

#include  "c6x_syscall.H"

void* c6x::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_VLIW_Reg.creg = ins_cache[1];
        instr_dec->F_Type_VLIW_Reg.z = ins_cache[2];
        instr_dec->F_Type_VLIW_Reg.op = ins_cache[3];
        instr_dec->F_Type_VLIW_Reg.src2 = ins_cache[4];
        instr_dec->F_Type_VLIW_Reg.src1 = ins_cache[5];
        instr_dec->F_Type_VLIW_Reg.dst = ins_cache[6];
        instr_dec->F_Type_VLIW_Reg.pad = ins_cache[7];
        instr_dec->F_Type_VLIW_Reg.s = ins_cache[8];
        instr_dec->F_Type_VLIW_Reg.p = ins_cache[9];
      break;
      case 2:
        instr_dec->F_Type_VLIW_Imm.creg = ins_cache[1];
        instr_dec->F_Type_VLIW_Imm.z = ins_cache[2];
        instr_dec->F_Type_VLIW_Imm.op = ins_cache[3];
        instr_dec->F_Type_VLIW_Imm.cst = ins_cache[10];
        instr_dec->F_Type_VLIW_Imm.dst = ins_cache[11];
      break;
      case 3:
        instr_dec->F_Type_Branch.creg = ins_cache[1];
        instr_dec->F_Type_Branch.z = ins_cache[2];
        instr_dec->F_Type_Branch.op = ins_cache[3];
        instr_dec->F_Type_Branch.disp = ins_cache[12];
      break;
      case 4:
        instr_dec->F_Type_Halt.op = ins_cache[13];
        instr_dec->F_Type_Halt.pad = ins_cache[14];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void c6x::behavior() {

  void* vet[] = {&&I_Init, &&I_add_reg, &&I_sub_reg, &&I_and_reg, &&I_or_reg, 
              &&I_xor_reg, &&I_sadd_reg, &&I_ssub_reg, &&I_mpy_reg, &&I_smpy_reg, 
              &&I_ldw, &&I_stw, &&I_mvkl, &&I_mvkh, &&I_add_imm, 
              &&I_sub_imm, &&I_b_disp, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_reg: // Instruction add_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_add_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_sub_reg: // Instruction sub_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_sub_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_and_reg: // Instruction and_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_and_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_or_reg: // Instruction or_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_or_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_xor_reg: // Instruction xor_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_xor_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_sadd_reg: // Instruction sadd_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_sadd_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_ssub_reg: // Instruction ssub_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_ssub_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_mpy_reg: // Instruction mpy_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_mpy_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_smpy_reg: // Instruction smpy_reg
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_smpy_reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_ldw: // Instruction ldw
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_ldw(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_stw: // Instruction stw
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Reg.op);
    ISA._behavior_c6x_Type_VLIW_Reg(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    ISA.behavior_stw(instr_dec->F_Type_VLIW_Reg.creg, instr_dec->F_Type_VLIW_Reg.z, instr_dec->F_Type_VLIW_Reg.op, instr_dec->F_Type_VLIW_Reg.src2, instr_dec->F_Type_VLIW_Reg.src1, instr_dec->F_Type_VLIW_Reg.dst, instr_dec->F_Type_VLIW_Reg.pad, instr_dec->F_Type_VLIW_Reg.s, instr_dec->F_Type_VLIW_Reg.p);
    goto *dispatch();

  I_mvkl: // Instruction mvkl
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Imm.op);
    ISA._behavior_c6x_Type_VLIW_Imm(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    ISA.behavior_mvkl(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    goto *dispatch();

  I_mvkh: // Instruction mvkh
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Imm.op);
    ISA._behavior_c6x_Type_VLIW_Imm(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    ISA.behavior_mvkh(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    goto *dispatch();

  I_add_imm: // Instruction add_imm
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Imm.op);
    ISA._behavior_c6x_Type_VLIW_Imm(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    ISA.behavior_add_imm(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    goto *dispatch();

  I_sub_imm: // Instruction sub_imm
    ISA._behavior_instruction(instr_dec->F_Type_VLIW_Imm.op);
    ISA._behavior_c6x_Type_VLIW_Imm(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    ISA.behavior_sub_imm(instr_dec->F_Type_VLIW_Imm.creg, instr_dec->F_Type_VLIW_Imm.z, instr_dec->F_Type_VLIW_Imm.op, instr_dec->F_Type_VLIW_Imm.cst, instr_dec->F_Type_VLIW_Imm.dst);
    goto *dispatch();

  I_b_disp: // Instruction b_disp
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_c6x_Type_Branch(instr_dec->F_Type_Branch.creg, instr_dec->F_Type_Branch.z, instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.disp);
    ISA.behavior_b_disp(instr_dec->F_Type_Branch.creg, instr_dec->F_Type_Branch.z, instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.disp);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_Halt.op);
    ISA._behavior_c6x_Type_Halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    ISA.behavior_halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void c6x::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void c6x::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void c6x::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void c6x::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void c6x::load(char* program) {
  DM_mport.load(program);
}

void c6x::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned c6x::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void c6x::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void c6x::PrintStat() {
  ac_arch<c6x_parms::ac_word, c6x_parms::ac_Hword>::PrintStat();
}

