/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "c6x_arch.H"
#include  "c6x_arch_ref.H"

//!/Default constructor.
c6x_arch_ref::c6x_arch_ref(c6x_arch& arch) : ac_arch_ref<c6x_parms::ac_word, c6x_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   RBA(arch.RBA),   RBB(arch.RBB),   csr(arch.csr) {}

