/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "c6x_isa.H"

//!Fields table declaration.
ac_dec_field c6x_parms::c6x_isa::fields[c6x_parms::AC_DEC_FIELD_NUMBER] = {
  {"creg", 3, 31, 1, 0, 0, &(c6x_parms::c6x_isa::fields[1])},
  {"z", 1, 28, 2, 0, 0, &(c6x_parms::c6x_isa::fields[2])},
  {"op", 7, 27, 3, 0, 0, &(c6x_parms::c6x_isa::fields[3])},
  {"src2", 5, 20, 4, 0, 0, &(c6x_parms::c6x_isa::fields[4])},
  {"src1", 5, 15, 5, 0, 0, &(c6x_parms::c6x_isa::fields[5])},
  {"dst", 5, 10, 6, 0, 0, &(c6x_parms::c6x_isa::fields[6])},
  {"pad", 4, 5, 7, 0, 0, &(c6x_parms::c6x_isa::fields[7])},
  {"s", 1, 1, 8, 0, 0, &(c6x_parms::c6x_isa::fields[8])},
  {"p", 1, 0, 9, 0, 0, NULL},
  {"creg", 3, 31, 1, 0, 0, &(c6x_parms::c6x_isa::fields[10])},
  {"z", 1, 28, 2, 0, 0, &(c6x_parms::c6x_isa::fields[11])},
  {"op", 7, 27, 3, 0, 0, &(c6x_parms::c6x_isa::fields[12])},
  {"cst", 16, 20, 10, 0, 1, &(c6x_parms::c6x_isa::fields[13])},
  {"dst", 5, 4, 11, 0, 0, NULL},
  {"creg", 3, 31, 1, 0, 0, &(c6x_parms::c6x_isa::fields[15])},
  {"z", 1, 28, 2, 0, 0, &(c6x_parms::c6x_isa::fields[16])},
  {"op", 7, 27, 3, 0, 0, &(c6x_parms::c6x_isa::fields[17])},
  {"disp", 21, 20, 12, 0, 1, NULL},
  {"op", 8, 31, 13, 0, 0, &(c6x_parms::c6x_isa::fields[19])},
  {"pad", 24, 23, 14, 0, 0, NULL}
};

ac_dec_format c6x_parms::c6x_isa::formats[c6x_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_VLIW_Reg", 32, &(c6x_parms::c6x_isa::fields[0]), &(c6x_parms::c6x_isa::formats[1])},
  {2, "Type_VLIW_Imm", 32, &(c6x_parms::c6x_isa::fields[9]), &(c6x_parms::c6x_isa::formats[2])},
  {3, "Type_Branch", 32, &(c6x_parms::c6x_isa::fields[14]), &(c6x_parms::c6x_isa::formats[3])},
  {4, "Type_Halt", 32, &(c6x_parms::c6x_isa::fields[18]), NULL}
};

ac_dec_list c6x_parms::c6x_isa::dec_list[c6x_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 3, 1, NULL},
  {"op", 3, 2, NULL},
  {"op", 3, 3, NULL},
  {"op", 3, 4, NULL},
  {"op", 3, 5, NULL},
  {"op", 3, 6, NULL},
  {"op", 3, 7, NULL},
  {"op", 3, 8, NULL},
  {"op", 3, 9, NULL},
  {"op", 3, 10, NULL},
  {"op", 3, 11, NULL},
  {"op", 3, 16, NULL},
  {"op", 3, 17, NULL},
  {"op", 3, 18, NULL},
  {"op", 3, 19, NULL},
  {"op", 3, 32, NULL},
  {"op", 13, 127, NULL}
};

ac_dec_instr c6x_parms::c6x_isa::instructions[c6x_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_reg", 4, "add", "add %src1, %src2, %dst", "Type_VLIW_Reg", 1, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[0]), 0, &(c6x_parms::c6x_isa::instructions[1])},
  {"sub_reg", 4, "sub", "sub %src1, %src2, %dst", "Type_VLIW_Reg", 2, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[1]), 0, &(c6x_parms::c6x_isa::instructions[2])},
  {"and_reg", 4, "and", "and %src1, %src2, %dst", "Type_VLIW_Reg", 3, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[2]), 0, &(c6x_parms::c6x_isa::instructions[3])},
  {"or_reg", 4, "or", "or %src1, %src2, %dst", "Type_VLIW_Reg", 4, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[3]), 0, &(c6x_parms::c6x_isa::instructions[4])},
  {"xor_reg", 4, "xor", "xor %src1, %src2, %dst", "Type_VLIW_Reg", 5, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[4]), 0, &(c6x_parms::c6x_isa::instructions[5])},
  {"sadd_reg", 4, "sadd", "sadd %src1, %src2, %dst", "Type_VLIW_Reg", 6, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[5]), 0, &(c6x_parms::c6x_isa::instructions[6])},
  {"ssub_reg", 4, "ssub", "ssub %src1, %src2, %dst", "Type_VLIW_Reg", 7, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[6]), 0, &(c6x_parms::c6x_isa::instructions[7])},
  {"mpy_reg", 4, "mpy", "mpy %src1, %src2, %dst", "Type_VLIW_Reg", 8, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[7]), 0, &(c6x_parms::c6x_isa::instructions[8])},
  {"smpy_reg", 4, "smpy", "smpy %src1, %src2, %dst", "Type_VLIW_Reg", 9, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[8]), 0, &(c6x_parms::c6x_isa::instructions[9])},
  {"ldw", 4, "ldw", "ldw *%src1, %dst", "Type_VLIW_Reg", 10, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[9]), 0, &(c6x_parms::c6x_isa::instructions[10])},
  {"stw", 4, "stw", "stw %src2, *%src1", "Type_VLIW_Reg", 11, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[10]), 0, &(c6x_parms::c6x_isa::instructions[11])},
  {"mvkl", 4, "mvkl", "mvkl %cst, %dst", "Type_VLIW_Imm", 12, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[11]), 0, &(c6x_parms::c6x_isa::instructions[12])},
  {"mvkh", 4, "mvkh", "mvkh %cst, %dst", "Type_VLIW_Imm", 13, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[12]), 0, &(c6x_parms::c6x_isa::instructions[13])},
  {"add_imm", 4, "add", "add %cst, %dst, %dst", "Type_VLIW_Imm", 14, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[13]), 0, &(c6x_parms::c6x_isa::instructions[14])},
  {"sub_imm", 4, "sub", "sub %cst, %dst, %dst", "Type_VLIW_Imm", 15, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[14]), 0, &(c6x_parms::c6x_isa::instructions[15])},
  {"b_disp", 4, "b", "b %disp", "Type_Branch", 16, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[15]), 0, &(c6x_parms::c6x_isa::instructions[16])},
  {"halt", 4, "halt", "halt", "Type_Halt", 17, 1, 1, 1, &(c6x_parms::c6x_isa::dec_list[16]), 0, NULL}
};

const ac_instr_info
c6x_parms::c6x_isa::instr_table[c6x_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "add_reg", "add", 4),
  ac_instr_info(2, "sub_reg", "sub", 4),
  ac_instr_info(3, "and_reg", "and", 4),
  ac_instr_info(4, "or_reg", "or", 4),
  ac_instr_info(5, "xor_reg", "xor", 4),
  ac_instr_info(6, "sadd_reg", "sadd", 4),
  ac_instr_info(7, "ssub_reg", "ssub", 4),
  ac_instr_info(8, "mpy_reg", "mpy", 4),
  ac_instr_info(9, "smpy_reg", "smpy", 4),
  ac_instr_info(10, "ldw", "ldw", 4),
  ac_instr_info(11, "stw", "stw", 4),
  ac_instr_info(12, "mvkl", "mvkl", 4),
  ac_instr_info(13, "mvkh", "mvkh", 4),
  ac_instr_info(14, "add_imm", "add", 4),
  ac_instr_info(15, "sub_imm", "sub", 4),
  ac_instr_info(16, "b_disp", "b", 4),
  ac_instr_info(17, "halt", "halt", 4)
};

const unsigned c6x_parms::c6x_isa::instr_format_table[c6x_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  3,
  4
};
