/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "c6x_arch.H"


c6x_arch::c6x_arch() :
  ac_arch_dec_if<c6x_parms::ac_word, c6x_parms::ac_Hword>(c6x_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  RBA("RBA"),
  RBB("RBB"),
  csr("csr", 0) {

  ac_mt_endian = c6x_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = c6x_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int c6x_arch::globalId = 0;