/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "apple_arm_isa.H"

//!Fields table declaration.
ac_dec_field apple_arm_parms::apple_arm_isa::fields[apple_arm_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[1])},
  {"opt", 3, 23, 2, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[2])},
  {"rm", 5, 20, 3, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[3])},
  {"subop", 6, 15, 4, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[4])},
  {"rn", 5, 9, 5, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[5])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[7])},
  {"imm14", 14, 23, 7, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[8])},
  {"rn", 5, 9, 5, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[9])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[11])},
  {"disp", 14, 23, 8, 0, 1, &(apple_arm_parms::apple_arm_isa::fields[12])},
  {"rn", 5, 9, 5, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[13])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[15])},
  {"pac_op", 8, 23, 9, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[16])},
  {"rn", 5, 15, 10, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[17])},
  {"subop", 6, 10, 11, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[18])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[20])},
  {"imm19", 19, 23, 12, 0, 1, &(apple_arm_parms::apple_arm_isa::fields[21])},
  {"o", 1, 4, 13, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[22])},
  {"cond", 4, 3, 14, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[24])},
  {"imm24", 24, 23, 15, 0, 1, NULL},
  {"op", 8, 31, 1, 0, 0, &(apple_arm_parms::apple_arm_isa::fields[26])},
  {"pad", 24, 23, 16, 0, 0, NULL}
};

ac_dec_format apple_arm_parms::apple_arm_isa::formats[apple_arm_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_DP_Reg", 32, &(apple_arm_parms::apple_arm_isa::fields[0]), &(apple_arm_parms::apple_arm_isa::formats[1])},
  {2, "Type_DP_Imm", 32, &(apple_arm_parms::apple_arm_isa::fields[6]), &(apple_arm_parms::apple_arm_isa::formats[2])},
  {3, "Type_LS_Imm", 32, &(apple_arm_parms::apple_arm_isa::fields[10]), &(apple_arm_parms::apple_arm_isa::formats[3])},
  {4, "Type_PAC", 32, &(apple_arm_parms::apple_arm_isa::fields[14]), &(apple_arm_parms::apple_arm_isa::formats[4])},
  {5, "Type_Branch_Cond", 32, &(apple_arm_parms::apple_arm_isa::fields[19]), &(apple_arm_parms::apple_arm_isa::formats[5])},
  {6, "Type_Branch_Imm", 32, &(apple_arm_parms::apple_arm_isa::fields[23]), &(apple_arm_parms::apple_arm_isa::formats[6])},
  {7, "Type_Halt", 32, &(apple_arm_parms::apple_arm_isa::fields[25]), NULL}
};

ac_dec_list apple_arm_parms::apple_arm_isa::dec_list[apple_arm_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 139, NULL},
  {"op", 1, 203, NULL},
  {"op", 1, 138, NULL},
  {"op", 1, 202, NULL},
  {"op", 1, 170, NULL},
  {"op", 1, 155, NULL},
  {"op", 1, 126, NULL},
  {"op", 1, 145, NULL},
  {"op", 1, 241, NULL},
  {"op", 1, 210, &(apple_arm_parms::apple_arm_isa::dec_list[10])},
  {"rn", 5, 31, NULL},
  {"op", 1, 249, NULL},
  {"op", 1, 248, NULL},
  {"op", 1, 218, &(apple_arm_parms::apple_arm_isa::dec_list[14])},
  {"pac_op", 9, 1, NULL},
  {"op", 1, 218, &(apple_arm_parms::apple_arm_isa::dec_list[16])},
  {"pac_op", 9, 5, NULL},
  {"op", 1, 218, &(apple_arm_parms::apple_arm_isa::dec_list[18])},
  {"pac_op", 9, 2, NULL},
  {"op", 1, 218, &(apple_arm_parms::apple_arm_isa::dec_list[20])},
  {"pac_op", 9, 6, NULL},
  {"op", 1, 84, &(apple_arm_parms::apple_arm_isa::dec_list[22])},
  {"o", 13, 0, NULL},
  {"op", 1, 20, NULL},
  {"op", 1, 148, NULL},
  {"op", 1, 127, NULL}
};

ac_dec_instr apple_arm_parms::apple_arm_isa::instructions[apple_arm_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_x", 4, "add", "add x%rd, x%rn, x%rm", "Type_DP_Reg", 1, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[0]), 0, &(apple_arm_parms::apple_arm_isa::instructions[1])},
  {"sub_x", 4, "sub", "sub x%rd, x%rn, x%rm", "Type_DP_Reg", 2, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[1]), 0, &(apple_arm_parms::apple_arm_isa::instructions[2])},
  {"and_x", 4, "and", "and x%rd, x%rn, x%rm", "Type_DP_Reg", 3, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[2]), 0, &(apple_arm_parms::apple_arm_isa::instructions[3])},
  {"eor_x", 4, "eor", "eor x%rd, x%rn, x%rm", "Type_DP_Reg", 4, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[3]), 0, &(apple_arm_parms::apple_arm_isa::instructions[4])},
  {"orr_x", 4, "orr", "orr x%rd, x%rn, x%rm", "Type_DP_Reg", 5, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[4]), 0, &(apple_arm_parms::apple_arm_isa::instructions[5])},
  {"mul_x", 4, "mul", "mul x%rd, x%rn, x%rm", "Type_DP_Reg", 6, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[5]), 0, &(apple_arm_parms::apple_arm_isa::instructions[6])},
  {"amx_fma", 4, "amx_fma", "amx_fma x%rd, x%rn, x%rm", "Type_DP_Reg", 7, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[6]), 0, &(apple_arm_parms::apple_arm_isa::instructions[7])},
  {"add_imm", 4, "add", "add x%rd, x%rn, #%imm14", "Type_DP_Imm", 8, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[7]), 0, &(apple_arm_parms::apple_arm_isa::instructions[8])},
  {"subs_imm", 4, "subs", "subs x%rd, x%rn, #%imm14", "Type_DP_Imm", 9, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[8]), 0, &(apple_arm_parms::apple_arm_isa::instructions[9])},
  {"movz_imm", 4, "movz", "movz x%rd, #%imm14", "Type_DP_Imm", 10, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[9]), 0, &(apple_arm_parms::apple_arm_isa::instructions[10])},
  {"ldr_x", 4, "ldr", "ldr x%rd, [x%rn, #%disp]", "Type_LS_Imm", 11, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[11]), 0, &(apple_arm_parms::apple_arm_isa::instructions[11])},
  {"str_x", 4, "str", "str x%rd, [x%rn, #%disp]", "Type_LS_Imm", 12, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[12]), 0, &(apple_arm_parms::apple_arm_isa::instructions[12])},
  {"pacia", 4, "pacia", "pacia x%rd, x%rn", "Type_PAC", 13, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[13]), 0, &(apple_arm_parms::apple_arm_isa::instructions[13])},
  {"autia", 4, "autia", "autia x%rd, x%rn", "Type_PAC", 14, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[15]), 0, &(apple_arm_parms::apple_arm_isa::instructions[14])},
  {"pacda", 4, "pacda", "pacda x%rd, x%rn", "Type_PAC", 15, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[17]), 0, &(apple_arm_parms::apple_arm_isa::instructions[15])},
  {"autda", 4, "autda", "autda x%rd, x%rn", "Type_PAC", 16, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[19]), 0, &(apple_arm_parms::apple_arm_isa::instructions[16])},
  {"b_cond", 4, "b.%cond", "b.%cond %imm19", "Type_Branch_Cond", 17, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[21]), 0, &(apple_arm_parms::apple_arm_isa::instructions[17])},
  {"b_imm", 4, "b", "b %imm24", "Type_Branch_Imm", 18, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[23]), 0, &(apple_arm_parms::apple_arm_isa::instructions[18])},
  {"bl_imm", 4, "bl", "bl %imm24", "Type_Branch_Imm", 19, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[24]), 0, &(apple_arm_parms::apple_arm_isa::instructions[19])},
  {"halt", 4, "halt", "halt", "Type_Halt", 20, 1, 1, 1, &(apple_arm_parms::apple_arm_isa::dec_list[25]), 0, NULL}
};

const ac_instr_info
apple_arm_parms::apple_arm_isa::instr_table[apple_arm_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 8),
  ac_instr_info(1, "add_x", "add", 4),
  ac_instr_info(2, "sub_x", "sub", 4),
  ac_instr_info(3, "and_x", "and", 4),
  ac_instr_info(4, "eor_x", "eor", 4),
  ac_instr_info(5, "orr_x", "orr", 4),
  ac_instr_info(6, "mul_x", "mul", 4),
  ac_instr_info(7, "amx_fma", "amx_fma", 4),
  ac_instr_info(8, "add_imm", "add", 4),
  ac_instr_info(9, "subs_imm", "subs", 4),
  ac_instr_info(10, "movz_imm", "movz", 4),
  ac_instr_info(11, "ldr_x", "ldr", 4),
  ac_instr_info(12, "str_x", "str", 4),
  ac_instr_info(13, "pacia", "pacia", 4),
  ac_instr_info(14, "autia", "autia", 4),
  ac_instr_info(15, "pacda", "pacda", 4),
  ac_instr_info(16, "autda", "autda", 4),
  ac_instr_info(17, "b_cond", "b.%cond", 4),
  ac_instr_info(18, "b_imm", "b", 4),
  ac_instr_info(19, "bl_imm", "bl", 4),
  ac_instr_info(20, "halt", "halt", 4)
};

const unsigned apple_arm_parms::apple_arm_isa::instr_format_table[apple_arm_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  3,
  3,
  4,
  4,
  4,
  4,
  5,
  6,
  6,
  7
};
