/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "apple_arm_arch.H"
#include  "apple_arm_arch_ref.H"

//!/Default constructor.
apple_arm_arch_ref::apple_arm_arch_ref(apple_arm_arch& arch) : ac_arch_ref<apple_arm_parms::ac_word, apple_arm_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   AMX_SRAM(arch.AMX_SRAM_mport),   X(arch.X),   V(arch.V),   pc(arch.pc),   pstate(arch.pstate),   pac_key_ia(arch.pac_key_ia),   pac_key_da(arch.pac_key_da),   amx_state(arch.amx_state),   tso_mode(arch.tso_mode) {}

