/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "apple_arm_arch.H"


apple_arm_arch::apple_arm_arch() :
  ac_arch_dec_if<apple_arm_parms::ac_word, apple_arm_parms::ac_Hword>(apple_arm_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  AMX_SRAM("AMX_SRAM", 16777216U),
  AMX_SRAM_mport(*this, AMX_SRAM),
  X("X"),
  V("V"),
  pc("pc", 0),
  pstate("pstate", 0),
  pac_key_ia("pac_key_ia", 0),
  pac_key_da("pac_key_da", 0),
  amx_state("amx_state", 0),
  tso_mode("tso_mode", 0) {

  ac_mt_endian = apple_arm_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = apple_arm_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int apple_arm_arch::globalId = 0;