/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "m8051.H"
#include  "m8051_isa.cpp"

#include  "m8051_syscall.H"

void* m8051::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_1B.op1 = ins_cache[1];
        instr_dec->F_Type_1B.rn1 = ins_cache[2];
      break;
      case 2:
        instr_dec->F_Type_2B.op2 = ins_cache[3];
        instr_dec->F_Type_2B.imm2 = ins_cache[4];
      break;
      case 3:
        instr_dec->F_Type_2BR.op3 = ins_cache[1];
        instr_dec->F_Type_2BR.rn3 = ins_cache[2];
        instr_dec->F_Type_2BR.imm3 = ins_cache[4];
      break;
      case 4:
        instr_dec->F_Type_REL.op4 = ins_cache[3];
        instr_dec->F_Type_REL.offset4 = ins_cache[5];
      break;
      case 5:
        instr_dec->F_Type_DJNZ.op5 = ins_cache[1];
        instr_dec->F_Type_DJNZ.rn5 = ins_cache[2];
        instr_dec->F_Type_DJNZ.offset5 = ins_cache[5];
      break;
      case 6:
        instr_dec->F_Type_HLT.op6 = ins_cache[3];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void m8051::behavior() {

  void* vet[] = {&&I_Init, &&I_add_a_rn, &&I_sub_a_rn, &&I_anl_a_rn, &&I_orl_a_rn, 
              &&I_xrl_a_rn, &&I_mov_a_rn, &&I_mov_rn_a, &&I_inc_rn, &&I_dec_rn, 
              &&I_mov_a_imm, &&I_add_a_imm, &&I_mov_rn_imm, &&I_sjmp, &&I_jz, 
              &&I_jnz, &&I_djnz_rn, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_a_rn: // Instruction add_a_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_add_a_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_sub_a_rn: // Instruction sub_a_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_sub_a_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_anl_a_rn: // Instruction anl_a_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_anl_a_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_orl_a_rn: // Instruction orl_a_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_orl_a_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_xrl_a_rn: // Instruction xrl_a_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_xrl_a_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_mov_a_rn: // Instruction mov_a_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_mov_a_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_mov_rn_a: // Instruction mov_rn_a
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_mov_rn_a(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_inc_rn: // Instruction inc_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_inc_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_dec_rn: // Instruction dec_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_1B(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    ISA.behavior_dec_rn(instr_dec->F_Type_1B.op1, instr_dec->F_Type_1B.rn1);
    goto *dispatch();

  I_mov_a_imm: // Instruction mov_a_imm
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_2B(instr_dec->F_Type_2B.op2, instr_dec->F_Type_2B.imm2);
    ISA.behavior_mov_a_imm(instr_dec->F_Type_2B.op2, instr_dec->F_Type_2B.imm2);
    goto *dispatch();

  I_add_a_imm: // Instruction add_a_imm
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_2B(instr_dec->F_Type_2B.op2, instr_dec->F_Type_2B.imm2);
    ISA.behavior_add_a_imm(instr_dec->F_Type_2B.op2, instr_dec->F_Type_2B.imm2);
    goto *dispatch();

  I_mov_rn_imm: // Instruction mov_rn_imm
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_2BR(instr_dec->F_Type_2BR.op3, instr_dec->F_Type_2BR.rn3, instr_dec->F_Type_2BR.imm3);
    ISA.behavior_mov_rn_imm(instr_dec->F_Type_2BR.op3, instr_dec->F_Type_2BR.rn3, instr_dec->F_Type_2BR.imm3);
    goto *dispatch();

  I_sjmp: // Instruction sjmp
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_REL(instr_dec->F_Type_REL.op4, instr_dec->F_Type_REL.offset4);
    ISA.behavior_sjmp(instr_dec->F_Type_REL.op4, instr_dec->F_Type_REL.offset4);
    goto *dispatch();

  I_jz: // Instruction jz
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_REL(instr_dec->F_Type_REL.op4, instr_dec->F_Type_REL.offset4);
    ISA.behavior_jz(instr_dec->F_Type_REL.op4, instr_dec->F_Type_REL.offset4);
    goto *dispatch();

  I_jnz: // Instruction jnz
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_REL(instr_dec->F_Type_REL.op4, instr_dec->F_Type_REL.offset4);
    ISA.behavior_jnz(instr_dec->F_Type_REL.op4, instr_dec->F_Type_REL.offset4);
    goto *dispatch();

  I_djnz_rn: // Instruction djnz_rn
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_DJNZ(instr_dec->F_Type_DJNZ.op5, instr_dec->F_Type_DJNZ.rn5, instr_dec->F_Type_DJNZ.offset5);
    ISA.behavior_djnz_rn(instr_dec->F_Type_DJNZ.op5, instr_dec->F_Type_DJNZ.rn5, instr_dec->F_Type_DJNZ.offset5);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction();
    ISA._behavior_m8051_Type_HLT(instr_dec->F_Type_HLT.op6);
    ISA.behavior_halt(instr_dec->F_Type_HLT.op6);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void m8051::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void m8051::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void m8051::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void m8051::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void m8051::load(char* program) {
  DM_mport.load(program);
}

void m8051::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned m8051::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void m8051::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void m8051::PrintStat() {
  ac_arch<m8051_parms::ac_word, m8051_parms::ac_Hword>::PrintStat();
}

