/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "m8051_isa.H"

//!Fields table declaration.
ac_dec_field m8051_parms::m8051_isa::fields[m8051_parms::AC_DEC_FIELD_NUMBER] = {
  {"op1", 5, 4, 1, 0, 0, &(m8051_parms::m8051_isa::fields[1])},
  {"rn1", 3, 7, 2, 0, 0, NULL},
  {"op2", 8, 7, 3, 0, 0, &(m8051_parms::m8051_isa::fields[3])},
  {"imm2", 8, 15, 4, 0, 0, NULL},
  {"op3", 5, 4, 1, 0, 0, &(m8051_parms::m8051_isa::fields[5])},
  {"rn3", 3, 7, 2, 0, 0, &(m8051_parms::m8051_isa::fields[6])},
  {"imm3", 8, 15, 4, 0, 0, NULL},
  {"op4", 8, 7, 3, 0, 0, &(m8051_parms::m8051_isa::fields[8])},
  {"offset4", 8, 15, 5, 0, 1, NULL},
  {"op5", 5, 4, 1, 0, 0, &(m8051_parms::m8051_isa::fields[10])},
  {"rn5", 3, 7, 2, 0, 0, &(m8051_parms::m8051_isa::fields[11])},
  {"offset5", 8, 15, 5, 0, 1, NULL},
  {"op6", 8, 7, 3, 0, 0, NULL}
};

ac_dec_format m8051_parms::m8051_isa::formats[m8051_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_1B", 8, &(m8051_parms::m8051_isa::fields[0]), &(m8051_parms::m8051_isa::formats[1])},
  {2, "Type_2B", 16, &(m8051_parms::m8051_isa::fields[2]), &(m8051_parms::m8051_isa::formats[2])},
  {3, "Type_2BR", 16, &(m8051_parms::m8051_isa::fields[4]), &(m8051_parms::m8051_isa::formats[3])},
  {4, "Type_REL", 16, &(m8051_parms::m8051_isa::fields[7]), &(m8051_parms::m8051_isa::formats[4])},
  {5, "Type_DJNZ", 16, &(m8051_parms::m8051_isa::fields[9]), &(m8051_parms::m8051_isa::formats[5])},
  {6, "Type_HLT", 8, &(m8051_parms::m8051_isa::fields[12]), NULL}
};

ac_dec_list m8051_parms::m8051_isa::dec_list[m8051_parms::AC_DEC_LIST_NUMBER] = {
  {"op1", 1, 5, NULL},
  {"op1", 1, 19, NULL},
  {"op1", 1, 11, NULL},
  {"op1", 1, 9, NULL},
  {"op1", 1, 13, NULL},
  {"op1", 1, 29, NULL},
  {"op1", 1, 31, NULL},
  {"op1", 1, 1, NULL},
  {"op1", 1, 3, NULL},
  {"op2", 3, 116, NULL},
  {"op2", 3, 36, NULL},
  {"op3", 1, 15, NULL},
  {"op4", 3, 128, NULL},
  {"op4", 3, 96, NULL},
  {"op4", 3, 112, NULL},
  {"op5", 1, 27, NULL},
  {"op6", 3, 165, NULL}
};

ac_dec_instr m8051_parms::m8051_isa::instructions[m8051_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_a_rn", 1, "add", "add a, %rn1", "Type_1B", 1, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[0]), 0, &(m8051_parms::m8051_isa::instructions[1])},
  {"sub_a_rn", 1, "subb", "subb a, %rn1", "Type_1B", 2, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[1]), 0, &(m8051_parms::m8051_isa::instructions[2])},
  {"anl_a_rn", 1, "anl", "anl a, %rn1", "Type_1B", 3, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[2]), 0, &(m8051_parms::m8051_isa::instructions[3])},
  {"orl_a_rn", 1, "orl", "orl a, %rn1", "Type_1B", 4, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[3]), 0, &(m8051_parms::m8051_isa::instructions[4])},
  {"xrl_a_rn", 1, "xrl", "xrl a, %rn1", "Type_1B", 5, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[4]), 0, &(m8051_parms::m8051_isa::instructions[5])},
  {"mov_a_rn", 1, "mov", "mov a, %rn1", "Type_1B", 6, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[5]), 0, &(m8051_parms::m8051_isa::instructions[6])},
  {"mov_rn_a", 1, "mov", "mov %rn1, a", "Type_1B", 7, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[6]), 0, &(m8051_parms::m8051_isa::instructions[7])},
  {"inc_rn", 1, "inc", "inc %rn1", "Type_1B", 8, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[7]), 0, &(m8051_parms::m8051_isa::instructions[8])},
  {"dec_rn", 1, "dec", "dec %rn1", "Type_1B", 9, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[8]), 0, &(m8051_parms::m8051_isa::instructions[9])},
  {"mov_a_imm", 2, "mov", "mov a, #%imm2", "Type_2B", 10, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[9]), 0, &(m8051_parms::m8051_isa::instructions[10])},
  {"add_a_imm", 2, "add", "add a, #%imm2", "Type_2B", 11, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[10]), 0, &(m8051_parms::m8051_isa::instructions[11])},
  {"mov_rn_imm", 2, "mov", "mov %rn3, #%imm3", "Type_2BR", 12, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[11]), 0, &(m8051_parms::m8051_isa::instructions[12])},
  {"sjmp", 2, "sjmp", "sjmp %offset4", "Type_REL", 13, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[12]), 0, &(m8051_parms::m8051_isa::instructions[13])},
  {"jz", 2, "jz", "jz %offset4", "Type_REL", 14, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[13]), 0, &(m8051_parms::m8051_isa::instructions[14])},
  {"jnz", 2, "jnz", "jnz %offset4", "Type_REL", 15, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[14]), 0, &(m8051_parms::m8051_isa::instructions[15])},
  {"djnz_rn", 2, "djnz", "djnz %rn5, %offset5", "Type_DJNZ", 16, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[15]), 0, &(m8051_parms::m8051_isa::instructions[16])},
  {"halt", 1, "halt", "halt", "Type_HLT", 17, 1, 1, 1, &(m8051_parms::m8051_isa::dec_list[16]), 0, NULL}
};

const ac_instr_info
m8051_parms::m8051_isa::instr_table[m8051_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 1),
  ac_instr_info(1, "add_a_rn", "add", 1),
  ac_instr_info(2, "sub_a_rn", "subb", 1),
  ac_instr_info(3, "anl_a_rn", "anl", 1),
  ac_instr_info(4, "orl_a_rn", "orl", 1),
  ac_instr_info(5, "xrl_a_rn", "xrl", 1),
  ac_instr_info(6, "mov_a_rn", "mov", 1),
  ac_instr_info(7, "mov_rn_a", "mov", 1),
  ac_instr_info(8, "inc_rn", "inc", 1),
  ac_instr_info(9, "dec_rn", "dec", 1),
  ac_instr_info(10, "mov_a_imm", "mov", 2),
  ac_instr_info(11, "add_a_imm", "add", 2),
  ac_instr_info(12, "mov_rn_imm", "mov", 2),
  ac_instr_info(13, "sjmp", "sjmp", 2),
  ac_instr_info(14, "jz", "jz", 2),
  ac_instr_info(15, "jnz", "jnz", 2),
  ac_instr_info(16, "djnz_rn", "djnz", 2),
  ac_instr_info(17, "halt", "halt", 1)
};

const unsigned m8051_parms::m8051_isa::instr_format_table[m8051_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  3,
  4,
  4,
  4,
  5,
  6
};
