/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "m8051_arch.H"
#include  "m8051_arch_ref.H"

//!/Default constructor.
m8051_arch_ref::m8051_arch_ref(m8051_arch& arch) : ac_arch_ref<m8051_parms::ac_word, m8051_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   RB(arch.RB),   acc(arch.acc),   b_reg(arch.b_reg),   dptr(arch.dptr),   sp_reg(arch.sp_reg),   psw(arch.psw) {}

