/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "powerpc_isa.H"

//!Fields table declaration.
ac_dec_field powerpc_parms::powerpc_isa::fields[powerpc_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 6, 5, 1, 0, 0, &(powerpc_parms::powerpc_isa::fields[1])},
  {"rt", 5, 10, 2, 0, 0, &(powerpc_parms::powerpc_isa::fields[2])},
  {"ra", 5, 15, 3, 0, 0, &(powerpc_parms::powerpc_isa::fields[3])},
  {"rb", 5, 20, 4, 0, 0, &(powerpc_parms::powerpc_isa::fields[4])},
  {"oe", 1, 21, 5, 0, 0, &(powerpc_parms::powerpc_isa::fields[5])},
  {"xo", 10, 31, 6, 0, 0, NULL},
  {"op", 6, 5, 1, 0, 0, &(powerpc_parms::powerpc_isa::fields[7])},
  {"rt", 5, 10, 2, 0, 0, &(powerpc_parms::powerpc_isa::fields[8])},
  {"ra", 5, 15, 3, 0, 0, &(powerpc_parms::powerpc_isa::fields[9])},
  {"d", 16, 31, 7, 0, 1, NULL},
  {"op", 6, 5, 1, 0, 0, &(powerpc_parms::powerpc_isa::fields[11])},
  {"bo", 5, 10, 2, 0, 0, &(powerpc_parms::powerpc_isa::fields[12])},
  {"bi", 5, 15, 3, 0, 0, &(powerpc_parms::powerpc_isa::fields[13])},
  {"bd", 14, 29, 8, 0, 1, &(powerpc_parms::powerpc_isa::fields[14])},
  {"aa", 1, 30, 9, 0, 0, &(powerpc_parms::powerpc_isa::fields[15])},
  {"lk", 1, 31, 10, 0, 0, NULL},
  {"op", 6, 5, 1, 0, 0, &(powerpc_parms::powerpc_isa::fields[17])},
  {"li", 24, 29, 11, 0, 1, &(powerpc_parms::powerpc_isa::fields[18])},
  {"aa", 1, 30, 9, 0, 0, &(powerpc_parms::powerpc_isa::fields[19])},
  {"lk", 1, 31, 10, 0, 0, NULL},
  {"op", 6, 5, 1, 0, 0, &(powerpc_parms::powerpc_isa::fields[21])},
  {"imm", 26, 31, 12, 0, 0, NULL}
};

ac_dec_format powerpc_parms::powerpc_isa::formats[powerpc_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_XO", 32, &(powerpc_parms::powerpc_isa::fields[0]), &(powerpc_parms::powerpc_isa::formats[1])},
  {2, "Type_D", 32, &(powerpc_parms::powerpc_isa::fields[6]), &(powerpc_parms::powerpc_isa::formats[2])},
  {3, "Type_B", 32, &(powerpc_parms::powerpc_isa::fields[10]), &(powerpc_parms::powerpc_isa::formats[3])},
  {4, "Type_I", 32, &(powerpc_parms::powerpc_isa::fields[16]), &(powerpc_parms::powerpc_isa::formats[4])},
  {5, "Type_HLT", 32, &(powerpc_parms::powerpc_isa::fields[20]), NULL}
};

ac_dec_list powerpc_parms::powerpc_isa::dec_list[powerpc_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[1])},
  {"xo", 6, 266, &(powerpc_parms::powerpc_isa::dec_list[2])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[4])},
  {"xo", 6, 40, &(powerpc_parms::powerpc_isa::dec_list[5])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[7])},
  {"xo", 6, 28, &(powerpc_parms::powerpc_isa::dec_list[8])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[10])},
  {"xo", 6, 444, &(powerpc_parms::powerpc_isa::dec_list[11])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[13])},
  {"xo", 6, 316, &(powerpc_parms::powerpc_isa::dec_list[14])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[16])},
  {"xo", 6, 24, &(powerpc_parms::powerpc_isa::dec_list[17])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[19])},
  {"xo", 6, 536, &(powerpc_parms::powerpc_isa::dec_list[20])},
  {"oe", 5, 0, NULL},
  {"op", 1, 31, &(powerpc_parms::powerpc_isa::dec_list[22])},
  {"xo", 6, 792, &(powerpc_parms::powerpc_isa::dec_list[23])},
  {"oe", 5, 0, NULL},
  {"op", 1, 14, NULL},
  {"op", 1, 13, NULL},
  {"op", 1, 15, NULL},
  {"op", 1, 24, NULL},
  {"op", 1, 28, NULL},
  {"op", 1, 32, NULL},
  {"op", 1, 36, NULL},
  {"op", 1, 16, NULL},
  {"op", 1, 18, NULL},
  {"op", 1, 63, NULL}
};

ac_dec_instr powerpc_parms::powerpc_isa::instructions[powerpc_parms::AC_DEC_INSTR_NUMBER] = {
  {"add", 4, "add", "add %rt, %ra, %rb", "Type_XO", 1, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[0]), 0, &(powerpc_parms::powerpc_isa::instructions[1])},
  {"subf", 4, "subf", "subf %rt, %ra, %rb", "Type_XO", 2, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[3]), 0, &(powerpc_parms::powerpc_isa::instructions[2])},
  {"and_op", 4, "and", "and %ra, %rt, %rb", "Type_XO", 3, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[6]), 0, &(powerpc_parms::powerpc_isa::instructions[3])},
  {"or_op", 4, "or", "or %ra, %rt, %rb", "Type_XO", 4, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[9]), 0, &(powerpc_parms::powerpc_isa::instructions[4])},
  {"xor_op", 4, "xor", "xor %ra, %rt, %rb", "Type_XO", 5, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[12]), 0, &(powerpc_parms::powerpc_isa::instructions[5])},
  {"slw", 4, "slw", "slw %ra, %rt, %rb", "Type_XO", 6, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[15]), 0, &(powerpc_parms::powerpc_isa::instructions[6])},
  {"srw", 4, "srw", "srw %ra, %rt, %rb", "Type_XO", 7, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[18]), 0, &(powerpc_parms::powerpc_isa::instructions[7])},
  {"sraw", 4, "sraw", "sraw %ra, %rt, %rb", "Type_XO", 8, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[21]), 0, &(powerpc_parms::powerpc_isa::instructions[8])},
  {"addi", 4, "addi", "addi %rt, %ra, %d", "Type_D", 9, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[24]), 0, &(powerpc_parms::powerpc_isa::instructions[9])},
  {"addic_dot", 4, "addic.", "addic. %rt, %ra, %d", "Type_D", 10, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[25]), 0, &(powerpc_parms::powerpc_isa::instructions[10])},
  {"addis", 4, "addis", "addis %rt, %ra, %d", "Type_D", 11, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[26]), 0, &(powerpc_parms::powerpc_isa::instructions[11])},
  {"ori", 4, "ori", "ori %ra, %rt, %d", "Type_D", 12, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[27]), 0, &(powerpc_parms::powerpc_isa::instructions[12])},
  {"andi_dot", 4, "andi.", "andi. %ra, %rt, %d", "Type_D", 13, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[28]), 0, &(powerpc_parms::powerpc_isa::instructions[13])},
  {"lwz", 4, "lwz", "lwz %rt, %d(%ra)", "Type_D", 14, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[29]), 0, &(powerpc_parms::powerpc_isa::instructions[14])},
  {"stw", 4, "stw", "stw %rt, %d(%ra)", "Type_D", 15, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[30]), 0, &(powerpc_parms::powerpc_isa::instructions[15])},
  {"bc", 4, "bc", "bc %bo, %bi, %bd", "Type_B", 16, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[31]), 0, &(powerpc_parms::powerpc_isa::instructions[16])},
  {"b", 4, "b", "b %li", "Type_I", 17, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[32]), 0, &(powerpc_parms::powerpc_isa::instructions[17])},
  {"halt", 4, "halt", "halt", "Type_HLT", 18, 1, 1, 1, &(powerpc_parms::powerpc_isa::dec_list[33]), 0, NULL}
};

const ac_instr_info
powerpc_parms::powerpc_isa::instr_table[powerpc_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "add", "add", 4),
  ac_instr_info(2, "subf", "subf", 4),
  ac_instr_info(3, "and_op", "and", 4),
  ac_instr_info(4, "or_op", "or", 4),
  ac_instr_info(5, "xor_op", "xor", 4),
  ac_instr_info(6, "slw", "slw", 4),
  ac_instr_info(7, "srw", "srw", 4),
  ac_instr_info(8, "sraw", "sraw", 4),
  ac_instr_info(9, "addi", "addi", 4),
  ac_instr_info(10, "addic_dot", "addic.", 4),
  ac_instr_info(11, "addis", "addis", 4),
  ac_instr_info(12, "ori", "ori", 4),
  ac_instr_info(13, "andi_dot", "andi.", 4),
  ac_instr_info(14, "lwz", "lwz", 4),
  ac_instr_info(15, "stw", "stw", 4),
  ac_instr_info(16, "bc", "bc", 4),
  ac_instr_info(17, "b", "b", 4),
  ac_instr_info(18, "halt", "halt", 4)
};

const unsigned powerpc_parms::powerpc_isa::instr_format_table[powerpc_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  4,
  5
};
