/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "powerpc.H"
#include  "powerpc_isa.cpp"

#include  "powerpc_syscall.H"

void* powerpc::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_XO.op = ins_cache[1];
        instr_dec->F_Type_XO.rt = ins_cache[2];
        instr_dec->F_Type_XO.ra = ins_cache[3];
        instr_dec->F_Type_XO.rb = ins_cache[4];
        instr_dec->F_Type_XO.oe = ins_cache[5];
        instr_dec->F_Type_XO.xo = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_D.op = ins_cache[1];
        instr_dec->F_Type_D.rt = ins_cache[2];
        instr_dec->F_Type_D.ra = ins_cache[3];
        instr_dec->F_Type_D.d = ins_cache[7];
      break;
      case 3:
        instr_dec->F_Type_B.op = ins_cache[1];
        instr_dec->F_Type_B.bo = ins_cache[2];
        instr_dec->F_Type_B.bi = ins_cache[3];
        instr_dec->F_Type_B.bd = ins_cache[8];
        instr_dec->F_Type_B.aa = ins_cache[9];
        instr_dec->F_Type_B.lk = ins_cache[10];
      break;
      case 4:
        instr_dec->F_Type_I.op = ins_cache[1];
        instr_dec->F_Type_I.li = ins_cache[11];
        instr_dec->F_Type_I.aa = ins_cache[9];
        instr_dec->F_Type_I.lk = ins_cache[10];
      break;
      case 5:
        instr_dec->F_Type_HLT.op = ins_cache[1];
        instr_dec->F_Type_HLT.imm = ins_cache[12];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void powerpc::behavior() {

  void* vet[] = {&&I_Init, &&I_add, &&I_subf, &&I_and_op, &&I_or_op, 
              &&I_xor_op, &&I_slw, &&I_srw, &&I_sraw, &&I_addi, 
              &&I_addic_dot, &&I_addis, &&I_ori, &&I_andi_dot, &&I_lwz, 
              &&I_stw, &&I_bc, &&I_b, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add: // Instruction add
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_add(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_subf: // Instruction subf
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_subf(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_and_op: // Instruction and_op
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_and_op(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_or_op: // Instruction or_op
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_or_op(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_xor_op: // Instruction xor_op
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_xor_op(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_slw: // Instruction slw
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_slw(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_srw: // Instruction srw
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_srw(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_sraw: // Instruction sraw
    ISA._behavior_instruction(instr_dec->F_Type_XO.op);
    ISA._behavior_powerpc_Type_XO(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    ISA.behavior_sraw(instr_dec->F_Type_XO.op, instr_dec->F_Type_XO.rt, instr_dec->F_Type_XO.ra, instr_dec->F_Type_XO.rb, instr_dec->F_Type_XO.oe, instr_dec->F_Type_XO.xo);
    goto *dispatch();

  I_addi: // Instruction addi
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_addi(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_addic_dot: // Instruction addic_dot
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_addic_dot(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_addis: // Instruction addis
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_addis(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_ori: // Instruction ori
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_ori(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_andi_dot: // Instruction andi_dot
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_andi_dot(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_lwz: // Instruction lwz
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_lwz(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_stw: // Instruction stw
    ISA._behavior_instruction(instr_dec->F_Type_D.op);
    ISA._behavior_powerpc_Type_D(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    ISA.behavior_stw(instr_dec->F_Type_D.op, instr_dec->F_Type_D.rt, instr_dec->F_Type_D.ra, instr_dec->F_Type_D.d);
    goto *dispatch();

  I_bc: // Instruction bc
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_powerpc_Type_B(instr_dec->F_Type_B.op, instr_dec->F_Type_B.bo, instr_dec->F_Type_B.bi, instr_dec->F_Type_B.bd, instr_dec->F_Type_B.aa, instr_dec->F_Type_B.lk);
    ISA.behavior_bc(instr_dec->F_Type_B.op, instr_dec->F_Type_B.bo, instr_dec->F_Type_B.bi, instr_dec->F_Type_B.bd, instr_dec->F_Type_B.aa, instr_dec->F_Type_B.lk);
    goto *dispatch();

  I_b: // Instruction b
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_powerpc_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.li, instr_dec->F_Type_I.aa, instr_dec->F_Type_I.lk);
    ISA.behavior_b(instr_dec->F_Type_I.op, instr_dec->F_Type_I.li, instr_dec->F_Type_I.aa, instr_dec->F_Type_I.lk);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_HLT.op);
    ISA._behavior_powerpc_Type_HLT(instr_dec->F_Type_HLT.op, instr_dec->F_Type_HLT.imm);
    ISA.behavior_halt(instr_dec->F_Type_HLT.op, instr_dec->F_Type_HLT.imm);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void powerpc::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void powerpc::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void powerpc::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void powerpc::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void powerpc::load(char* program) {
  DM_mport.load(program);
}

void powerpc::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned powerpc::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void powerpc::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void powerpc::PrintStat() {
  ac_arch<powerpc_parms::ac_word, powerpc_parms::ac_Hword>::PrintStat();
}

