/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "powerpc_arch.H"
#include  "powerpc_arch_ref.H"

//!/Default constructor.
powerpc_arch_ref::powerpc_arch_ref(powerpc_arch& arch) : ac_arch_ref<powerpc_parms::ac_word, powerpc_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   RB(arch.RB),   cr(arch.cr),   lr(arch.lr),   ctr(arch.ctr) {}

