/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "esp32_arch.H"


esp32_arch::esp32_arch() :
  ac_arch_dec_if<esp32_parms::ac_word, esp32_parms::ac_Hword>(esp32_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  AR("AR"),
  sar("sar", 0),
  lcount("lcount", 0),
  lbeg("lbeg", 0),
  lend("lend", 0),
  ps("ps", 0) {

  ac_mt_endian = esp32_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = esp32_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int esp32_arch::globalId = 0;