/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "esp32.H"
#include  "esp32_isa.cpp"

#include  "esp32_syscall.H"

void* esp32::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_RRR.op = ins_cache[1];
        instr_dec->F_Type_RRR.op1 = ins_cache[2];
        instr_dec->F_Type_RRR.r = ins_cache[3];
        instr_dec->F_Type_RRR.s = ins_cache[4];
        instr_dec->F_Type_RRR.t = ins_cache[5];
        instr_dec->F_Type_RRR.op2 = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_RRI8.op = ins_cache[1];
        instr_dec->F_Type_RRI8.imm8 = ins_cache[7];
        instr_dec->F_Type_RRI8.s = ins_cache[4];
        instr_dec->F_Type_RRI8.t = ins_cache[5];
        instr_dec->F_Type_RRI8.pad1 = ins_cache[6];
      break;
      case 3:
        instr_dec->F_Type_RI16.op = ins_cache[1];
        instr_dec->F_Type_RI16.t = ins_cache[2];
        instr_dec->F_Type_RI16.imm16 = ins_cache[8];
        instr_dec->F_Type_RI16.pad2 = ins_cache[9];
      break;
      case 4:
        instr_dec->F_Type_L32I.op = ins_cache[1];
        instr_dec->F_Type_L32I.disp = ins_cache[10];
        instr_dec->F_Type_L32I.s = ins_cache[4];
        instr_dec->F_Type_L32I.t = ins_cache[5];
        instr_dec->F_Type_L32I.pad3 = ins_cache[6];
      break;
      case 5:
        instr_dec->F_Type_Branch.op = ins_cache[1];
        instr_dec->F_Type_Branch.bdisp = ins_cache[11];
        instr_dec->F_Type_Branch.s = ins_cache[5];
        instr_dec->F_Type_Branch.t = ins_cache[12];
        instr_dec->F_Type_Branch.pad4 = ins_cache[9];
      break;
      case 6:
        instr_dec->F_Type_Jump.op = ins_cache[1];
        instr_dec->F_Type_Jump.target = ins_cache[13];
        instr_dec->F_Type_Jump.pad5 = ins_cache[14];
      break;
      case 7:
        instr_dec->F_Type_Loop.op = ins_cache[1];
        instr_dec->F_Type_Loop.ldisp = ins_cache[10];
        instr_dec->F_Type_Loop.s = ins_cache[4];
        instr_dec->F_Type_Loop.pad6 = ins_cache[15];
      break;
      case 8:
        instr_dec->F_Type_Halt.op = ins_cache[1];
        instr_dec->F_Type_Halt.pad7 = ins_cache[16];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void esp32::behavior() {

  void* vet[] = {&&I_Init, &&I_add_op, &&I_sub_op, &&I_and_op, &&I_or_op, 
              &&I_xor_op, &&I_mull_op, &&I_addi_op, &&I_addmi_op, &&I_movi_op, 
              &&I_l32i_op, &&I_s32i_op, &&I_bne_op, &&I_beq_op, &&I_blt_op, 
              &&I_bge_op, &&I_j_op, &&I_call0_op, &&I_loop_op, &&I_halt_op};

  IntRoutine = vet;

  if (has_delayed_load) {
    IROM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_op: // Instruction add_op
    ISA._behavior_instruction(instr_dec->F_Type_RRR.op);
    ISA._behavior_esp32_Type_RRR(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    ISA.behavior_add_op(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    goto *dispatch();

  I_sub_op: // Instruction sub_op
    ISA._behavior_instruction(instr_dec->F_Type_RRR.op);
    ISA._behavior_esp32_Type_RRR(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    ISA.behavior_sub_op(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    goto *dispatch();

  I_and_op: // Instruction and_op
    ISA._behavior_instruction(instr_dec->F_Type_RRR.op);
    ISA._behavior_esp32_Type_RRR(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    ISA.behavior_and_op(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    goto *dispatch();

  I_or_op: // Instruction or_op
    ISA._behavior_instruction(instr_dec->F_Type_RRR.op);
    ISA._behavior_esp32_Type_RRR(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    ISA.behavior_or_op(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    goto *dispatch();

  I_xor_op: // Instruction xor_op
    ISA._behavior_instruction(instr_dec->F_Type_RRR.op);
    ISA._behavior_esp32_Type_RRR(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    ISA.behavior_xor_op(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    goto *dispatch();

  I_mull_op: // Instruction mull_op
    ISA._behavior_instruction(instr_dec->F_Type_RRR.op);
    ISA._behavior_esp32_Type_RRR(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    ISA.behavior_mull_op(instr_dec->F_Type_RRR.op, instr_dec->F_Type_RRR.op1, instr_dec->F_Type_RRR.r, instr_dec->F_Type_RRR.s, instr_dec->F_Type_RRR.t, instr_dec->F_Type_RRR.op2);
    goto *dispatch();

  I_addi_op: // Instruction addi_op
    ISA._behavior_instruction(instr_dec->F_Type_RRI8.op);
    ISA._behavior_esp32_Type_RRI8(instr_dec->F_Type_RRI8.op, instr_dec->F_Type_RRI8.imm8, instr_dec->F_Type_RRI8.s, instr_dec->F_Type_RRI8.t, instr_dec->F_Type_RRI8.pad1);
    ISA.behavior_addi_op(instr_dec->F_Type_RRI8.op, instr_dec->F_Type_RRI8.imm8, instr_dec->F_Type_RRI8.s, instr_dec->F_Type_RRI8.t, instr_dec->F_Type_RRI8.pad1);
    goto *dispatch();

  I_addmi_op: // Instruction addmi_op
    ISA._behavior_instruction(instr_dec->F_Type_RRI8.op);
    ISA._behavior_esp32_Type_RRI8(instr_dec->F_Type_RRI8.op, instr_dec->F_Type_RRI8.imm8, instr_dec->F_Type_RRI8.s, instr_dec->F_Type_RRI8.t, instr_dec->F_Type_RRI8.pad1);
    ISA.behavior_addmi_op(instr_dec->F_Type_RRI8.op, instr_dec->F_Type_RRI8.imm8, instr_dec->F_Type_RRI8.s, instr_dec->F_Type_RRI8.t, instr_dec->F_Type_RRI8.pad1);
    goto *dispatch();

  I_movi_op: // Instruction movi_op
    ISA._behavior_instruction(instr_dec->F_Type_RI16.op);
    ISA._behavior_esp32_Type_RI16(instr_dec->F_Type_RI16.op, instr_dec->F_Type_RI16.t, instr_dec->F_Type_RI16.imm16, instr_dec->F_Type_RI16.pad2);
    ISA.behavior_movi_op(instr_dec->F_Type_RI16.op, instr_dec->F_Type_RI16.t, instr_dec->F_Type_RI16.imm16, instr_dec->F_Type_RI16.pad2);
    goto *dispatch();

  I_l32i_op: // Instruction l32i_op
    ISA._behavior_instruction(instr_dec->F_Type_L32I.op);
    ISA._behavior_esp32_Type_L32I(instr_dec->F_Type_L32I.op, instr_dec->F_Type_L32I.disp, instr_dec->F_Type_L32I.s, instr_dec->F_Type_L32I.t, instr_dec->F_Type_L32I.pad3);
    ISA.behavior_l32i_op(instr_dec->F_Type_L32I.op, instr_dec->F_Type_L32I.disp, instr_dec->F_Type_L32I.s, instr_dec->F_Type_L32I.t, instr_dec->F_Type_L32I.pad3);
    goto *dispatch();

  I_s32i_op: // Instruction s32i_op
    ISA._behavior_instruction(instr_dec->F_Type_L32I.op);
    ISA._behavior_esp32_Type_L32I(instr_dec->F_Type_L32I.op, instr_dec->F_Type_L32I.disp, instr_dec->F_Type_L32I.s, instr_dec->F_Type_L32I.t, instr_dec->F_Type_L32I.pad3);
    ISA.behavior_s32i_op(instr_dec->F_Type_L32I.op, instr_dec->F_Type_L32I.disp, instr_dec->F_Type_L32I.s, instr_dec->F_Type_L32I.t, instr_dec->F_Type_L32I.pad3);
    goto *dispatch();

  I_bne_op: // Instruction bne_op
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_esp32_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    ISA.behavior_bne_op(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    goto *dispatch();

  I_beq_op: // Instruction beq_op
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_esp32_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    ISA.behavior_beq_op(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    goto *dispatch();

  I_blt_op: // Instruction blt_op
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_esp32_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    ISA.behavior_blt_op(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    goto *dispatch();

  I_bge_op: // Instruction bge_op
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_esp32_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    ISA.behavior_bge_op(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.bdisp, instr_dec->F_Type_Branch.s, instr_dec->F_Type_Branch.t, instr_dec->F_Type_Branch.pad4);
    goto *dispatch();

  I_j_op: // Instruction j_op
    ISA._behavior_instruction(instr_dec->F_Type_Jump.op);
    ISA._behavior_esp32_Type_Jump(instr_dec->F_Type_Jump.op, instr_dec->F_Type_Jump.target, instr_dec->F_Type_Jump.pad5);
    ISA.behavior_j_op(instr_dec->F_Type_Jump.op, instr_dec->F_Type_Jump.target, instr_dec->F_Type_Jump.pad5);
    goto *dispatch();

  I_call0_op: // Instruction call0_op
    ISA._behavior_instruction(instr_dec->F_Type_Jump.op);
    ISA._behavior_esp32_Type_Jump(instr_dec->F_Type_Jump.op, instr_dec->F_Type_Jump.target, instr_dec->F_Type_Jump.pad5);
    ISA.behavior_call0_op(instr_dec->F_Type_Jump.op, instr_dec->F_Type_Jump.target, instr_dec->F_Type_Jump.pad5);
    goto *dispatch();

  I_loop_op: // Instruction loop_op
    ISA._behavior_instruction(instr_dec->F_Type_Loop.op);
    ISA._behavior_esp32_Type_Loop(instr_dec->F_Type_Loop.op, instr_dec->F_Type_Loop.ldisp, instr_dec->F_Type_Loop.s, instr_dec->F_Type_Loop.pad6);
    ISA.behavior_loop_op(instr_dec->F_Type_Loop.op, instr_dec->F_Type_Loop.ldisp, instr_dec->F_Type_Loop.s, instr_dec->F_Type_Loop.pad6);
    goto *dispatch();

  I_halt_op: // Instruction halt_op
    ISA._behavior_instruction(instr_dec->F_Type_Halt.op);
    ISA._behavior_esp32_Type_Halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad7);
    ISA.behavior_halt_op(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad7);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void esp32::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void esp32::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  IROM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void esp32::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void esp32::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void esp32::load(char* program) {
  IROM_mport.load(program);
}

void esp32::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned esp32::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void esp32::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void esp32::PrintStat() {
  ac_arch<esp32_parms::ac_word, esp32_parms::ac_Hword>::PrintStat();
}

