/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "esp32_isa.H"

//!Fields table declaration.
ac_dec_field esp32_parms::esp32_isa::fields[esp32_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[1])},
  {"op1", 4, 23, 2, 0, 0, &(esp32_parms::esp32_isa::fields[2])},
  {"r", 4, 19, 3, 0, 0, &(esp32_parms::esp32_isa::fields[3])},
  {"s", 4, 15, 4, 0, 0, &(esp32_parms::esp32_isa::fields[4])},
  {"t", 4, 11, 5, 0, 0, &(esp32_parms::esp32_isa::fields[5])},
  {"op2", 8, 7, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[7])},
  {"imm8", 8, 23, 7, 0, 1, &(esp32_parms::esp32_isa::fields[8])},
  {"s", 4, 15, 4, 0, 0, &(esp32_parms::esp32_isa::fields[9])},
  {"t", 4, 11, 5, 0, 0, &(esp32_parms::esp32_isa::fields[10])},
  {"pad1", 8, 7, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[12])},
  {"t", 4, 23, 2, 0, 0, &(esp32_parms::esp32_isa::fields[13])},
  {"imm16", 16, 19, 8, 0, 1, &(esp32_parms::esp32_isa::fields[14])},
  {"pad2", 4, 3, 9, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[16])},
  {"disp", 8, 23, 10, 0, 0, &(esp32_parms::esp32_isa::fields[17])},
  {"s", 4, 15, 4, 0, 0, &(esp32_parms::esp32_isa::fields[18])},
  {"t", 4, 11, 5, 0, 0, &(esp32_parms::esp32_isa::fields[19])},
  {"pad3", 8, 7, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[21])},
  {"bdisp", 12, 23, 11, 0, 1, &(esp32_parms::esp32_isa::fields[22])},
  {"s", 4, 11, 5, 0, 0, &(esp32_parms::esp32_isa::fields[23])},
  {"t", 4, 7, 12, 0, 0, &(esp32_parms::esp32_isa::fields[24])},
  {"pad4", 4, 3, 9, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[26])},
  {"target", 18, 23, 13, 0, 1, &(esp32_parms::esp32_isa::fields[27])},
  {"pad5", 6, 5, 14, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[29])},
  {"ldisp", 8, 23, 10, 0, 0, &(esp32_parms::esp32_isa::fields[30])},
  {"s", 4, 15, 4, 0, 0, &(esp32_parms::esp32_isa::fields[31])},
  {"pad6", 12, 11, 15, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(esp32_parms::esp32_isa::fields[33])},
  {"pad7", 24, 23, 16, 0, 0, NULL}
};

ac_dec_format esp32_parms::esp32_isa::formats[esp32_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_RRR", 32, &(esp32_parms::esp32_isa::fields[0]), &(esp32_parms::esp32_isa::formats[1])},
  {2, "Type_RRI8", 32, &(esp32_parms::esp32_isa::fields[6]), &(esp32_parms::esp32_isa::formats[2])},
  {3, "Type_RI16", 32, &(esp32_parms::esp32_isa::fields[11]), &(esp32_parms::esp32_isa::formats[3])},
  {4, "Type_L32I", 32, &(esp32_parms::esp32_isa::fields[15]), &(esp32_parms::esp32_isa::formats[4])},
  {5, "Type_Branch", 32, &(esp32_parms::esp32_isa::fields[20]), &(esp32_parms::esp32_isa::formats[5])},
  {6, "Type_Jump", 32, &(esp32_parms::esp32_isa::fields[25]), &(esp32_parms::esp32_isa::formats[6])},
  {7, "Type_Loop", 32, &(esp32_parms::esp32_isa::fields[28]), &(esp32_parms::esp32_isa::formats[7])},
  {8, "Type_Halt", 32, &(esp32_parms::esp32_isa::fields[32]), NULL}
};

ac_dec_list esp32_parms::esp32_isa::dec_list[esp32_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 0, &(esp32_parms::esp32_isa::dec_list[1])},
  {"op1", 2, 0, &(esp32_parms::esp32_isa::dec_list[2])},
  {"op2", 6, 8, NULL},
  {"op", 1, 0, &(esp32_parms::esp32_isa::dec_list[4])},
  {"op1", 2, 0, &(esp32_parms::esp32_isa::dec_list[5])},
  {"op2", 6, 12, NULL},
  {"op", 1, 0, &(esp32_parms::esp32_isa::dec_list[7])},
  {"op1", 2, 0, &(esp32_parms::esp32_isa::dec_list[8])},
  {"op2", 6, 1, NULL},
  {"op", 1, 0, &(esp32_parms::esp32_isa::dec_list[10])},
  {"op1", 2, 0, &(esp32_parms::esp32_isa::dec_list[11])},
  {"op2", 6, 2, NULL},
  {"op", 1, 0, &(esp32_parms::esp32_isa::dec_list[13])},
  {"op1", 2, 0, &(esp32_parms::esp32_isa::dec_list[14])},
  {"op2", 6, 3, NULL},
  {"op", 1, 0, &(esp32_parms::esp32_isa::dec_list[16])},
  {"op1", 2, 2, &(esp32_parms::esp32_isa::dec_list[17])},
  {"op2", 6, 8, NULL},
  {"op", 1, 2, NULL},
  {"op", 1, 13, NULL},
  {"op", 1, 10, NULL},
  {"op", 1, 6, NULL},
  {"op", 1, 7, NULL},
  {"op", 1, 23, NULL},
  {"op", 1, 22, NULL},
  {"op", 1, 20, NULL},
  {"op", 1, 21, NULL},
  {"op", 1, 5, NULL},
  {"op", 1, 9, NULL},
  {"op", 1, 18, NULL},
  {"op", 1, 127, NULL}
};

ac_dec_instr esp32_parms::esp32_isa::instructions[esp32_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_op", 4, "add", "add a%r, a%s, a%t", "Type_RRR", 1, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[0]), 0, &(esp32_parms::esp32_isa::instructions[1])},
  {"sub_op", 4, "sub", "sub a%r, a%s, a%t", "Type_RRR", 2, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[3]), 0, &(esp32_parms::esp32_isa::instructions[2])},
  {"and_op", 4, "and", "and a%r, a%s, a%t", "Type_RRR", 3, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[6]), 0, &(esp32_parms::esp32_isa::instructions[3])},
  {"or_op", 4, "or", "or a%r, a%s, a%t", "Type_RRR", 4, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[9]), 0, &(esp32_parms::esp32_isa::instructions[4])},
  {"xor_op", 4, "xor", "xor a%r, a%s, a%t", "Type_RRR", 5, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[12]), 0, &(esp32_parms::esp32_isa::instructions[5])},
  {"mull_op", 4, "mull", "mull a%r, a%s, a%t", "Type_RRR", 6, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[15]), 0, &(esp32_parms::esp32_isa::instructions[6])},
  {"addi_op", 4, "addi", "addi a%t, a%s, %imm8", "Type_RRI8", 7, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[18]), 0, &(esp32_parms::esp32_isa::instructions[7])},
  {"addmi_op", 4, "addmi", "addmi a%t, a%s, %imm8", "Type_RRI8", 8, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[19]), 0, &(esp32_parms::esp32_isa::instructions[8])},
  {"movi_op", 4, "movi", "movi a%t, %imm16", "Type_RI16", 9, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[20]), 0, &(esp32_parms::esp32_isa::instructions[9])},
  {"l32i_op", 4, "l32i", "l32i a%t, a%s, %disp", "Type_L32I", 10, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[21]), 0, &(esp32_parms::esp32_isa::instructions[10])},
  {"s32i_op", 4, "s32i", "s32i a%t, a%s, %disp", "Type_L32I", 11, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[22]), 0, &(esp32_parms::esp32_isa::instructions[11])},
  {"bne_op", 4, "bne", "bne a%s, a%t, %bdisp", "Type_Branch", 12, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[23]), 0, &(esp32_parms::esp32_isa::instructions[12])},
  {"beq_op", 4, "beq", "beq a%s, a%t, %bdisp", "Type_Branch", 13, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[24]), 0, &(esp32_parms::esp32_isa::instructions[13])},
  {"blt_op", 4, "blt", "blt a%s, a%t, %bdisp", "Type_Branch", 14, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[25]), 0, &(esp32_parms::esp32_isa::instructions[14])},
  {"bge_op", 4, "bge", "bge a%s, a%t, %bdisp", "Type_Branch", 15, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[26]), 0, &(esp32_parms::esp32_isa::instructions[15])},
  {"j_op", 4, "j", "j %target", "Type_Jump", 16, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[27]), 0, &(esp32_parms::esp32_isa::instructions[16])},
  {"call0_op", 4, "call0", "call0 %target", "Type_Jump", 17, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[28]), 0, &(esp32_parms::esp32_isa::instructions[17])},
  {"loop_op", 4, "loop", "loop a%s, %ldisp", "Type_Loop", 18, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[29]), 0, &(esp32_parms::esp32_isa::instructions[18])},
  {"halt_op", 4, "ill", "ill", "Type_Halt", 19, 1, 1, 1, &(esp32_parms::esp32_isa::dec_list[30]), 0, NULL}
};

const ac_instr_info
esp32_parms::esp32_isa::instr_table[esp32_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "add_op", "add", 4),
  ac_instr_info(2, "sub_op", "sub", 4),
  ac_instr_info(3, "and_op", "and", 4),
  ac_instr_info(4, "or_op", "or", 4),
  ac_instr_info(5, "xor_op", "xor", 4),
  ac_instr_info(6, "mull_op", "mull", 4),
  ac_instr_info(7, "addi_op", "addi", 4),
  ac_instr_info(8, "addmi_op", "addmi", 4),
  ac_instr_info(9, "movi_op", "movi", 4),
  ac_instr_info(10, "l32i_op", "l32i", 4),
  ac_instr_info(11, "s32i_op", "s32i", 4),
  ac_instr_info(12, "bne_op", "bne", 4),
  ac_instr_info(13, "beq_op", "beq", 4),
  ac_instr_info(14, "blt_op", "blt", 4),
  ac_instr_info(15, "bge_op", "bge", 4),
  ac_instr_info(16, "j_op", "j", 4),
  ac_instr_info(17, "call0_op", "call0", 4),
  ac_instr_info(18, "loop_op", "loop", 4),
  ac_instr_info(19, "halt_op", "ill", 4)
};

const unsigned esp32_parms::esp32_isa::instr_format_table[esp32_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  3,
  4,
  4,
  5,
  5,
  5,
  5,
  6,
  6,
  7,
  8
};
