/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "sparc.H"
#include  "sparc_isa.cpp"

#include  "sparc_syscall.H"

void* sparc::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_F2.op = ins_cache[1];
        instr_dec->F_Type_F2.rd = ins_cache[2];
        instr_dec->F_Type_F2.op2 = ins_cache[3];
        instr_dec->F_Type_F2.imm22 = ins_cache[4];
      break;
      case 2:
        instr_dec->F_Type_F3R.op = ins_cache[1];
        instr_dec->F_Type_F3R.rd = ins_cache[2];
        instr_dec->F_Type_F3R.op3 = ins_cache[5];
        instr_dec->F_Type_F3R.rs1 = ins_cache[6];
        instr_dec->F_Type_F3R.i = ins_cache[7];
        instr_dec->F_Type_F3R.asi = ins_cache[8];
        instr_dec->F_Type_F3R.rs2 = ins_cache[9];
      break;
      case 3:
        instr_dec->F_Type_F3I.op = ins_cache[1];
        instr_dec->F_Type_F3I.rd = ins_cache[2];
        instr_dec->F_Type_F3I.op3 = ins_cache[5];
        instr_dec->F_Type_F3I.rs1 = ins_cache[6];
        instr_dec->F_Type_F3I.i = ins_cache[7];
        instr_dec->F_Type_F3I.simm13 = ins_cache[10];
      break;
      case 4:
        instr_dec->F_Type_BR.op = ins_cache[1];
        instr_dec->F_Type_BR.a = ins_cache[11];
        instr_dec->F_Type_BR.cond = ins_cache[12];
        instr_dec->F_Type_BR.op2 = ins_cache[3];
        instr_dec->F_Type_BR.disp22 = ins_cache[13];
      break;
      case 5:
        instr_dec->F_Type_HLT.op = ins_cache[1];
        instr_dec->F_Type_HLT.rd = ins_cache[2];
        instr_dec->F_Type_HLT.op3 = ins_cache[5];
        instr_dec->F_Type_HLT.imm = ins_cache[14];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void sparc::behavior() {

  void* vet[] = {&&I_Init, &&I_add_r, &&I_sub_r, &&I_and_r, &&I_or_r, 
              &&I_xor_r, &&I_sll_r, &&I_srl_r, &&I_sra_r, &&I_add_i, 
              &&I_sub_i, &&I_and_i, &&I_or_i, &&I_xor_i, &&I_sll_i, 
              &&I_srl_i, &&I_sra_i, &&I_ld_i, &&I_st_i, &&I_sethi, 
              &&I_be, &&I_bne, &&I_ba, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_r: // Instruction add_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_add_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_sub_r: // Instruction sub_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_sub_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_and_r: // Instruction and_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_and_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_or_r: // Instruction or_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_or_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_xor_r: // Instruction xor_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_xor_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_sll_r: // Instruction sll_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_sll_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_srl_r: // Instruction srl_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_srl_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_sra_r: // Instruction sra_r
    ISA._behavior_instruction(instr_dec->F_Type_F3R.op);
    ISA._behavior_sparc_Type_F3R(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    ISA.behavior_sra_r(instr_dec->F_Type_F3R.op, instr_dec->F_Type_F3R.rd, instr_dec->F_Type_F3R.op3, instr_dec->F_Type_F3R.rs1, instr_dec->F_Type_F3R.i, instr_dec->F_Type_F3R.asi, instr_dec->F_Type_F3R.rs2);
    goto *dispatch();

  I_add_i: // Instruction add_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_add_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_sub_i: // Instruction sub_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_sub_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_and_i: // Instruction and_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_and_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_or_i: // Instruction or_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_or_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_xor_i: // Instruction xor_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_xor_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_sll_i: // Instruction sll_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_sll_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_srl_i: // Instruction srl_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_srl_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_sra_i: // Instruction sra_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_sra_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_ld_i: // Instruction ld_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_ld_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_st_i: // Instruction st_i
    ISA._behavior_instruction(instr_dec->F_Type_F3I.op);
    ISA._behavior_sparc_Type_F3I(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    ISA.behavior_st_i(instr_dec->F_Type_F3I.op, instr_dec->F_Type_F3I.rd, instr_dec->F_Type_F3I.op3, instr_dec->F_Type_F3I.rs1, instr_dec->F_Type_F3I.i, instr_dec->F_Type_F3I.simm13);
    goto *dispatch();

  I_sethi: // Instruction sethi
    ISA._behavior_instruction(instr_dec->F_Type_F2.op);
    ISA._behavior_sparc_Type_F2(instr_dec->F_Type_F2.op, instr_dec->F_Type_F2.rd, instr_dec->F_Type_F2.op2, instr_dec->F_Type_F2.imm22);
    ISA.behavior_sethi(instr_dec->F_Type_F2.op, instr_dec->F_Type_F2.rd, instr_dec->F_Type_F2.op2, instr_dec->F_Type_F2.imm22);
    goto *dispatch();

  I_be: // Instruction be
    ISA._behavior_instruction(instr_dec->F_Type_BR.op);
    ISA._behavior_sparc_Type_BR(instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.a, instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op2, instr_dec->F_Type_BR.disp22);
    ISA.behavior_be(instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.a, instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op2, instr_dec->F_Type_BR.disp22);
    goto *dispatch();

  I_bne: // Instruction bne
    ISA._behavior_instruction(instr_dec->F_Type_BR.op);
    ISA._behavior_sparc_Type_BR(instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.a, instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op2, instr_dec->F_Type_BR.disp22);
    ISA.behavior_bne(instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.a, instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op2, instr_dec->F_Type_BR.disp22);
    goto *dispatch();

  I_ba: // Instruction ba
    ISA._behavior_instruction(instr_dec->F_Type_BR.op);
    ISA._behavior_sparc_Type_BR(instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.a, instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op2, instr_dec->F_Type_BR.disp22);
    ISA.behavior_ba(instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.a, instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op2, instr_dec->F_Type_BR.disp22);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_HLT.op);
    ISA._behavior_sparc_Type_HLT(instr_dec->F_Type_HLT.op, instr_dec->F_Type_HLT.rd, instr_dec->F_Type_HLT.op3, instr_dec->F_Type_HLT.imm);
    ISA.behavior_halt(instr_dec->F_Type_HLT.op, instr_dec->F_Type_HLT.rd, instr_dec->F_Type_HLT.op3, instr_dec->F_Type_HLT.imm);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void sparc::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void sparc::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void sparc::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void sparc::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void sparc::load(char* program) {
  DM_mport.load(program);
}

void sparc::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned sparc::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void sparc::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void sparc::PrintStat() {
  ac_arch<sparc_parms::ac_word, sparc_parms::ac_Hword>::PrintStat();
}

