/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "sparc_isa.H"

//!Fields table declaration.
ac_dec_field sparc_parms::sparc_isa::fields[sparc_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 2, 1, 1, 0, 0, &(sparc_parms::sparc_isa::fields[1])},
  {"rd", 5, 6, 2, 0, 0, &(sparc_parms::sparc_isa::fields[2])},
  {"op2", 3, 9, 3, 0, 0, &(sparc_parms::sparc_isa::fields[3])},
  {"imm22", 22, 31, 4, 0, 0, NULL},
  {"op", 2, 1, 1, 0, 0, &(sparc_parms::sparc_isa::fields[5])},
  {"rd", 5, 6, 2, 0, 0, &(sparc_parms::sparc_isa::fields[6])},
  {"op3", 6, 12, 5, 0, 0, &(sparc_parms::sparc_isa::fields[7])},
  {"rs1", 5, 17, 6, 0, 0, &(sparc_parms::sparc_isa::fields[8])},
  {"i", 1, 18, 7, 0, 0, &(sparc_parms::sparc_isa::fields[9])},
  {"asi", 8, 26, 8, 0, 0, &(sparc_parms::sparc_isa::fields[10])},
  {"rs2", 5, 31, 9, 0, 0, NULL},
  {"op", 2, 1, 1, 0, 0, &(sparc_parms::sparc_isa::fields[12])},
  {"rd", 5, 6, 2, 0, 0, &(sparc_parms::sparc_isa::fields[13])},
  {"op3", 6, 12, 5, 0, 0, &(sparc_parms::sparc_isa::fields[14])},
  {"rs1", 5, 17, 6, 0, 0, &(sparc_parms::sparc_isa::fields[15])},
  {"i", 1, 18, 7, 0, 0, &(sparc_parms::sparc_isa::fields[16])},
  {"simm13", 13, 31, 10, 0, 1, NULL},
  {"op", 2, 1, 1, 0, 0, &(sparc_parms::sparc_isa::fields[18])},
  {"a", 1, 2, 11, 0, 0, &(sparc_parms::sparc_isa::fields[19])},
  {"cond", 4, 6, 12, 0, 0, &(sparc_parms::sparc_isa::fields[20])},
  {"op2", 3, 9, 3, 0, 0, &(sparc_parms::sparc_isa::fields[21])},
  {"disp22", 22, 31, 13, 0, 1, NULL},
  {"op", 2, 1, 1, 0, 0, &(sparc_parms::sparc_isa::fields[23])},
  {"rd", 5, 6, 2, 0, 0, &(sparc_parms::sparc_isa::fields[24])},
  {"op3", 6, 12, 5, 0, 0, &(sparc_parms::sparc_isa::fields[25])},
  {"imm", 24, 36, 14, 0, 0, NULL}
};

ac_dec_format sparc_parms::sparc_isa::formats[sparc_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_F2", 32, &(sparc_parms::sparc_isa::fields[0]), &(sparc_parms::sparc_isa::formats[1])},
  {2, "Type_F3R", 32, &(sparc_parms::sparc_isa::fields[4]), &(sparc_parms::sparc_isa::formats[2])},
  {3, "Type_F3I", 32, &(sparc_parms::sparc_isa::fields[11]), &(sparc_parms::sparc_isa::formats[3])},
  {4, "Type_BR", 32, &(sparc_parms::sparc_isa::fields[17]), &(sparc_parms::sparc_isa::formats[4])},
  {5, "Type_HLT", 37, &(sparc_parms::sparc_isa::fields[22]), NULL}
};

ac_dec_list sparc_parms::sparc_isa::dec_list[sparc_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[1])},
  {"op3", 5, 0, &(sparc_parms::sparc_isa::dec_list[2])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[4])},
  {"op3", 5, 4, &(sparc_parms::sparc_isa::dec_list[5])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[7])},
  {"op3", 5, 1, &(sparc_parms::sparc_isa::dec_list[8])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[10])},
  {"op3", 5, 2, &(sparc_parms::sparc_isa::dec_list[11])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[13])},
  {"op3", 5, 3, &(sparc_parms::sparc_isa::dec_list[14])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[16])},
  {"op3", 5, 37, &(sparc_parms::sparc_isa::dec_list[17])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[19])},
  {"op3", 5, 38, &(sparc_parms::sparc_isa::dec_list[20])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[22])},
  {"op3", 5, 39, &(sparc_parms::sparc_isa::dec_list[23])},
  {"i", 7, 0, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[25])},
  {"op3", 5, 0, &(sparc_parms::sparc_isa::dec_list[26])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[28])},
  {"op3", 5, 4, &(sparc_parms::sparc_isa::dec_list[29])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[31])},
  {"op3", 5, 1, &(sparc_parms::sparc_isa::dec_list[32])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[34])},
  {"op3", 5, 2, &(sparc_parms::sparc_isa::dec_list[35])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[37])},
  {"op3", 5, 3, &(sparc_parms::sparc_isa::dec_list[38])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[40])},
  {"op3", 5, 37, &(sparc_parms::sparc_isa::dec_list[41])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[43])},
  {"op3", 5, 38, &(sparc_parms::sparc_isa::dec_list[44])},
  {"i", 7, 1, NULL},
  {"op", 1, 2, &(sparc_parms::sparc_isa::dec_list[46])},
  {"op3", 5, 39, &(sparc_parms::sparc_isa::dec_list[47])},
  {"i", 7, 1, NULL},
  {"op", 1, 3, &(sparc_parms::sparc_isa::dec_list[49])},
  {"op3", 5, 0, &(sparc_parms::sparc_isa::dec_list[50])},
  {"i", 7, 1, NULL},
  {"op", 1, 3, &(sparc_parms::sparc_isa::dec_list[52])},
  {"op3", 5, 4, &(sparc_parms::sparc_isa::dec_list[53])},
  {"i", 7, 1, NULL},
  {"op", 1, 0, &(sparc_parms::sparc_isa::dec_list[55])},
  {"op2", 3, 4, NULL},
  {"op", 1, 0, &(sparc_parms::sparc_isa::dec_list[57])},
  {"op2", 3, 2, &(sparc_parms::sparc_isa::dec_list[58])},
  {"cond", 12, 1, NULL},
  {"op", 1, 0, &(sparc_parms::sparc_isa::dec_list[60])},
  {"op2", 3, 2, &(sparc_parms::sparc_isa::dec_list[61])},
  {"cond", 12, 9, NULL},
  {"op", 1, 0, &(sparc_parms::sparc_isa::dec_list[63])},
  {"op2", 3, 2, &(sparc_parms::sparc_isa::dec_list[64])},
  {"cond", 12, 8, NULL},
  {"op", 1, 3, &(sparc_parms::sparc_isa::dec_list[66])},
  {"op3", 5, 63, NULL}
};

ac_dec_instr sparc_parms::sparc_isa::instructions[sparc_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_r", 4, "add", "add %rs1, %rs2, %rd", "Type_F3R", 1, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[0]), 0, &(sparc_parms::sparc_isa::instructions[1])},
  {"sub_r", 4, "sub", "sub %rs1, %rs2, %rd", "Type_F3R", 2, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[3]), 0, &(sparc_parms::sparc_isa::instructions[2])},
  {"and_r", 4, "and", "and %rs1, %rs2, %rd", "Type_F3R", 3, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[6]), 0, &(sparc_parms::sparc_isa::instructions[3])},
  {"or_r", 4, "or", "or %rs1, %rs2, %rd", "Type_F3R", 4, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[9]), 0, &(sparc_parms::sparc_isa::instructions[4])},
  {"xor_r", 4, "xor", "xor %rs1, %rs2, %rd", "Type_F3R", 5, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[12]), 0, &(sparc_parms::sparc_isa::instructions[5])},
  {"sll_r", 4, "sll", "sll %rs1, %rs2, %rd", "Type_F3R", 6, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[15]), 0, &(sparc_parms::sparc_isa::instructions[6])},
  {"srl_r", 4, "srl", "srl %rs1, %rs2, %rd", "Type_F3R", 7, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[18]), 0, &(sparc_parms::sparc_isa::instructions[7])},
  {"sra_r", 4, "sra", "sra %rs1, %rs2, %rd", "Type_F3R", 8, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[21]), 0, &(sparc_parms::sparc_isa::instructions[8])},
  {"add_i", 4, "add", "add %rs1, %simm13, %rd", "Type_F3I", 9, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[24]), 0, &(sparc_parms::sparc_isa::instructions[9])},
  {"sub_i", 4, "sub", "sub %rs1, %simm13, %rd", "Type_F3I", 10, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[27]), 0, &(sparc_parms::sparc_isa::instructions[10])},
  {"and_i", 4, "and", "and %rs1, %simm13, %rd", "Type_F3I", 11, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[30]), 0, &(sparc_parms::sparc_isa::instructions[11])},
  {"or_i", 4, "or", "or %rs1, %simm13, %rd", "Type_F3I", 12, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[33]), 0, &(sparc_parms::sparc_isa::instructions[12])},
  {"xor_i", 4, "xor", "xor %rs1, %simm13, %rd", "Type_F3I", 13, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[36]), 0, &(sparc_parms::sparc_isa::instructions[13])},
  {"sll_i", 4, "sll", "sll %rs1, %simm13, %rd", "Type_F3I", 14, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[39]), 0, &(sparc_parms::sparc_isa::instructions[14])},
  {"srl_i", 4, "srl", "srl %rs1, %simm13, %rd", "Type_F3I", 15, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[42]), 0, &(sparc_parms::sparc_isa::instructions[15])},
  {"sra_i", 4, "sra", "sra %rs1, %simm13, %rd", "Type_F3I", 16, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[45]), 0, &(sparc_parms::sparc_isa::instructions[16])},
  {"ld_i", 4, "ld", "ld [%rs1 + %simm13], %rd", "Type_F3I", 17, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[48]), 0, &(sparc_parms::sparc_isa::instructions[17])},
  {"st_i", 4, "st", "st %rd, [%rs1 + %simm13]", "Type_F3I", 18, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[51]), 0, &(sparc_parms::sparc_isa::instructions[18])},
  {"sethi", 4, "sethi", "sethi %imm22, %rd", "Type_F2", 19, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[54]), 0, &(sparc_parms::sparc_isa::instructions[19])},
  {"be", 4, "be", "be %disp22", "Type_BR", 20, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[56]), 0, &(sparc_parms::sparc_isa::instructions[20])},
  {"bne", 4, "bne", "bne %disp22", "Type_BR", 21, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[59]), 0, &(sparc_parms::sparc_isa::instructions[21])},
  {"ba", 4, "ba", "ba %disp22", "Type_BR", 22, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[62]), 0, &(sparc_parms::sparc_isa::instructions[22])},
  {"halt", 4, "halt", "halt", "Type_HLT", 23, 1, 1, 1, &(sparc_parms::sparc_isa::dec_list[65]), 0, NULL}
};

const ac_instr_info
sparc_parms::sparc_isa::instr_table[sparc_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "add_r", "add", 4),
  ac_instr_info(2, "sub_r", "sub", 4),
  ac_instr_info(3, "and_r", "and", 4),
  ac_instr_info(4, "or_r", "or", 4),
  ac_instr_info(5, "xor_r", "xor", 4),
  ac_instr_info(6, "sll_r", "sll", 4),
  ac_instr_info(7, "srl_r", "srl", 4),
  ac_instr_info(8, "sra_r", "sra", 4),
  ac_instr_info(9, "add_i", "add", 4),
  ac_instr_info(10, "sub_i", "sub", 4),
  ac_instr_info(11, "and_i", "and", 4),
  ac_instr_info(12, "or_i", "or", 4),
  ac_instr_info(13, "xor_i", "xor", 4),
  ac_instr_info(14, "sll_i", "sll", 4),
  ac_instr_info(15, "srl_i", "srl", 4),
  ac_instr_info(16, "sra_i", "sra", 4),
  ac_instr_info(17, "ld_i", "ld", 4),
  ac_instr_info(18, "st_i", "st", 4),
  ac_instr_info(19, "sethi", "sethi", 4),
  ac_instr_info(20, "be", "be", 4),
  ac_instr_info(21, "bne", "bne", 4),
  ac_instr_info(22, "ba", "ba", 4),
  ac_instr_info(23, "halt", "halt", 4)
};

const unsigned sparc_parms::sparc_isa::instr_format_table[sparc_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  4,
  4,
  4,
  5
};
