/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "alpha.H"
#include  "alpha_isa.cpp"

#include  "alpha_syscall.H"

void* alpha::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_OpReg.op = ins_cache[1];
        instr_dec->F_Type_OpReg.ra = ins_cache[2];
        instr_dec->F_Type_OpReg.rb = ins_cache[3];
        instr_dec->F_Type_OpReg.sbz = ins_cache[4];
        instr_dec->F_Type_OpReg.func = ins_cache[5];
        instr_dec->F_Type_OpReg.rc = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_OpLit.op = ins_cache[1];
        instr_dec->F_Type_OpLit.ra = ins_cache[2];
        instr_dec->F_Type_OpLit.lit = ins_cache[7];
        instr_dec->F_Type_OpLit.flag = ins_cache[8];
        instr_dec->F_Type_OpLit.func = ins_cache[5];
        instr_dec->F_Type_OpLit.rc = ins_cache[6];
      break;
      case 3:
        instr_dec->F_Type_Memory.op = ins_cache[1];
        instr_dec->F_Type_Memory.ra = ins_cache[2];
        instr_dec->F_Type_Memory.rb = ins_cache[3];
        instr_dec->F_Type_Memory.disp = ins_cache[9];
      break;
      case 4:
        instr_dec->F_Type_Branch.op = ins_cache[1];
        instr_dec->F_Type_Branch.ra = ins_cache[2];
        instr_dec->F_Type_Branch.bdisp = ins_cache[10];
      break;
      case 5:
        instr_dec->F_Type_Halt.op = ins_cache[1];
        instr_dec->F_Type_Halt.pad = ins_cache[11];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void alpha::behavior() {

  void* vet[] = {&&I_Init, &&I_addq, &&I_subq, &&I_mulq, &&I_cmpeq, 
              &&I_cmplt, &&I_cmple, &&I_cmpult, &&I_cmpule, &&I_and_op, 
              &&I_bis_op, &&I_xor_op, &&I_bic_op, &&I_cmoveq, &&I_cmovne, 
              &&I_addq_i, &&I_subq_i, &&I_lda, &&I_ldah, &&I_ldq, 
              &&I_stq, &&I_ldl, &&I_stl, &&I_br, &&I_bne, 
              &&I_beq, &&I_blt, &&I_bge, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_addq: // Instruction addq
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_addq(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_subq: // Instruction subq
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_subq(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_mulq: // Instruction mulq
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_mulq(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmpeq: // Instruction cmpeq
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmpeq(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmplt: // Instruction cmplt
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmplt(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmple: // Instruction cmple
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmple(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmpult: // Instruction cmpult
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmpult(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmpule: // Instruction cmpule
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmpule(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_and_op: // Instruction and_op
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_and_op(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_bis_op: // Instruction bis_op
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_bis_op(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_xor_op: // Instruction xor_op
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_xor_op(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_bic_op: // Instruction bic_op
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_bic_op(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmoveq: // Instruction cmoveq
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmoveq(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_cmovne: // Instruction cmovne
    ISA._behavior_instruction(instr_dec->F_Type_OpReg.op);
    ISA._behavior_alpha_Type_OpReg(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    ISA.behavior_cmovne(instr_dec->F_Type_OpReg.op, instr_dec->F_Type_OpReg.ra, instr_dec->F_Type_OpReg.rb, instr_dec->F_Type_OpReg.sbz, instr_dec->F_Type_OpReg.func, instr_dec->F_Type_OpReg.rc);
    goto *dispatch();

  I_addq_i: // Instruction addq_i
    ISA._behavior_instruction(instr_dec->F_Type_OpLit.op);
    ISA._behavior_alpha_Type_OpLit(instr_dec->F_Type_OpLit.op, instr_dec->F_Type_OpLit.ra, instr_dec->F_Type_OpLit.lit, instr_dec->F_Type_OpLit.flag, instr_dec->F_Type_OpLit.func, instr_dec->F_Type_OpLit.rc);
    ISA.behavior_addq_i(instr_dec->F_Type_OpLit.op, instr_dec->F_Type_OpLit.ra, instr_dec->F_Type_OpLit.lit, instr_dec->F_Type_OpLit.flag, instr_dec->F_Type_OpLit.func, instr_dec->F_Type_OpLit.rc);
    goto *dispatch();

  I_subq_i: // Instruction subq_i
    ISA._behavior_instruction(instr_dec->F_Type_OpLit.op);
    ISA._behavior_alpha_Type_OpLit(instr_dec->F_Type_OpLit.op, instr_dec->F_Type_OpLit.ra, instr_dec->F_Type_OpLit.lit, instr_dec->F_Type_OpLit.flag, instr_dec->F_Type_OpLit.func, instr_dec->F_Type_OpLit.rc);
    ISA.behavior_subq_i(instr_dec->F_Type_OpLit.op, instr_dec->F_Type_OpLit.ra, instr_dec->F_Type_OpLit.lit, instr_dec->F_Type_OpLit.flag, instr_dec->F_Type_OpLit.func, instr_dec->F_Type_OpLit.rc);
    goto *dispatch();

  I_lda: // Instruction lda
    ISA._behavior_instruction(instr_dec->F_Type_Memory.op);
    ISA._behavior_alpha_Type_Memory(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    ISA.behavior_lda(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    goto *dispatch();

  I_ldah: // Instruction ldah
    ISA._behavior_instruction(instr_dec->F_Type_Memory.op);
    ISA._behavior_alpha_Type_Memory(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    ISA.behavior_ldah(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    goto *dispatch();

  I_ldq: // Instruction ldq
    ISA._behavior_instruction(instr_dec->F_Type_Memory.op);
    ISA._behavior_alpha_Type_Memory(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    ISA.behavior_ldq(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    goto *dispatch();

  I_stq: // Instruction stq
    ISA._behavior_instruction(instr_dec->F_Type_Memory.op);
    ISA._behavior_alpha_Type_Memory(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    ISA.behavior_stq(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    goto *dispatch();

  I_ldl: // Instruction ldl
    ISA._behavior_instruction(instr_dec->F_Type_Memory.op);
    ISA._behavior_alpha_Type_Memory(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    ISA.behavior_ldl(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    goto *dispatch();

  I_stl: // Instruction stl
    ISA._behavior_instruction(instr_dec->F_Type_Memory.op);
    ISA._behavior_alpha_Type_Memory(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    ISA.behavior_stl(instr_dec->F_Type_Memory.op, instr_dec->F_Type_Memory.ra, instr_dec->F_Type_Memory.rb, instr_dec->F_Type_Memory.disp);
    goto *dispatch();

  I_br: // Instruction br
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_alpha_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    ISA.behavior_br(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    goto *dispatch();

  I_bne: // Instruction bne
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_alpha_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    ISA.behavior_bne(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    goto *dispatch();

  I_beq: // Instruction beq
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_alpha_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    ISA.behavior_beq(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    goto *dispatch();

  I_blt: // Instruction blt
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_alpha_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    ISA.behavior_blt(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    goto *dispatch();

  I_bge: // Instruction bge
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_alpha_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    ISA.behavior_bge(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.ra, instr_dec->F_Type_Branch.bdisp);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_Halt.op);
    ISA._behavior_alpha_Type_Halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    ISA.behavior_halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void alpha::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void alpha::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void alpha::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void alpha::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void alpha::load(char* program) {
  DM_mport.load(program);
}

void alpha::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned alpha::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void alpha::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void alpha::PrintStat() {
  ac_arch<alpha_parms::ac_word, alpha_parms::ac_Hword>::PrintStat();
}

