/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "alpha_isa.H"

//!Fields table declaration.
ac_dec_field alpha_parms::alpha_isa::fields[alpha_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 6, 31, 1, 0, 0, &(alpha_parms::alpha_isa::fields[1])},
  {"ra", 5, 25, 2, 0, 0, &(alpha_parms::alpha_isa::fields[2])},
  {"rb", 5, 20, 3, 0, 0, &(alpha_parms::alpha_isa::fields[3])},
  {"sbz", 4, 15, 4, 0, 0, &(alpha_parms::alpha_isa::fields[4])},
  {"func", 7, 11, 5, 0, 0, &(alpha_parms::alpha_isa::fields[5])},
  {"rc", 5, 4, 6, 0, 0, NULL},
  {"op", 6, 31, 1, 0, 0, &(alpha_parms::alpha_isa::fields[7])},
  {"ra", 5, 25, 2, 0, 0, &(alpha_parms::alpha_isa::fields[8])},
  {"lit", 8, 20, 7, 0, 0, &(alpha_parms::alpha_isa::fields[9])},
  {"flag", 1, 12, 8, 0, 0, &(alpha_parms::alpha_isa::fields[10])},
  {"func", 7, 11, 5, 0, 0, &(alpha_parms::alpha_isa::fields[11])},
  {"rc", 5, 4, 6, 0, 0, NULL},
  {"op", 6, 31, 1, 0, 0, &(alpha_parms::alpha_isa::fields[13])},
  {"ra", 5, 25, 2, 0, 0, &(alpha_parms::alpha_isa::fields[14])},
  {"rb", 5, 20, 3, 0, 0, &(alpha_parms::alpha_isa::fields[15])},
  {"disp", 16, 15, 9, 0, 1, NULL},
  {"op", 6, 31, 1, 0, 0, &(alpha_parms::alpha_isa::fields[17])},
  {"ra", 5, 25, 2, 0, 0, &(alpha_parms::alpha_isa::fields[18])},
  {"bdisp", 21, 20, 10, 0, 1, NULL},
  {"op", 6, 31, 1, 0, 0, &(alpha_parms::alpha_isa::fields[20])},
  {"pad", 26, 25, 11, 0, 0, NULL}
};

ac_dec_format alpha_parms::alpha_isa::formats[alpha_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_OpReg", 32, &(alpha_parms::alpha_isa::fields[0]), &(alpha_parms::alpha_isa::formats[1])},
  {2, "Type_OpLit", 32, &(alpha_parms::alpha_isa::fields[6]), &(alpha_parms::alpha_isa::formats[2])},
  {3, "Type_Memory", 32, &(alpha_parms::alpha_isa::fields[12]), &(alpha_parms::alpha_isa::formats[3])},
  {4, "Type_Branch", 32, &(alpha_parms::alpha_isa::fields[16]), &(alpha_parms::alpha_isa::formats[4])},
  {5, "Type_Halt", 32, &(alpha_parms::alpha_isa::fields[19]), NULL}
};

ac_dec_list alpha_parms::alpha_isa::dec_list[alpha_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[1])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[2])},
  {"func", 5, 32, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[4])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[5])},
  {"func", 5, 41, NULL},
  {"op", 1, 19, &(alpha_parms::alpha_isa::dec_list[7])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[8])},
  {"func", 5, 32, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[10])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[11])},
  {"func", 5, 45, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[13])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[14])},
  {"func", 5, 77, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[16])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[17])},
  {"func", 5, 109, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[19])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[20])},
  {"func", 5, 29, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[22])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[23])},
  {"func", 5, 61, NULL},
  {"op", 1, 17, &(alpha_parms::alpha_isa::dec_list[25])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[26])},
  {"func", 5, 0, NULL},
  {"op", 1, 17, &(alpha_parms::alpha_isa::dec_list[28])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[29])},
  {"func", 5, 32, NULL},
  {"op", 1, 17, &(alpha_parms::alpha_isa::dec_list[31])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[32])},
  {"func", 5, 64, NULL},
  {"op", 1, 17, &(alpha_parms::alpha_isa::dec_list[34])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[35])},
  {"func", 5, 8, NULL},
  {"op", 1, 17, &(alpha_parms::alpha_isa::dec_list[37])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[38])},
  {"func", 5, 36, NULL},
  {"op", 1, 17, &(alpha_parms::alpha_isa::dec_list[40])},
  {"sbz", 4, 0, &(alpha_parms::alpha_isa::dec_list[41])},
  {"func", 5, 38, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[43])},
  {"flag", 8, 1, &(alpha_parms::alpha_isa::dec_list[44])},
  {"func", 5, 32, NULL},
  {"op", 1, 16, &(alpha_parms::alpha_isa::dec_list[46])},
  {"flag", 8, 1, &(alpha_parms::alpha_isa::dec_list[47])},
  {"func", 5, 41, NULL},
  {"op", 1, 8, NULL},
  {"op", 1, 9, NULL},
  {"op", 1, 41, NULL},
  {"op", 1, 45, NULL},
  {"op", 1, 40, NULL},
  {"op", 1, 44, NULL},
  {"op", 1, 48, NULL},
  {"op", 1, 61, NULL},
  {"op", 1, 57, NULL},
  {"op", 1, 62, NULL},
  {"op", 1, 63, NULL},
  {"op", 1, 0, NULL}
};

ac_dec_instr alpha_parms::alpha_isa::instructions[alpha_parms::AC_DEC_INSTR_NUMBER] = {
  {"addq", 4, "addq", "addq $ra, $rb, $rc", "Type_OpReg", 1, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[0]), 0, &(alpha_parms::alpha_isa::instructions[1])},
  {"subq", 4, "subq", "subq $ra, $rb, $rc", "Type_OpReg", 2, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[3]), 0, &(alpha_parms::alpha_isa::instructions[2])},
  {"mulq", 4, "mulq", "mulq $ra, $rb, $rc", "Type_OpReg", 3, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[6]), 0, &(alpha_parms::alpha_isa::instructions[3])},
  {"cmpeq", 4, "cmpeq", "cmpeq $ra, $rb, $rc", "Type_OpReg", 4, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[9]), 0, &(alpha_parms::alpha_isa::instructions[4])},
  {"cmplt", 4, "cmplt", "cmplt $ra, $rb, $rc", "Type_OpReg", 5, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[12]), 0, &(alpha_parms::alpha_isa::instructions[5])},
  {"cmple", 4, "cmple", "cmple $ra, $rb, $rc", "Type_OpReg", 6, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[15]), 0, &(alpha_parms::alpha_isa::instructions[6])},
  {"cmpult", 4, "cmpult", "cmpult $ra, $rb, $rc", "Type_OpReg", 7, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[18]), 0, &(alpha_parms::alpha_isa::instructions[7])},
  {"cmpule", 4, "cmpule", "cmpule $ra, $rb, $rc", "Type_OpReg", 8, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[21]), 0, &(alpha_parms::alpha_isa::instructions[8])},
  {"and_op", 4, "and", "and $ra, $rb, $rc", "Type_OpReg", 9, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[24]), 0, &(alpha_parms::alpha_isa::instructions[9])},
  {"bis_op", 4, "bis", "bis $ra, $rb, $rc", "Type_OpReg", 10, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[27]), 0, &(alpha_parms::alpha_isa::instructions[10])},
  {"xor_op", 4, "xor", "xor $ra, $rb, $rc", "Type_OpReg", 11, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[30]), 0, &(alpha_parms::alpha_isa::instructions[11])},
  {"bic_op", 4, "bic", "bic $ra, $rb, $rc", "Type_OpReg", 12, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[33]), 0, &(alpha_parms::alpha_isa::instructions[12])},
  {"cmoveq", 4, "cmoveq", "cmoveq $ra, $rb, $rc", "Type_OpReg", 13, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[36]), 0, &(alpha_parms::alpha_isa::instructions[13])},
  {"cmovne", 4, "cmovne", "cmovne $ra, $rb, $rc", "Type_OpReg", 14, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[39]), 0, &(alpha_parms::alpha_isa::instructions[14])},
  {"addq_i", 4, "addq", "addq $ra, $lit, $rc", "Type_OpLit", 15, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[42]), 0, &(alpha_parms::alpha_isa::instructions[15])},
  {"subq_i", 4, "subq", "subq $ra, $lit, $rc", "Type_OpLit", 16, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[45]), 0, &(alpha_parms::alpha_isa::instructions[16])},
  {"lda", 4, "lda", "lda $ra, $disp($rb)", "Type_Memory", 17, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[48]), 0, &(alpha_parms::alpha_isa::instructions[17])},
  {"ldah", 4, "ldah", "ldah $ra, $disp($rb)", "Type_Memory", 18, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[49]), 0, &(alpha_parms::alpha_isa::instructions[18])},
  {"ldq", 4, "ldq", "ldq $ra, $disp($rb)", "Type_Memory", 19, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[50]), 0, &(alpha_parms::alpha_isa::instructions[19])},
  {"stq", 4, "stq", "stq $ra, $disp($rb)", "Type_Memory", 20, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[51]), 0, &(alpha_parms::alpha_isa::instructions[20])},
  {"ldl", 4, "ldl", "ldl $ra, $disp($rb)", "Type_Memory", 21, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[52]), 0, &(alpha_parms::alpha_isa::instructions[21])},
  {"stl", 4, "stl", "stl $ra, $disp($rb)", "Type_Memory", 22, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[53]), 0, &(alpha_parms::alpha_isa::instructions[22])},
  {"br", 4, "br", "br $ra, $bdisp", "Type_Branch", 23, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[54]), 0, &(alpha_parms::alpha_isa::instructions[23])},
  {"bne", 4, "bne", "bne $ra, $bdisp", "Type_Branch", 24, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[55]), 0, &(alpha_parms::alpha_isa::instructions[24])},
  {"beq", 4, "beq", "beq $ra, $bdisp", "Type_Branch", 25, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[56]), 0, &(alpha_parms::alpha_isa::instructions[25])},
  {"blt", 4, "blt", "blt $ra, $bdisp", "Type_Branch", 26, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[57]), 0, &(alpha_parms::alpha_isa::instructions[26])},
  {"bge", 4, "bge", "bge $ra, $bdisp", "Type_Branch", 27, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[58]), 0, &(alpha_parms::alpha_isa::instructions[27])},
  {"halt", 4, "halt", "halt", "Type_Halt", 28, 1, 1, 1, &(alpha_parms::alpha_isa::dec_list[59]), 0, NULL}
};

const ac_instr_info
alpha_parms::alpha_isa::instr_table[alpha_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 8),
  ac_instr_info(1, "addq", "addq", 4),
  ac_instr_info(2, "subq", "subq", 4),
  ac_instr_info(3, "mulq", "mulq", 4),
  ac_instr_info(4, "cmpeq", "cmpeq", 4),
  ac_instr_info(5, "cmplt", "cmplt", 4),
  ac_instr_info(6, "cmple", "cmple", 4),
  ac_instr_info(7, "cmpult", "cmpult", 4),
  ac_instr_info(8, "cmpule", "cmpule", 4),
  ac_instr_info(9, "and_op", "and", 4),
  ac_instr_info(10, "bis_op", "bis", 4),
  ac_instr_info(11, "xor_op", "xor", 4),
  ac_instr_info(12, "bic_op", "bic", 4),
  ac_instr_info(13, "cmoveq", "cmoveq", 4),
  ac_instr_info(14, "cmovne", "cmovne", 4),
  ac_instr_info(15, "addq_i", "addq", 4),
  ac_instr_info(16, "subq_i", "subq", 4),
  ac_instr_info(17, "lda", "lda", 4),
  ac_instr_info(18, "ldah", "ldah", 4),
  ac_instr_info(19, "ldq", "ldq", 4),
  ac_instr_info(20, "stq", "stq", 4),
  ac_instr_info(21, "ldl", "ldl", 4),
  ac_instr_info(22, "stl", "stl", 4),
  ac_instr_info(23, "br", "br", 4),
  ac_instr_info(24, "bne", "bne", 4),
  ac_instr_info(25, "beq", "beq", 4),
  ac_instr_info(26, "blt", "blt", 4),
  ac_instr_info(27, "bge", "bge", 4),
  ac_instr_info(28, "halt", "halt", 4)
};

const unsigned alpha_parms::alpha_isa::instr_format_table[alpha_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  4,
  4,
  4,
  4,
  4,
  5
};
