/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "mips.H"
#include  "mips_isa.cpp"

#include  "mips_syscall.H"

void* mips::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_R.op = ins_cache[1];
        instr_dec->F_Type_R.rs = ins_cache[2];
        instr_dec->F_Type_R.rt = ins_cache[3];
        instr_dec->F_Type_R.rd = ins_cache[4];
        instr_dec->F_Type_R.shamt = ins_cache[5];
        instr_dec->F_Type_R.func = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_I.op = ins_cache[1];
        instr_dec->F_Type_I.rs = ins_cache[2];
        instr_dec->F_Type_I.rt = ins_cache[3];
        instr_dec->F_Type_I.imm = ins_cache[7];
      break;
      case 3:
        instr_dec->F_Type_J.op = ins_cache[1];
        instr_dec->F_Type_J.addr = ins_cache[8];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void mips::behavior() {

  void* vet[] = {&&I_Init, &&I_add, &&I_sub, &&I_and_op, &&I_or_op, 
              &&I_xor_op, &&I_nor_op, &&I_slt, &&I_sltu, &&I_sll, 
              &&I_srl, &&I_sra, &&I_mult, &&I_div_op, &&I_mfhi, 
              &&I_mflo, &&I_jr, &&I_nop, &&I_addi, &&I_addiu, 
              &&I_andi, &&I_ori, &&I_xori, &&I_lui, &&I_lw, 
              &&I_sw, &&I_beq, &&I_bne, &&I_blez, &&I_bgtz, 
              &&I_j, &&I_jal, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add: // Instruction add
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_add(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_sub: // Instruction sub
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sub(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_and_op: // Instruction and_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_and_op(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_or_op: // Instruction or_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_or_op(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_xor_op: // Instruction xor_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_xor_op(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_nor_op: // Instruction nor_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_nor_op(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_slt: // Instruction slt
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_slt(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_sltu: // Instruction sltu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sltu(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_sll: // Instruction sll
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sll(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_srl: // Instruction srl
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_srl(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_sra: // Instruction sra
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_sra(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_mult: // Instruction mult
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mult(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_div_op: // Instruction div_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_div_op(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_mfhi: // Instruction mfhi
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mfhi(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_mflo: // Instruction mflo
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_mflo(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_jr: // Instruction jr
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_jr(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_nop: // Instruction nop
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_mips_Type_R(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    ISA.behavior_nop(instr_dec->F_Type_R.op, instr_dec->F_Type_R.rs, instr_dec->F_Type_R.rt, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.shamt, instr_dec->F_Type_R.func);
    goto *dispatch();

  I_addi: // Instruction addi
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_addi(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_addiu: // Instruction addiu
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_addiu(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_andi: // Instruction andi
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_andi(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_ori: // Instruction ori
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_ori(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_xori: // Instruction xori
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_xori(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_lui: // Instruction lui
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lui(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_lw: // Instruction lw
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_lw(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_sw: // Instruction sw
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_sw(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_beq: // Instruction beq
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_beq(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_bne: // Instruction bne
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bne(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_blez: // Instruction blez
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_blez(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_bgtz: // Instruction bgtz
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_mips_Type_I(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    ISA.behavior_bgtz(instr_dec->F_Type_I.op, instr_dec->F_Type_I.rs, instr_dec->F_Type_I.rt, instr_dec->F_Type_I.imm);
    goto *dispatch();

  I_j: // Instruction j
    ISA._behavior_instruction(instr_dec->F_Type_J.op);
    ISA._behavior_mips_Type_J(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ISA.behavior_j(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    goto *dispatch();

  I_jal: // Instruction jal
    ISA._behavior_instruction(instr_dec->F_Type_J.op);
    ISA._behavior_mips_Type_J(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ISA.behavior_jal(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_J.op);
    ISA._behavior_mips_Type_J(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    ISA.behavior_halt(instr_dec->F_Type_J.op, instr_dec->F_Type_J.addr);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void mips::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void mips::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void mips::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void mips::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void mips::load(char* program) {
  DM_mport.load(program);
}

void mips::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned mips::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void mips::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void mips::PrintStat() {
  ac_arch<mips_parms::ac_word, mips_parms::ac_Hword>::PrintStat();
}

