/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "mips_isa.H"

//!Fields table declaration.
ac_dec_field mips_parms::mips_isa::fields[mips_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 6, 5, 1, 0, 0, &(mips_parms::mips_isa::fields[1])},
  {"rs", 5, 10, 2, 0, 0, &(mips_parms::mips_isa::fields[2])},
  {"rt", 5, 15, 3, 0, 0, &(mips_parms::mips_isa::fields[3])},
  {"rd", 5, 20, 4, 0, 0, &(mips_parms::mips_isa::fields[4])},
  {"shamt", 5, 25, 5, 0, 0, &(mips_parms::mips_isa::fields[5])},
  {"func", 6, 31, 6, 0, 0, NULL},
  {"op", 6, 5, 1, 0, 0, &(mips_parms::mips_isa::fields[7])},
  {"rs", 5, 10, 2, 0, 0, &(mips_parms::mips_isa::fields[8])},
  {"rt", 5, 15, 3, 0, 0, &(mips_parms::mips_isa::fields[9])},
  {"imm", 16, 31, 7, 0, 1, NULL},
  {"op", 6, 5, 1, 0, 0, &(mips_parms::mips_isa::fields[11])},
  {"addr", 26, 31, 8, 0, 0, NULL}
};

ac_dec_format mips_parms::mips_isa::formats[mips_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_R", 32, &(mips_parms::mips_isa::fields[0]), &(mips_parms::mips_isa::formats[1])},
  {2, "Type_I", 32, &(mips_parms::mips_isa::fields[6]), &(mips_parms::mips_isa::formats[2])},
  {3, "Type_J", 32, &(mips_parms::mips_isa::fields[10]), NULL}
};

ac_dec_list mips_parms::mips_isa::dec_list[mips_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[1])},
  {"func", 6, 32, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[3])},
  {"func", 6, 34, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[5])},
  {"func", 6, 36, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[7])},
  {"func", 6, 37, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[9])},
  {"func", 6, 38, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[11])},
  {"func", 6, 39, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[13])},
  {"func", 6, 42, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[15])},
  {"func", 6, 43, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[17])},
  {"func", 6, 0, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[19])},
  {"func", 6, 2, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[21])},
  {"func", 6, 3, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[23])},
  {"func", 6, 24, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[25])},
  {"func", 6, 26, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[27])},
  {"func", 6, 16, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[29])},
  {"func", 6, 18, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[31])},
  {"func", 6, 8, NULL},
  {"op", 1, 0, &(mips_parms::mips_isa::dec_list[33])},
  {"func", 6, 1, NULL},
  {"op", 1, 8, NULL},
  {"op", 1, 9, NULL},
  {"op", 1, 12, NULL},
  {"op", 1, 13, NULL},
  {"op", 1, 14, NULL},
  {"op", 1, 15, NULL},
  {"op", 1, 35, NULL},
  {"op", 1, 43, NULL},
  {"op", 1, 4, NULL},
  {"op", 1, 5, NULL},
  {"op", 1, 6, NULL},
  {"op", 1, 7, NULL},
  {"op", 1, 2, NULL},
  {"op", 1, 3, NULL},
  {"op", 1, 63, NULL}
};

ac_dec_instr mips_parms::mips_isa::instructions[mips_parms::AC_DEC_INSTR_NUMBER] = {
  {"add", 4, "add", "add %rd, %rs, %rt", "Type_R", 1, 1, 1, 1, &(mips_parms::mips_isa::dec_list[0]), 0, &(mips_parms::mips_isa::instructions[1])},
  {"sub", 4, "sub", "sub %rd, %rs, %rt", "Type_R", 2, 1, 1, 1, &(mips_parms::mips_isa::dec_list[2]), 0, &(mips_parms::mips_isa::instructions[2])},
  {"and_op", 4, "and", "and %rd, %rs, %rt", "Type_R", 3, 1, 1, 1, &(mips_parms::mips_isa::dec_list[4]), 0, &(mips_parms::mips_isa::instructions[3])},
  {"or_op", 4, "or", "or %rd, %rs, %rt", "Type_R", 4, 1, 1, 1, &(mips_parms::mips_isa::dec_list[6]), 0, &(mips_parms::mips_isa::instructions[4])},
  {"xor_op", 4, "xor", "xor %rd, %rs, %rt", "Type_R", 5, 1, 1, 1, &(mips_parms::mips_isa::dec_list[8]), 0, &(mips_parms::mips_isa::instructions[5])},
  {"nor_op", 4, "nor", "nor %rd, %rs, %rt", "Type_R", 6, 1, 1, 1, &(mips_parms::mips_isa::dec_list[10]), 0, &(mips_parms::mips_isa::instructions[6])},
  {"slt", 4, "slt", "slt %rd, %rs, %rt", "Type_R", 7, 1, 1, 1, &(mips_parms::mips_isa::dec_list[12]), 0, &(mips_parms::mips_isa::instructions[7])},
  {"sltu", 4, "sltu", "sltu %rd, %rs, %rt", "Type_R", 8, 1, 1, 1, &(mips_parms::mips_isa::dec_list[14]), 0, &(mips_parms::mips_isa::instructions[8])},
  {"sll", 4, "sll", "sll %rd, %rt, %shamt", "Type_R", 9, 1, 1, 1, &(mips_parms::mips_isa::dec_list[16]), 0, &(mips_parms::mips_isa::instructions[9])},
  {"srl", 4, "srl", "srl %rd, %rt, %shamt", "Type_R", 10, 1, 1, 1, &(mips_parms::mips_isa::dec_list[18]), 0, &(mips_parms::mips_isa::instructions[10])},
  {"sra", 4, "sra", "sra %rd, %rt, %shamt", "Type_R", 11, 1, 1, 1, &(mips_parms::mips_isa::dec_list[20]), 0, &(mips_parms::mips_isa::instructions[11])},
  {"mult", 4, "mult", "mult %rs, %rt", "Type_R", 12, 1, 1, 1, &(mips_parms::mips_isa::dec_list[22]), 0, &(mips_parms::mips_isa::instructions[12])},
  {"div_op", 4, "div", "div %rs, %rt", "Type_R", 13, 1, 1, 1, &(mips_parms::mips_isa::dec_list[24]), 0, &(mips_parms::mips_isa::instructions[13])},
  {"mfhi", 4, "mfhi", "mfhi %rd", "Type_R", 14, 1, 1, 1, &(mips_parms::mips_isa::dec_list[26]), 0, &(mips_parms::mips_isa::instructions[14])},
  {"mflo", 4, "mflo", "mflo %rd", "Type_R", 15, 1, 1, 1, &(mips_parms::mips_isa::dec_list[28]), 0, &(mips_parms::mips_isa::instructions[15])},
  {"jr", 4, "jr", "jr %rs", "Type_R", 16, 1, 1, 1, &(mips_parms::mips_isa::dec_list[30]), 0, &(mips_parms::mips_isa::instructions[16])},
  {"nop", 4, "nop", "nop", "Type_R", 17, 1, 1, 1, &(mips_parms::mips_isa::dec_list[32]), 0, &(mips_parms::mips_isa::instructions[17])},
  {"addi", 4, "addi", "addi %rt, %rs, %imm", "Type_I", 18, 1, 1, 1, &(mips_parms::mips_isa::dec_list[34]), 0, &(mips_parms::mips_isa::instructions[18])},
  {"addiu", 4, "addiu", "addiu %rt, %rs, %imm", "Type_I", 19, 1, 1, 1, &(mips_parms::mips_isa::dec_list[35]), 0, &(mips_parms::mips_isa::instructions[19])},
  {"andi", 4, "andi", "andi %rt, %rs, %imm", "Type_I", 20, 1, 1, 1, &(mips_parms::mips_isa::dec_list[36]), 0, &(mips_parms::mips_isa::instructions[20])},
  {"ori", 4, "ori", "ori %rt, %rs, %imm", "Type_I", 21, 1, 1, 1, &(mips_parms::mips_isa::dec_list[37]), 0, &(mips_parms::mips_isa::instructions[21])},
  {"xori", 4, "xori", "xori %rt, %rs, %imm", "Type_I", 22, 1, 1, 1, &(mips_parms::mips_isa::dec_list[38]), 0, &(mips_parms::mips_isa::instructions[22])},
  {"lui", 4, "lui", "lui %rt, %imm", "Type_I", 23, 1, 1, 1, &(mips_parms::mips_isa::dec_list[39]), 0, &(mips_parms::mips_isa::instructions[23])},
  {"lw", 4, "lw", "lw %rt, %imm(%rs)", "Type_I", 24, 1, 1, 1, &(mips_parms::mips_isa::dec_list[40]), 0, &(mips_parms::mips_isa::instructions[24])},
  {"sw", 4, "sw", "sw %rt, %imm(%rs)", "Type_I", 25, 1, 1, 1, &(mips_parms::mips_isa::dec_list[41]), 0, &(mips_parms::mips_isa::instructions[25])},
  {"beq", 4, "beq", "beq %rs, %rt, %imm", "Type_I", 26, 1, 1, 1, &(mips_parms::mips_isa::dec_list[42]), 0, &(mips_parms::mips_isa::instructions[26])},
  {"bne", 4, "bne", "bne %rs, %rt, %imm", "Type_I", 27, 1, 1, 1, &(mips_parms::mips_isa::dec_list[43]), 0, &(mips_parms::mips_isa::instructions[27])},
  {"blez", 4, "blez", "blez %rs, %imm", "Type_I", 28, 1, 1, 1, &(mips_parms::mips_isa::dec_list[44]), 0, &(mips_parms::mips_isa::instructions[28])},
  {"bgtz", 4, "bgtz", "bgtz %rs, %imm", "Type_I", 29, 1, 1, 1, &(mips_parms::mips_isa::dec_list[45]), 0, &(mips_parms::mips_isa::instructions[29])},
  {"j", 4, "j", "j %addr", "Type_J", 30, 1, 1, 1, &(mips_parms::mips_isa::dec_list[46]), 0, &(mips_parms::mips_isa::instructions[30])},
  {"jal", 4, "jal", "jal %addr", "Type_J", 31, 1, 1, 1, &(mips_parms::mips_isa::dec_list[47]), 0, &(mips_parms::mips_isa::instructions[31])},
  {"halt", 4, "halt", "halt", "Type_J", 32, 1, 1, 1, &(mips_parms::mips_isa::dec_list[48]), 0, NULL}
};

const ac_instr_info
mips_parms::mips_isa::instr_table[mips_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "add", "add", 4),
  ac_instr_info(2, "sub", "sub", 4),
  ac_instr_info(3, "and_op", "and", 4),
  ac_instr_info(4, "or_op", "or", 4),
  ac_instr_info(5, "xor_op", "xor", 4),
  ac_instr_info(6, "nor_op", "nor", 4),
  ac_instr_info(7, "slt", "slt", 4),
  ac_instr_info(8, "sltu", "sltu", 4),
  ac_instr_info(9, "sll", "sll", 4),
  ac_instr_info(10, "srl", "srl", 4),
  ac_instr_info(11, "sra", "sra", 4),
  ac_instr_info(12, "mult", "mult", 4),
  ac_instr_info(13, "div_op", "div", 4),
  ac_instr_info(14, "mfhi", "mfhi", 4),
  ac_instr_info(15, "mflo", "mflo", 4),
  ac_instr_info(16, "jr", "jr", 4),
  ac_instr_info(17, "nop", "nop", 4),
  ac_instr_info(18, "addi", "addi", 4),
  ac_instr_info(19, "addiu", "addiu", 4),
  ac_instr_info(20, "andi", "andi", 4),
  ac_instr_info(21, "ori", "ori", 4),
  ac_instr_info(22, "xori", "xori", 4),
  ac_instr_info(23, "lui", "lui", 4),
  ac_instr_info(24, "lw", "lw", 4),
  ac_instr_info(25, "sw", "sw", 4),
  ac_instr_info(26, "beq", "beq", 4),
  ac_instr_info(27, "bne", "bne", 4),
  ac_instr_info(28, "blez", "blez", 4),
  ac_instr_info(29, "bgtz", "bgtz", 4),
  ac_instr_info(30, "j", "j", 4),
  ac_instr_info(31, "jal", "jal", 4),
  ac_instr_info(32, "halt", "halt", 4)
};

const unsigned mips_parms::mips_isa::instr_format_table[mips_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3
};
