/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "stm32_arch.H"
#include  "stm32_arch_ref.H"

//!/Default constructor.
stm32_arch_ref::stm32_arch_ref(stm32_arch& arch) : ac_arch_ref<stm32_parms::ac_word, stm32_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   FLASH(arch.FLASH_mport),   SRAM(arch.SRAM_mport),   PERIPH(arch.PERIPH_mport),   R(arch.R),   xpsr(arch.xpsr),   primask(arch.primask),   control(arch.control) {}

