/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "nrf52_arch.H"
#include  "nrf52_arch_ref.H"

//!/Default constructor.
nrf52_arch_ref::nrf52_arch_ref(nrf52_arch& arch) : ac_arch_ref<nrf52_parms::ac_word, nrf52_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   FLASH(arch.FLASH_mport),   SRAM(arch.SRAM_mport),   RADIO_PERIPH(arch.RADIO_PERIPH_mport),   R(arch.R),   xpsr(arch.xpsr),   primask(arch.primask),   control(arch.control),   event_reg(arch.event_reg) {}

