/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "nrf52_isa.H"

//!Fields table declaration.
ac_dec_field nrf52_parms::nrf52_isa::fields[nrf52_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 4, 15, 1, 0, 0, &(nrf52_parms::nrf52_isa::fields[1])},
  {"subop1", 1, 11, 2, 0, 0, &(nrf52_parms::nrf52_isa::fields[2])},
  {"rd1", 3, 10, 3, 0, 0, &(nrf52_parms::nrf52_isa::fields[3])},
  {"imm1", 8, 7, 4, 0, 0, NULL},
  {"op", 4, 15, 1, 0, 0, &(nrf52_parms::nrf52_isa::fields[5])},
  {"subop2", 3, 11, 5, 0, 0, &(nrf52_parms::nrf52_isa::fields[6])},
  {"rm2", 3, 8, 6, 0, 0, &(nrf52_parms::nrf52_isa::fields[7])},
  {"rn2", 3, 5, 7, 0, 0, &(nrf52_parms::nrf52_isa::fields[8])},
  {"rd2", 3, 2, 8, 0, 0, NULL},
  {"op", 4, 15, 1, 0, 0, &(nrf52_parms::nrf52_isa::fields[10])},
  {"subop3", 6, 11, 9, 0, 0, &(nrf52_parms::nrf52_isa::fields[11])},
  {"rm3", 3, 5, 7, 0, 0, &(nrf52_parms::nrf52_isa::fields[12])},
  {"rdn3", 3, 2, 8, 0, 0, NULL},
  {"op", 4, 15, 1, 0, 0, &(nrf52_parms::nrf52_isa::fields[14])},
  {"subop4", 1, 11, 2, 0, 0, &(nrf52_parms::nrf52_isa::fields[15])},
  {"imm4", 5, 10, 10, 0, 0, &(nrf52_parms::nrf52_isa::fields[16])},
  {"rn4", 3, 5, 7, 0, 0, &(nrf52_parms::nrf52_isa::fields[17])},
  {"rt4", 3, 2, 8, 0, 0, NULL},
  {"op", 4, 15, 1, 0, 0, &(nrf52_parms::nrf52_isa::fields[19])},
  {"cond5", 4, 11, 11, 0, 0, &(nrf52_parms::nrf52_isa::fields[20])},
  {"bdisp5", 8, 7, 12, 0, 1, NULL},
  {"op", 4, 14, 13, 0, 0, &(nrf52_parms::nrf52_isa::fields[22])},
  {"bdisp6", 11, 10, 14, 0, 1, NULL},
  {"op", 4, 15, 1, 0, 0, &(nrf52_parms::nrf52_isa::fields[24])},
  {"subop7", 4, 11, 11, 0, 0, &(nrf52_parms::nrf52_isa::fields[25])},
  {"imm7", 8, 7, 4, 0, 0, NULL}
};

ac_dec_format nrf52_parms::nrf52_isa::formats[nrf52_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_Imm8", 16, &(nrf52_parms::nrf52_isa::fields[0]), &(nrf52_parms::nrf52_isa::formats[1])},
  {2, "Type_Alu3", 16, &(nrf52_parms::nrf52_isa::fields[4]), &(nrf52_parms::nrf52_isa::formats[2])},
  {3, "Type_Alu2", 16, &(nrf52_parms::nrf52_isa::fields[9]), &(nrf52_parms::nrf52_isa::formats[3])},
  {4, "Type_Mem", 16, &(nrf52_parms::nrf52_isa::fields[13]), &(nrf52_parms::nrf52_isa::formats[4])},
  {5, "Type_BCond", 16, &(nrf52_parms::nrf52_isa::fields[18]), &(nrf52_parms::nrf52_isa::formats[5])},
  {6, "Type_BUnc", 15, &(nrf52_parms::nrf52_isa::fields[21]), &(nrf52_parms::nrf52_isa::formats[6])},
  {7, "Type_Special", 16, &(nrf52_parms::nrf52_isa::fields[23]), NULL}
};

ac_dec_list nrf52_parms::nrf52_isa::dec_list[nrf52_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 2, &(nrf52_parms::nrf52_isa::dec_list[1])},
  {"subop1", 2, 0, NULL},
  {"op", 1, 2, &(nrf52_parms::nrf52_isa::dec_list[3])},
  {"subop1", 2, 1, NULL},
  {"op", 1, 3, &(nrf52_parms::nrf52_isa::dec_list[5])},
  {"subop1", 2, 0, NULL},
  {"op", 1, 3, &(nrf52_parms::nrf52_isa::dec_list[7])},
  {"subop1", 2, 1, NULL},
  {"op", 1, 1, &(nrf52_parms::nrf52_isa::dec_list[9])},
  {"subop2", 5, 6, NULL},
  {"op", 1, 1, &(nrf52_parms::nrf52_isa::dec_list[11])},
  {"subop2", 5, 7, NULL},
  {"op", 1, 4, &(nrf52_parms::nrf52_isa::dec_list[13])},
  {"subop3", 9, 0, NULL},
  {"op", 1, 4, &(nrf52_parms::nrf52_isa::dec_list[15])},
  {"subop3", 9, 1, NULL},
  {"op", 1, 4, &(nrf52_parms::nrf52_isa::dec_list[17])},
  {"subop3", 9, 12, NULL},
  {"op", 1, 4, &(nrf52_parms::nrf52_isa::dec_list[19])},
  {"subop3", 9, 13, NULL},
  {"op", 1, 6, &(nrf52_parms::nrf52_isa::dec_list[21])},
  {"subop4", 2, 1, NULL},
  {"op", 1, 6, &(nrf52_parms::nrf52_isa::dec_list[23])},
  {"subop4", 2, 0, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[25])},
  {"cond5", 11, 0, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[27])},
  {"cond5", 11, 1, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[29])},
  {"cond5", 11, 2, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[31])},
  {"cond5", 11, 3, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[33])},
  {"cond5", 11, 4, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[35])},
  {"cond5", 11, 5, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[37])},
  {"cond5", 11, 10, NULL},
  {"op", 1, 13, &(nrf52_parms::nrf52_isa::dec_list[39])},
  {"cond5", 11, 11, NULL},
  {"op", 13, 14, NULL},
  {"op", 1, 11, &(nrf52_parms::nrf52_isa::dec_list[42])},
  {"subop7", 11, 2, NULL},
  {"op", 1, 11, &(nrf52_parms::nrf52_isa::dec_list[44])},
  {"subop7", 11, 4, NULL},
  {"op", 1, 11, &(nrf52_parms::nrf52_isa::dec_list[46])},
  {"subop7", 11, 3, NULL},
  {"op", 1, 11, &(nrf52_parms::nrf52_isa::dec_list[48])},
  {"subop7", 11, 0, NULL}
};

ac_dec_instr nrf52_parms::nrf52_isa::instructions[nrf52_parms::AC_DEC_INSTR_NUMBER] = {
  {"movs_imm", 2, "movs", "movs r%rd1, #%imm1", "Type_Imm8", 1, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[0]), 0, &(nrf52_parms::nrf52_isa::instructions[1])},
  {"cmp_imm", 2, "cmp", "cmp r%rd1, #%imm1", "Type_Imm8", 2, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[2]), 0, &(nrf52_parms::nrf52_isa::instructions[2])},
  {"adds_imm", 2, "adds", "adds r%rd1, #%imm1", "Type_Imm8", 3, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[4]), 0, &(nrf52_parms::nrf52_isa::instructions[3])},
  {"subs_imm", 2, "subs", "subs r%rd1, #%imm1", "Type_Imm8", 4, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[6]), 0, &(nrf52_parms::nrf52_isa::instructions[4])},
  {"adds_reg", 2, "adds", "adds r%rd2, r%rn2, r%rm2", "Type_Alu3", 5, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[8]), 0, &(nrf52_parms::nrf52_isa::instructions[5])},
  {"subs_reg", 2, "subs", "subs r%rd2, r%rn2, r%rm2", "Type_Alu3", 6, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[10]), 0, &(nrf52_parms::nrf52_isa::instructions[6])},
  {"ands_reg", 2, "ands", "ands r%rdn3, r%rm3", "Type_Alu2", 7, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[12]), 0, &(nrf52_parms::nrf52_isa::instructions[7])},
  {"eors_reg", 2, "eors", "eors r%rdn3, r%rm3", "Type_Alu2", 8, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[14]), 0, &(nrf52_parms::nrf52_isa::instructions[8])},
  {"orrs_reg", 2, "orrs", "orrs r%rdn3, r%rm3", "Type_Alu2", 9, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[16]), 0, &(nrf52_parms::nrf52_isa::instructions[9])},
  {"muls_reg", 2, "muls", "muls r%rdn3, r%rm3", "Type_Alu2", 10, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[18]), 0, &(nrf52_parms::nrf52_isa::instructions[10])},
  {"ldr_imm", 2, "ldr", "ldr r%rt4, [r%rn4, #%imm4]", "Type_Mem", 11, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[20]), 0, &(nrf52_parms::nrf52_isa::instructions[11])},
  {"str_imm", 2, "str", "str r%rt4, [r%rn4, #%imm4]", "Type_Mem", 12, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[22]), 0, &(nrf52_parms::nrf52_isa::instructions[12])},
  {"beq", 2, "beq", "beq %bdisp5", "Type_BCond", 13, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[24]), 0, &(nrf52_parms::nrf52_isa::instructions[13])},
  {"bne", 2, "bne", "bne %bdisp5", "Type_BCond", 14, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[26]), 0, &(nrf52_parms::nrf52_isa::instructions[14])},
  {"bcs", 2, "bcs", "bcs %bdisp5", "Type_BCond", 15, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[28]), 0, &(nrf52_parms::nrf52_isa::instructions[15])},
  {"bcc", 2, "bcc", "bcc %bdisp5", "Type_BCond", 16, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[30]), 0, &(nrf52_parms::nrf52_isa::instructions[16])},
  {"bmi", 2, "bmi", "bmi %bdisp5", "Type_BCond", 17, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[32]), 0, &(nrf52_parms::nrf52_isa::instructions[17])},
  {"bpl", 2, "bpl", "bpl %bdisp5", "Type_BCond", 18, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[34]), 0, &(nrf52_parms::nrf52_isa::instructions[18])},
  {"bge", 2, "bge", "bge %bdisp5", "Type_BCond", 19, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[36]), 0, &(nrf52_parms::nrf52_isa::instructions[19])},
  {"blt", 2, "blt", "blt %bdisp5", "Type_BCond", 20, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[38]), 0, &(nrf52_parms::nrf52_isa::instructions[20])},
  {"b_unc", 1, "b", "b %bdisp6", "Type_BUnc", 21, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[40]), 0, &(nrf52_parms::nrf52_isa::instructions[21])},
  {"wfe", 2, "wfe", "wfe", "Type_Special", 22, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[41]), 0, &(nrf52_parms::nrf52_isa::instructions[22])},
  {"sev", 2, "sev", "sev", "Type_Special", 23, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[43]), 0, &(nrf52_parms::nrf52_isa::instructions[23])},
  {"wfi", 2, "wfi", "wfi", "Type_Special", 24, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[45]), 0, &(nrf52_parms::nrf52_isa::instructions[24])},
  {"bkpt_halt", 2, "bkpt", "bkpt", "Type_Special", 25, 1, 1, 1, &(nrf52_parms::nrf52_isa::dec_list[47]), 0, NULL}
};

const ac_instr_info
nrf52_parms::nrf52_isa::instr_table[nrf52_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "movs_imm", "movs", 2),
  ac_instr_info(2, "cmp_imm", "cmp", 2),
  ac_instr_info(3, "adds_imm", "adds", 2),
  ac_instr_info(4, "subs_imm", "subs", 2),
  ac_instr_info(5, "adds_reg", "adds", 2),
  ac_instr_info(6, "subs_reg", "subs", 2),
  ac_instr_info(7, "ands_reg", "ands", 2),
  ac_instr_info(8, "eors_reg", "eors", 2),
  ac_instr_info(9, "orrs_reg", "orrs", 2),
  ac_instr_info(10, "muls_reg", "muls", 2),
  ac_instr_info(11, "ldr_imm", "ldr", 2),
  ac_instr_info(12, "str_imm", "str", 2),
  ac_instr_info(13, "beq", "beq", 2),
  ac_instr_info(14, "bne", "bne", 2),
  ac_instr_info(15, "bcs", "bcs", 2),
  ac_instr_info(16, "bcc", "bcc", 2),
  ac_instr_info(17, "bmi", "bmi", 2),
  ac_instr_info(18, "bpl", "bpl", 2),
  ac_instr_info(19, "bge", "bge", 2),
  ac_instr_info(20, "blt", "blt", 2),
  ac_instr_info(21, "b_unc", "b", 1),
  ac_instr_info(22, "wfe", "wfe", 2),
  ac_instr_info(23, "sev", "sev", 2),
  ac_instr_info(24, "wfi", "wfi", 2),
  ac_instr_info(25, "bkpt_halt", "bkpt", 2)
};

const unsigned nrf52_parms::nrf52_isa::instr_format_table[nrf52_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  2,
  2,
  3,
  3,
  3,
  3,
  4,
  4,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  6,
  7,
  7,
  7,
  7
};
