/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "nrf52_arch.H"


nrf52_arch::nrf52_arch() :
  ac_arch_dec_if<nrf52_parms::ac_word, nrf52_parms::ac_Hword>(nrf52_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  FLASH("FLASH", 1048576U),
  FLASH_mport(*this, FLASH),
  SRAM("SRAM", 262144U),
  SRAM_mport(*this, SRAM),
  RADIO_PERIPH("RADIO_PERIPH", 536870912U),
  RADIO_PERIPH_mport(*this, RADIO_PERIPH),
  R("R"),
  xpsr("xpsr", 0),
  primask("primask", 0),
  control("control", 0),
  event_reg("event_reg", 0) {

  ac_mt_endian = nrf52_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = nrf52_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int nrf52_arch::globalId = 0;