/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "nrf52.H"
#include  "nrf52_isa.cpp"

#include  "nrf52_syscall.H"

void* nrf52::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_Imm8.op = ins_cache[1];
        instr_dec->F_Type_Imm8.subop1 = ins_cache[2];
        instr_dec->F_Type_Imm8.rd1 = ins_cache[3];
        instr_dec->F_Type_Imm8.imm1 = ins_cache[4];
      break;
      case 2:
        instr_dec->F_Type_Alu3.op = ins_cache[1];
        instr_dec->F_Type_Alu3.subop2 = ins_cache[5];
        instr_dec->F_Type_Alu3.rm2 = ins_cache[6];
        instr_dec->F_Type_Alu3.rn2 = ins_cache[7];
        instr_dec->F_Type_Alu3.rd2 = ins_cache[8];
      break;
      case 3:
        instr_dec->F_Type_Alu2.op = ins_cache[1];
        instr_dec->F_Type_Alu2.subop3 = ins_cache[9];
        instr_dec->F_Type_Alu2.rm3 = ins_cache[7];
        instr_dec->F_Type_Alu2.rdn3 = ins_cache[8];
      break;
      case 4:
        instr_dec->F_Type_Mem.op = ins_cache[1];
        instr_dec->F_Type_Mem.subop4 = ins_cache[2];
        instr_dec->F_Type_Mem.imm4 = ins_cache[10];
        instr_dec->F_Type_Mem.rn4 = ins_cache[7];
        instr_dec->F_Type_Mem.rt4 = ins_cache[8];
      break;
      case 5:
        instr_dec->F_Type_BCond.op = ins_cache[1];
        instr_dec->F_Type_BCond.cond5 = ins_cache[11];
        instr_dec->F_Type_BCond.bdisp5 = ins_cache[12];
      break;
      case 6:
        instr_dec->F_Type_BUnc.op = ins_cache[13];
        instr_dec->F_Type_BUnc.bdisp6 = ins_cache[14];
      break;
      case 7:
        instr_dec->F_Type_Special.op = ins_cache[1];
        instr_dec->F_Type_Special.subop7 = ins_cache[11];
        instr_dec->F_Type_Special.imm7 = ins_cache[4];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void nrf52::behavior() {

  void* vet[] = {&&I_Init, &&I_movs_imm, &&I_cmp_imm, &&I_adds_imm, &&I_subs_imm, 
              &&I_adds_reg, &&I_subs_reg, &&I_ands_reg, &&I_eors_reg, &&I_orrs_reg, 
              &&I_muls_reg, &&I_ldr_imm, &&I_str_imm, &&I_beq, &&I_bne, 
              &&I_bcs, &&I_bcc, &&I_bmi, &&I_bpl, &&I_bge, 
              &&I_blt, &&I_b_unc, &&I_wfe, &&I_sev, &&I_wfi, 
              &&I_bkpt_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_movs_imm: // Instruction movs_imm
    ISA._behavior_instruction(instr_dec->F_Type_Imm8.op);
    ISA._behavior_nrf52_Type_Imm8(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    ISA.behavior_movs_imm(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    goto *dispatch();

  I_cmp_imm: // Instruction cmp_imm
    ISA._behavior_instruction(instr_dec->F_Type_Imm8.op);
    ISA._behavior_nrf52_Type_Imm8(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    ISA.behavior_cmp_imm(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    goto *dispatch();

  I_adds_imm: // Instruction adds_imm
    ISA._behavior_instruction(instr_dec->F_Type_Imm8.op);
    ISA._behavior_nrf52_Type_Imm8(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    ISA.behavior_adds_imm(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    goto *dispatch();

  I_subs_imm: // Instruction subs_imm
    ISA._behavior_instruction(instr_dec->F_Type_Imm8.op);
    ISA._behavior_nrf52_Type_Imm8(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    ISA.behavior_subs_imm(instr_dec->F_Type_Imm8.op, instr_dec->F_Type_Imm8.subop1, instr_dec->F_Type_Imm8.rd1, instr_dec->F_Type_Imm8.imm1);
    goto *dispatch();

  I_adds_reg: // Instruction adds_reg
    ISA._behavior_instruction(instr_dec->F_Type_Alu3.op);
    ISA._behavior_nrf52_Type_Alu3(instr_dec->F_Type_Alu3.op, instr_dec->F_Type_Alu3.subop2, instr_dec->F_Type_Alu3.rm2, instr_dec->F_Type_Alu3.rn2, instr_dec->F_Type_Alu3.rd2);
    ISA.behavior_adds_reg(instr_dec->F_Type_Alu3.op, instr_dec->F_Type_Alu3.subop2, instr_dec->F_Type_Alu3.rm2, instr_dec->F_Type_Alu3.rn2, instr_dec->F_Type_Alu3.rd2);
    goto *dispatch();

  I_subs_reg: // Instruction subs_reg
    ISA._behavior_instruction(instr_dec->F_Type_Alu3.op);
    ISA._behavior_nrf52_Type_Alu3(instr_dec->F_Type_Alu3.op, instr_dec->F_Type_Alu3.subop2, instr_dec->F_Type_Alu3.rm2, instr_dec->F_Type_Alu3.rn2, instr_dec->F_Type_Alu3.rd2);
    ISA.behavior_subs_reg(instr_dec->F_Type_Alu3.op, instr_dec->F_Type_Alu3.subop2, instr_dec->F_Type_Alu3.rm2, instr_dec->F_Type_Alu3.rn2, instr_dec->F_Type_Alu3.rd2);
    goto *dispatch();

  I_ands_reg: // Instruction ands_reg
    ISA._behavior_instruction(instr_dec->F_Type_Alu2.op);
    ISA._behavior_nrf52_Type_Alu2(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    ISA.behavior_ands_reg(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    goto *dispatch();

  I_eors_reg: // Instruction eors_reg
    ISA._behavior_instruction(instr_dec->F_Type_Alu2.op);
    ISA._behavior_nrf52_Type_Alu2(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    ISA.behavior_eors_reg(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    goto *dispatch();

  I_orrs_reg: // Instruction orrs_reg
    ISA._behavior_instruction(instr_dec->F_Type_Alu2.op);
    ISA._behavior_nrf52_Type_Alu2(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    ISA.behavior_orrs_reg(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    goto *dispatch();

  I_muls_reg: // Instruction muls_reg
    ISA._behavior_instruction(instr_dec->F_Type_Alu2.op);
    ISA._behavior_nrf52_Type_Alu2(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    ISA.behavior_muls_reg(instr_dec->F_Type_Alu2.op, instr_dec->F_Type_Alu2.subop3, instr_dec->F_Type_Alu2.rm3, instr_dec->F_Type_Alu2.rdn3);
    goto *dispatch();

  I_ldr_imm: // Instruction ldr_imm
    ISA._behavior_instruction(instr_dec->F_Type_Mem.op);
    ISA._behavior_nrf52_Type_Mem(instr_dec->F_Type_Mem.op, instr_dec->F_Type_Mem.subop4, instr_dec->F_Type_Mem.imm4, instr_dec->F_Type_Mem.rn4, instr_dec->F_Type_Mem.rt4);
    ISA.behavior_ldr_imm(instr_dec->F_Type_Mem.op, instr_dec->F_Type_Mem.subop4, instr_dec->F_Type_Mem.imm4, instr_dec->F_Type_Mem.rn4, instr_dec->F_Type_Mem.rt4);
    goto *dispatch();

  I_str_imm: // Instruction str_imm
    ISA._behavior_instruction(instr_dec->F_Type_Mem.op);
    ISA._behavior_nrf52_Type_Mem(instr_dec->F_Type_Mem.op, instr_dec->F_Type_Mem.subop4, instr_dec->F_Type_Mem.imm4, instr_dec->F_Type_Mem.rn4, instr_dec->F_Type_Mem.rt4);
    ISA.behavior_str_imm(instr_dec->F_Type_Mem.op, instr_dec->F_Type_Mem.subop4, instr_dec->F_Type_Mem.imm4, instr_dec->F_Type_Mem.rn4, instr_dec->F_Type_Mem.rt4);
    goto *dispatch();

  I_beq: // Instruction beq
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_beq(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_bne: // Instruction bne
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_bne(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_bcs: // Instruction bcs
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_bcs(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_bcc: // Instruction bcc
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_bcc(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_bmi: // Instruction bmi
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_bmi(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_bpl: // Instruction bpl
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_bpl(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_bge: // Instruction bge
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_bge(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_blt: // Instruction blt
    ISA._behavior_instruction(instr_dec->F_Type_BCond.op);
    ISA._behavior_nrf52_Type_BCond(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    ISA.behavior_blt(instr_dec->F_Type_BCond.op, instr_dec->F_Type_BCond.cond5, instr_dec->F_Type_BCond.bdisp5);
    goto *dispatch();

  I_b_unc: // Instruction b_unc
    ISA._behavior_instruction(instr_dec->F_Type_BUnc.op);
    ISA._behavior_nrf52_Type_BUnc(instr_dec->F_Type_BUnc.op, instr_dec->F_Type_BUnc.bdisp6);
    ISA.behavior_b_unc(instr_dec->F_Type_BUnc.op, instr_dec->F_Type_BUnc.bdisp6);
    goto *dispatch();

  I_wfe: // Instruction wfe
    ISA._behavior_instruction(instr_dec->F_Type_Special.op);
    ISA._behavior_nrf52_Type_Special(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    ISA.behavior_wfe(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    goto *dispatch();

  I_sev: // Instruction sev
    ISA._behavior_instruction(instr_dec->F_Type_Special.op);
    ISA._behavior_nrf52_Type_Special(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    ISA.behavior_sev(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    goto *dispatch();

  I_wfi: // Instruction wfi
    ISA._behavior_instruction(instr_dec->F_Type_Special.op);
    ISA._behavior_nrf52_Type_Special(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    ISA.behavior_wfi(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    goto *dispatch();

  I_bkpt_halt: // Instruction bkpt_halt
    ISA._behavior_instruction(instr_dec->F_Type_Special.op);
    ISA._behavior_nrf52_Type_Special(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    ISA.behavior_bkpt_halt(instr_dec->F_Type_Special.op, instr_dec->F_Type_Special.subop7, instr_dec->F_Type_Special.imm7);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void nrf52::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void nrf52::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void nrf52::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void nrf52::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void nrf52::load(char* program) {
  DM_mport.load(program);
}

void nrf52::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned nrf52::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void nrf52::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void nrf52::PrintStat() {
  ac_arch<nrf52_parms::ac_word, nrf52_parms::ac_Hword>::PrintStat();
}

