/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "avr.H"
#include  "avr_isa.cpp"

#include  "avr_syscall.H"

void* avr::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 2));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_2R.op = ins_cache[1];
        instr_dec->F_Type_2R.rd = ins_cache[2];
        instr_dec->F_Type_2R.rr = ins_cache[3];
      break;
      case 2:
        instr_dec->F_Type_1R.op = ins_cache[4];
        instr_dec->F_Type_1R.rd = ins_cache[5];
        instr_dec->F_Type_1R.func = ins_cache[6];
      break;
      case 3:
        instr_dec->F_Type_Imm.op = ins_cache[7];
        instr_dec->F_Type_Imm.k_hi = ins_cache[8];
        instr_dec->F_Type_Imm.rd_hi = ins_cache[9];
        instr_dec->F_Type_Imm.k_lo = ins_cache[6];
      break;
      case 4:
        instr_dec->F_Type_Branch.op = ins_cache[1];
        instr_dec->F_Type_Branch.k_br = ins_cache[10];
        instr_dec->F_Type_Branch.cond = ins_cache[11];
      break;
      case 5:
        instr_dec->F_Type_RJMP.op = ins_cache[7];
        instr_dec->F_Type_RJMP.k_jmp = ins_cache[12];
      break;
      case 6:
        instr_dec->F_Type_Ptr.op = ins_cache[1];
        instr_dec->F_Type_Ptr.rd = ins_cache[2];
        instr_dec->F_Type_Ptr.ptr = ins_cache[3];
      break;
      case 7:
        instr_dec->F_Type_Halt.op = ins_cache[13];
        instr_dec->F_Type_Halt.pad = ins_cache[14];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void avr::behavior() {

  void* vet[] = {&&I_Init, &&I_add_r, &&I_adc_r, &&I_sub_r, &&I_sbc_r, 
              &&I_and_r, &&I_or_r, &&I_eor_r, &&I_cp_r, &&I_mov_r, 
              &&I_inc_r, &&I_dec_r, &&I_clr_r, &&I_ldi_i, &&I_subi_i, 
              &&I_andi_i, &&I_ori_i, &&I_cpi_i, &&I_brne, &&I_breq, 
              &&I_brcs, &&I_brcc, &&I_rjmp, &&I_ld_x, &&I_st_x, 
              &&I_ld_z, &&I_st_z, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 2)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_r: // Instruction add_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_add_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_adc_r: // Instruction adc_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_adc_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_sub_r: // Instruction sub_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_sub_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_sbc_r: // Instruction sbc_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_sbc_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_and_r: // Instruction and_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_and_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_or_r: // Instruction or_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_or_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_eor_r: // Instruction eor_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_eor_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_cp_r: // Instruction cp_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_cp_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_mov_r: // Instruction mov_r
    ISA._behavior_instruction(instr_dec->F_Type_2R.op);
    ISA._behavior_avr_Type_2R(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    ISA.behavior_mov_r(instr_dec->F_Type_2R.op, instr_dec->F_Type_2R.rd, instr_dec->F_Type_2R.rr);
    goto *dispatch();

  I_inc_r: // Instruction inc_r
    ISA._behavior_instruction(instr_dec->F_Type_1R.op);
    ISA._behavior_avr_Type_1R(instr_dec->F_Type_1R.op, instr_dec->F_Type_1R.rd, instr_dec->F_Type_1R.func);
    ISA.behavior_inc_r(instr_dec->F_Type_1R.op, instr_dec->F_Type_1R.rd, instr_dec->F_Type_1R.func);
    goto *dispatch();

  I_dec_r: // Instruction dec_r
    ISA._behavior_instruction(instr_dec->F_Type_1R.op);
    ISA._behavior_avr_Type_1R(instr_dec->F_Type_1R.op, instr_dec->F_Type_1R.rd, instr_dec->F_Type_1R.func);
    ISA.behavior_dec_r(instr_dec->F_Type_1R.op, instr_dec->F_Type_1R.rd, instr_dec->F_Type_1R.func);
    goto *dispatch();

  I_clr_r: // Instruction clr_r
    ISA._behavior_instruction(instr_dec->F_Type_1R.op);
    ISA._behavior_avr_Type_1R(instr_dec->F_Type_1R.op, instr_dec->F_Type_1R.rd, instr_dec->F_Type_1R.func);
    ISA.behavior_clr_r(instr_dec->F_Type_1R.op, instr_dec->F_Type_1R.rd, instr_dec->F_Type_1R.func);
    goto *dispatch();

  I_ldi_i: // Instruction ldi_i
    ISA._behavior_instruction(instr_dec->F_Type_Imm.op);
    ISA._behavior_avr_Type_Imm(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    ISA.behavior_ldi_i(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    goto *dispatch();

  I_subi_i: // Instruction subi_i
    ISA._behavior_instruction(instr_dec->F_Type_Imm.op);
    ISA._behavior_avr_Type_Imm(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    ISA.behavior_subi_i(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    goto *dispatch();

  I_andi_i: // Instruction andi_i
    ISA._behavior_instruction(instr_dec->F_Type_Imm.op);
    ISA._behavior_avr_Type_Imm(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    ISA.behavior_andi_i(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    goto *dispatch();

  I_ori_i: // Instruction ori_i
    ISA._behavior_instruction(instr_dec->F_Type_Imm.op);
    ISA._behavior_avr_Type_Imm(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    ISA.behavior_ori_i(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    goto *dispatch();

  I_cpi_i: // Instruction cpi_i
    ISA._behavior_instruction(instr_dec->F_Type_Imm.op);
    ISA._behavior_avr_Type_Imm(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    ISA.behavior_cpi_i(instr_dec->F_Type_Imm.op, instr_dec->F_Type_Imm.k_hi, instr_dec->F_Type_Imm.rd_hi, instr_dec->F_Type_Imm.k_lo);
    goto *dispatch();

  I_brne: // Instruction brne
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_avr_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    ISA.behavior_brne(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    goto *dispatch();

  I_breq: // Instruction breq
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_avr_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    ISA.behavior_breq(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    goto *dispatch();

  I_brcs: // Instruction brcs
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_avr_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    ISA.behavior_brcs(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    goto *dispatch();

  I_brcc: // Instruction brcc
    ISA._behavior_instruction(instr_dec->F_Type_Branch.op);
    ISA._behavior_avr_Type_Branch(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    ISA.behavior_brcc(instr_dec->F_Type_Branch.op, instr_dec->F_Type_Branch.k_br, instr_dec->F_Type_Branch.cond);
    goto *dispatch();

  I_rjmp: // Instruction rjmp
    ISA._behavior_instruction(instr_dec->F_Type_RJMP.op);
    ISA._behavior_avr_Type_RJMP(instr_dec->F_Type_RJMP.op, instr_dec->F_Type_RJMP.k_jmp);
    ISA.behavior_rjmp(instr_dec->F_Type_RJMP.op, instr_dec->F_Type_RJMP.k_jmp);
    goto *dispatch();

  I_ld_x: // Instruction ld_x
    ISA._behavior_instruction(instr_dec->F_Type_Ptr.op);
    ISA._behavior_avr_Type_Ptr(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    ISA.behavior_ld_x(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    goto *dispatch();

  I_st_x: // Instruction st_x
    ISA._behavior_instruction(instr_dec->F_Type_Ptr.op);
    ISA._behavior_avr_Type_Ptr(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    ISA.behavior_st_x(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    goto *dispatch();

  I_ld_z: // Instruction ld_z
    ISA._behavior_instruction(instr_dec->F_Type_Ptr.op);
    ISA._behavior_avr_Type_Ptr(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    ISA.behavior_ld_z(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    goto *dispatch();

  I_st_z: // Instruction st_z
    ISA._behavior_instruction(instr_dec->F_Type_Ptr.op);
    ISA._behavior_avr_Type_Ptr(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    ISA.behavior_st_z(instr_dec->F_Type_Ptr.op, instr_dec->F_Type_Ptr.rd, instr_dec->F_Type_Ptr.ptr);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_Halt.op);
    ISA._behavior_avr_Type_Halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    ISA.behavior_halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void avr::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void avr::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void avr::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void avr::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void avr::load(char* program) {
  DM_mport.load(program);
}

void avr::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned avr::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void avr::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void avr::PrintStat() {
  ac_arch<avr_parms::ac_word, avr_parms::ac_Hword>::PrintStat();
}

