/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "avr_isa.H"

//!Fields table declaration.
ac_dec_field avr_parms::avr_isa::fields[avr_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 6, 15, 1, 0, 0, &(avr_parms::avr_isa::fields[1])},
  {"rd", 5, 9, 2, 0, 0, &(avr_parms::avr_isa::fields[2])},
  {"rr", 5, 4, 3, 0, 0, NULL},
  {"op", 7, 15, 4, 0, 0, &(avr_parms::avr_isa::fields[4])},
  {"rd", 5, 8, 5, 0, 0, &(avr_parms::avr_isa::fields[5])},
  {"func", 4, 3, 6, 0, 0, NULL},
  {"op", 4, 15, 7, 0, 0, &(avr_parms::avr_isa::fields[7])},
  {"k_hi", 4, 11, 8, 0, 0, &(avr_parms::avr_isa::fields[8])},
  {"rd_hi", 4, 7, 9, 0, 0, &(avr_parms::avr_isa::fields[9])},
  {"k_lo", 4, 3, 6, 0, 0, NULL},
  {"op", 6, 15, 1, 0, 0, &(avr_parms::avr_isa::fields[11])},
  {"k_br", 7, 9, 10, 0, 1, &(avr_parms::avr_isa::fields[12])},
  {"cond", 3, 2, 11, 0, 0, NULL},
  {"op", 4, 15, 7, 0, 0, &(avr_parms::avr_isa::fields[14])},
  {"k_jmp", 12, 11, 12, 0, 1, NULL},
  {"op", 6, 15, 1, 0, 0, &(avr_parms::avr_isa::fields[16])},
  {"rd", 5, 9, 2, 0, 0, &(avr_parms::avr_isa::fields[17])},
  {"ptr", 5, 4, 3, 0, 0, NULL},
  {"op", 8, 15, 13, 0, 0, &(avr_parms::avr_isa::fields[19])},
  {"pad", 8, 7, 14, 0, 0, NULL}
};

ac_dec_format avr_parms::avr_isa::formats[avr_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_2R", 16, &(avr_parms::avr_isa::fields[0]), &(avr_parms::avr_isa::formats[1])},
  {2, "Type_1R", 16, &(avr_parms::avr_isa::fields[3]), &(avr_parms::avr_isa::formats[2])},
  {3, "Type_Imm", 16, &(avr_parms::avr_isa::fields[6]), &(avr_parms::avr_isa::formats[3])},
  {4, "Type_Branch", 16, &(avr_parms::avr_isa::fields[10]), &(avr_parms::avr_isa::formats[4])},
  {5, "Type_RJMP", 16, &(avr_parms::avr_isa::fields[13]), &(avr_parms::avr_isa::formats[5])},
  {6, "Type_Ptr", 16, &(avr_parms::avr_isa::fields[15]), &(avr_parms::avr_isa::formats[6])},
  {7, "Type_Halt", 16, &(avr_parms::avr_isa::fields[18]), NULL}
};

ac_dec_list avr_parms::avr_isa::dec_list[avr_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 3, NULL},
  {"op", 1, 7, NULL},
  {"op", 1, 6, NULL},
  {"op", 1, 2, NULL},
  {"op", 1, 8, NULL},
  {"op", 1, 10, NULL},
  {"op", 1, 9, NULL},
  {"op", 1, 5, NULL},
  {"op", 1, 11, NULL},
  {"op", 4, 75, &(avr_parms::avr_isa::dec_list[10])},
  {"func", 6, 3, NULL},
  {"op", 4, 75, &(avr_parms::avr_isa::dec_list[12])},
  {"func", 6, 10, NULL},
  {"op", 4, 75, &(avr_parms::avr_isa::dec_list[14])},
  {"func", 6, 0, NULL},
  {"op", 7, 14, NULL},
  {"op", 7, 5, NULL},
  {"op", 7, 7, NULL},
  {"op", 7, 6, NULL},
  {"op", 7, 3, NULL},
  {"op", 1, 61, &(avr_parms::avr_isa::dec_list[21])},
  {"cond", 11, 1, NULL},
  {"op", 1, 61, &(avr_parms::avr_isa::dec_list[23])},
  {"cond", 11, 0, NULL},
  {"op", 1, 61, &(avr_parms::avr_isa::dec_list[25])},
  {"cond", 11, 2, NULL},
  {"op", 1, 61, &(avr_parms::avr_isa::dec_list[27])},
  {"cond", 11, 3, NULL},
  {"op", 7, 12, NULL},
  {"op", 1, 36, &(avr_parms::avr_isa::dec_list[30])},
  {"ptr", 3, 12, NULL},
  {"op", 1, 37, &(avr_parms::avr_isa::dec_list[32])},
  {"ptr", 3, 12, NULL},
  {"op", 1, 32, &(avr_parms::avr_isa::dec_list[34])},
  {"ptr", 3, 0, NULL},
  {"op", 1, 33, &(avr_parms::avr_isa::dec_list[36])},
  {"ptr", 3, 0, NULL},
  {"op", 13, 149, &(avr_parms::avr_isa::dec_list[38])},
  {"pad", 14, 136, NULL}
};

ac_dec_instr avr_parms::avr_isa::instructions[avr_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_r", 2, "add", "add R%rd, R%rr", "Type_2R", 1, 1, 1, 1, &(avr_parms::avr_isa::dec_list[0]), 0, &(avr_parms::avr_isa::instructions[1])},
  {"adc_r", 2, "adc", "adc R%rd, R%rr", "Type_2R", 2, 1, 1, 1, &(avr_parms::avr_isa::dec_list[1]), 0, &(avr_parms::avr_isa::instructions[2])},
  {"sub_r", 2, "sub", "sub R%rd, R%rr", "Type_2R", 3, 1, 1, 1, &(avr_parms::avr_isa::dec_list[2]), 0, &(avr_parms::avr_isa::instructions[3])},
  {"sbc_r", 2, "sbc", "sbc R%rd, R%rr", "Type_2R", 4, 1, 1, 1, &(avr_parms::avr_isa::dec_list[3]), 0, &(avr_parms::avr_isa::instructions[4])},
  {"and_r", 2, "and", "and R%rd, R%rr", "Type_2R", 5, 1, 1, 1, &(avr_parms::avr_isa::dec_list[4]), 0, &(avr_parms::avr_isa::instructions[5])},
  {"or_r", 2, "or", "or R%rd, R%rr", "Type_2R", 6, 1, 1, 1, &(avr_parms::avr_isa::dec_list[5]), 0, &(avr_parms::avr_isa::instructions[6])},
  {"eor_r", 2, "eor", "eor R%rd, R%rr", "Type_2R", 7, 1, 1, 1, &(avr_parms::avr_isa::dec_list[6]), 0, &(avr_parms::avr_isa::instructions[7])},
  {"cp_r", 2, "cp", "cp R%rd, R%rr", "Type_2R", 8, 1, 1, 1, &(avr_parms::avr_isa::dec_list[7]), 0, &(avr_parms::avr_isa::instructions[8])},
  {"mov_r", 2, "mov", "mov R%rd, R%rr", "Type_2R", 9, 1, 1, 1, &(avr_parms::avr_isa::dec_list[8]), 0, &(avr_parms::avr_isa::instructions[9])},
  {"inc_r", 2, "inc", "inc R%rd", "Type_1R", 10, 1, 1, 1, &(avr_parms::avr_isa::dec_list[9]), 0, &(avr_parms::avr_isa::instructions[10])},
  {"dec_r", 2, "dec", "dec R%rd", "Type_1R", 11, 1, 1, 1, &(avr_parms::avr_isa::dec_list[11]), 0, &(avr_parms::avr_isa::instructions[11])},
  {"clr_r", 2, "clr", "clr R%rd", "Type_1R", 12, 1, 1, 1, &(avr_parms::avr_isa::dec_list[13]), 0, &(avr_parms::avr_isa::instructions[12])},
  {"ldi_i", 2, "ldi", "ldi R%rd_hi, #%k_hi:%k_lo", "Type_Imm", 13, 1, 1, 1, &(avr_parms::avr_isa::dec_list[15]), 0, &(avr_parms::avr_isa::instructions[13])},
  {"subi_i", 2, "subi", "subi R%rd_hi, #%k_hi:%k_lo", "Type_Imm", 14, 1, 1, 1, &(avr_parms::avr_isa::dec_list[16]), 0, &(avr_parms::avr_isa::instructions[14])},
  {"andi_i", 2, "andi", "andi R%rd_hi, #%k_hi:%k_lo", "Type_Imm", 15, 1, 1, 1, &(avr_parms::avr_isa::dec_list[17]), 0, &(avr_parms::avr_isa::instructions[15])},
  {"ori_i", 2, "ori", "ori R%rd_hi, #%k_hi:%k_lo", "Type_Imm", 16, 1, 1, 1, &(avr_parms::avr_isa::dec_list[18]), 0, &(avr_parms::avr_isa::instructions[16])},
  {"cpi_i", 2, "cpi", "cpi R%rd_hi, #%k_hi:%k_lo", "Type_Imm", 17, 1, 1, 1, &(avr_parms::avr_isa::dec_list[19]), 0, &(avr_parms::avr_isa::instructions[17])},
  {"brne", 2, "brne", "brne %k_br", "Type_Branch", 18, 1, 1, 1, &(avr_parms::avr_isa::dec_list[20]), 0, &(avr_parms::avr_isa::instructions[18])},
  {"breq", 2, "breq", "breq %k_br", "Type_Branch", 19, 1, 1, 1, &(avr_parms::avr_isa::dec_list[22]), 0, &(avr_parms::avr_isa::instructions[19])},
  {"brcs", 2, "brcs", "brcs %k_br", "Type_Branch", 20, 1, 1, 1, &(avr_parms::avr_isa::dec_list[24]), 0, &(avr_parms::avr_isa::instructions[20])},
  {"brcc", 2, "brcc", "brcc %k_br", "Type_Branch", 21, 1, 1, 1, &(avr_parms::avr_isa::dec_list[26]), 0, &(avr_parms::avr_isa::instructions[21])},
  {"rjmp", 2, "rjmp", "rjmp %k_jmp", "Type_RJMP", 22, 1, 1, 1, &(avr_parms::avr_isa::dec_list[28]), 0, &(avr_parms::avr_isa::instructions[22])},
  {"ld_x", 2, "ld", "ld R%rd, X", "Type_Ptr", 23, 1, 1, 1, &(avr_parms::avr_isa::dec_list[29]), 0, &(avr_parms::avr_isa::instructions[23])},
  {"st_x", 2, "st", "st X, R%rd", "Type_Ptr", 24, 1, 1, 1, &(avr_parms::avr_isa::dec_list[31]), 0, &(avr_parms::avr_isa::instructions[24])},
  {"ld_z", 2, "ld", "ld R%rd, Z", "Type_Ptr", 25, 1, 1, 1, &(avr_parms::avr_isa::dec_list[33]), 0, &(avr_parms::avr_isa::instructions[25])},
  {"st_z", 2, "st", "st Z, R%rd", "Type_Ptr", 26, 1, 1, 1, &(avr_parms::avr_isa::dec_list[35]), 0, &(avr_parms::avr_isa::instructions[26])},
  {"halt", 2, "halt", "halt", "Type_Halt", 27, 1, 1, 1, &(avr_parms::avr_isa::dec_list[37]), 0, NULL}
};

const ac_instr_info
avr_parms::avr_isa::instr_table[avr_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 1),
  ac_instr_info(1, "add_r", "add", 2),
  ac_instr_info(2, "adc_r", "adc", 2),
  ac_instr_info(3, "sub_r", "sub", 2),
  ac_instr_info(4, "sbc_r", "sbc", 2),
  ac_instr_info(5, "and_r", "and", 2),
  ac_instr_info(6, "or_r", "or", 2),
  ac_instr_info(7, "eor_r", "eor", 2),
  ac_instr_info(8, "cp_r", "cp", 2),
  ac_instr_info(9, "mov_r", "mov", 2),
  ac_instr_info(10, "inc_r", "inc", 2),
  ac_instr_info(11, "dec_r", "dec", 2),
  ac_instr_info(12, "clr_r", "clr", 2),
  ac_instr_info(13, "ldi_i", "ldi", 2),
  ac_instr_info(14, "subi_i", "subi", 2),
  ac_instr_info(15, "andi_i", "andi", 2),
  ac_instr_info(16, "ori_i", "ori", 2),
  ac_instr_info(17, "cpi_i", "cpi", 2),
  ac_instr_info(18, "brne", "brne", 2),
  ac_instr_info(19, "breq", "breq", 2),
  ac_instr_info(20, "brcs", "brcs", 2),
  ac_instr_info(21, "brcc", "brcc", 2),
  ac_instr_info(22, "rjmp", "rjmp", 2),
  ac_instr_info(23, "ld_x", "ld", 2),
  ac_instr_info(24, "st_x", "st", 2),
  ac_instr_info(25, "ld_z", "ld", 2),
  ac_instr_info(26, "st_z", "st", 2),
  ac_instr_info(27, "halt", "halt", 2)
};

const unsigned avr_parms::avr_isa::instr_format_table[avr_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  4,
  4,
  4,
  4,
  5,
  6,
  6,
  6,
  6,
  7
};
