/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "m68k_arch.H"
#include  "m68k_arch_ref.H"

//!/Default constructor.
m68k_arch_ref::m68k_arch_ref(m68k_arch& arch) : ac_arch_ref<m68k_parms::ac_word, m68k_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   RD(arch.RD),   RA(arch.RA),   sr(arch.sr) {}

