/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "m68k_arch.H"


m68k_arch::m68k_arch() :
  ac_arch_dec_if<m68k_parms::ac_word, m68k_parms::ac_Hword>(m68k_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  RD("RD"),
  RA("RA"),
  sr("sr", 0) {

  ac_mt_endian = m68k_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = m68k_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int m68k_arch::globalId = 0;