/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "m68k_isa.H"

//!Fields table declaration.
ac_dec_field m68k_parms::m68k_isa::fields[m68k_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 4, 3, 1, 0, 0, &(m68k_parms::m68k_isa::fields[1])},
  {"rd", 3, 6, 2, 0, 0, &(m68k_parms::m68k_isa::fields[2])},
  {"zero", 1, 7, 3, 0, 0, &(m68k_parms::m68k_isa::fields[3])},
  {"data", 8, 15, 4, 0, 1, NULL},
  {"op", 4, 3, 1, 0, 0, &(m68k_parms::m68k_isa::fields[5])},
  {"rd", 3, 6, 2, 0, 0, &(m68k_parms::m68k_isa::fields[6])},
  {"opmode", 3, 9, 5, 0, 0, &(m68k_parms::m68k_isa::fields[7])},
  {"mode", 3, 12, 6, 0, 0, &(m68k_parms::m68k_isa::fields[8])},
  {"reg", 3, 15, 7, 0, 0, NULL},
  {"op", 4, 3, 1, 0, 0, &(m68k_parms::m68k_isa::fields[10])},
  {"qdata", 3, 6, 2, 0, 0, &(m68k_parms::m68k_isa::fields[11])},
  {"s", 1, 7, 3, 0, 0, &(m68k_parms::m68k_isa::fields[12])},
  {"size", 2, 9, 8, 0, 0, &(m68k_parms::m68k_isa::fields[13])},
  {"mode", 3, 12, 6, 0, 0, &(m68k_parms::m68k_isa::fields[14])},
  {"reg", 3, 15, 7, 0, 0, NULL},
  {"op", 4, 3, 1, 0, 0, &(m68k_parms::m68k_isa::fields[16])},
  {"cond", 4, 7, 9, 0, 0, &(m68k_parms::m68k_isa::fields[17])},
  {"bdisp", 8, 15, 4, 0, 1, NULL},
  {"op", 4, 3, 1, 0, 0, &(m68k_parms::m68k_isa::fields[19])},
  {"size", 2, 5, 10, 0, 0, &(m68k_parms::m68k_isa::fields[20])},
  {"dst_reg", 3, 8, 11, 0, 0, &(m68k_parms::m68k_isa::fields[21])},
  {"dst_mode", 3, 11, 12, 0, 0, &(m68k_parms::m68k_isa::fields[22])},
  {"src_mode", 3, 14, 13, 0, 0, &(m68k_parms::m68k_isa::fields[23])},
  {"src_reg", 3, 17, 14, 0, 0, NULL},
  {"op", 16, 15, 15, 0, 0, NULL}
};

ac_dec_format m68k_parms::m68k_isa::formats[m68k_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_MoveQ", 16, &(m68k_parms::m68k_isa::fields[0]), &(m68k_parms::m68k_isa::formats[1])},
  {2, "Type_ALU_Reg", 16, &(m68k_parms::m68k_isa::fields[4]), &(m68k_parms::m68k_isa::formats[2])},
  {3, "Type_Quick", 16, &(m68k_parms::m68k_isa::fields[9]), &(m68k_parms::m68k_isa::formats[3])},
  {4, "Type_Branch", 16, &(m68k_parms::m68k_isa::fields[15]), &(m68k_parms::m68k_isa::formats[4])},
  {5, "Type_Move_Mem", 18, &(m68k_parms::m68k_isa::fields[18]), &(m68k_parms::m68k_isa::formats[5])},
  {6, "Type_Halt", 16, &(m68k_parms::m68k_isa::fields[24]), NULL}
};

ac_dec_list m68k_parms::m68k_isa::dec_list[m68k_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 7, &(m68k_parms::m68k_isa::dec_list[1])},
  {"zero", 3, 0, NULL},
  {"op", 1, 13, &(m68k_parms::m68k_isa::dec_list[3])},
  {"opmode", 5, 2, &(m68k_parms::m68k_isa::dec_list[4])},
  {"mode", 6, 0, NULL},
  {"op", 1, 9, &(m68k_parms::m68k_isa::dec_list[6])},
  {"opmode", 5, 2, &(m68k_parms::m68k_isa::dec_list[7])},
  {"mode", 6, 0, NULL},
  {"op", 1, 12, &(m68k_parms::m68k_isa::dec_list[9])},
  {"opmode", 5, 7, &(m68k_parms::m68k_isa::dec_list[10])},
  {"mode", 6, 0, NULL},
  {"op", 1, 12, &(m68k_parms::m68k_isa::dec_list[12])},
  {"opmode", 5, 2, &(m68k_parms::m68k_isa::dec_list[13])},
  {"mode", 6, 0, NULL},
  {"op", 1, 8, &(m68k_parms::m68k_isa::dec_list[15])},
  {"opmode", 5, 2, &(m68k_parms::m68k_isa::dec_list[16])},
  {"mode", 6, 0, NULL},
  {"op", 1, 11, &(m68k_parms::m68k_isa::dec_list[18])},
  {"opmode", 5, 2, &(m68k_parms::m68k_isa::dec_list[19])},
  {"mode", 6, 0, NULL},
  {"op", 1, 5, &(m68k_parms::m68k_isa::dec_list[21])},
  {"s", 3, 0, &(m68k_parms::m68k_isa::dec_list[22])},
  {"size", 8, 2, &(m68k_parms::m68k_isa::dec_list[23])},
  {"mode", 6, 0, NULL},
  {"op", 1, 5, &(m68k_parms::m68k_isa::dec_list[25])},
  {"s", 3, 1, &(m68k_parms::m68k_isa::dec_list[26])},
  {"size", 8, 2, &(m68k_parms::m68k_isa::dec_list[27])},
  {"mode", 6, 0, NULL},
  {"op", 1, 6, &(m68k_parms::m68k_isa::dec_list[29])},
  {"cond", 9, 0, NULL},
  {"op", 1, 6, &(m68k_parms::m68k_isa::dec_list[31])},
  {"cond", 9, 6, NULL},
  {"op", 1, 6, &(m68k_parms::m68k_isa::dec_list[33])},
  {"cond", 9, 7, NULL},
  {"op", 1, 6, &(m68k_parms::m68k_isa::dec_list[35])},
  {"cond", 9, 13, NULL},
  {"op", 1, 6, &(m68k_parms::m68k_isa::dec_list[37])},
  {"cond", 9, 12, NULL},
  {"op", 1, 2, &(m68k_parms::m68k_isa::dec_list[39])},
  {"size", 10, 0, &(m68k_parms::m68k_isa::dec_list[40])},
  {"dst_mode", 12, 2, &(m68k_parms::m68k_isa::dec_list[41])},
  {"src_mode", 13, 0, NULL},
  {"op", 1, 2, &(m68k_parms::m68k_isa::dec_list[43])},
  {"size", 10, 0, &(m68k_parms::m68k_isa::dec_list[44])},
  {"dst_mode", 12, 0, &(m68k_parms::m68k_isa::dec_list[45])},
  {"src_mode", 13, 2, NULL},
  {"op", 15, 19196, NULL}
};

ac_dec_instr m68k_parms::m68k_isa::instructions[m68k_parms::AC_DEC_INSTR_NUMBER] = {
  {"moveq", 2, "moveq", "moveq #%data, D%rd", "Type_MoveQ", 1, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[0]), 0, &(m68k_parms::m68k_isa::instructions[1])},
  {"add_l", 2, "add.l", "add.l D%reg, D%rd", "Type_ALU_Reg", 2, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[2]), 0, &(m68k_parms::m68k_isa::instructions[2])},
  {"sub_l", 2, "sub.l", "sub.l D%reg, D%rd", "Type_ALU_Reg", 3, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[5]), 0, &(m68k_parms::m68k_isa::instructions[3])},
  {"mul_l", 2, "muls", "muls D%reg, D%rd", "Type_ALU_Reg", 4, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[8]), 0, &(m68k_parms::m68k_isa::instructions[4])},
  {"and_l", 2, "and.l", "and.l D%reg, D%rd", "Type_ALU_Reg", 5, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[11]), 0, &(m68k_parms::m68k_isa::instructions[5])},
  {"or_l", 2, "or.l", "or.l D%reg, D%rd", "Type_ALU_Reg", 6, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[14]), 0, &(m68k_parms::m68k_isa::instructions[6])},
  {"eor_l", 2, "eor.l", "eor.l D%reg, D%rd", "Type_ALU_Reg", 7, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[17]), 0, &(m68k_parms::m68k_isa::instructions[7])},
  {"addq_l", 2, "addq.l", "addq.l #%qdata, D%reg", "Type_Quick", 8, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[20]), 0, &(m68k_parms::m68k_isa::instructions[8])},
  {"subq_l", 2, "subq.l", "subq.l #%qdata, D%reg", "Type_Quick", 9, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[24]), 0, &(m68k_parms::m68k_isa::instructions[9])},
  {"bra", 2, "bra", "bra %bdisp", "Type_Branch", 10, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[28]), 0, &(m68k_parms::m68k_isa::instructions[10])},
  {"bne", 2, "bne", "bne %bdisp", "Type_Branch", 11, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[30]), 0, &(m68k_parms::m68k_isa::instructions[11])},
  {"beq", 2, "beq", "beq %bdisp", "Type_Branch", 12, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[32]), 0, &(m68k_parms::m68k_isa::instructions[12])},
  {"blt", 2, "blt", "blt %bdisp", "Type_Branch", 13, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[34]), 0, &(m68k_parms::m68k_isa::instructions[13])},
  {"bge", 2, "bge", "bge %bdisp", "Type_Branch", 14, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[36]), 0, &(m68k_parms::m68k_isa::instructions[14])},
  {"move_to_mem", 2, "move.l", "move.l D%src_reg, (A%dst_reg)", "Type_Move_Mem", 15, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[38]), 0, &(m68k_parms::m68k_isa::instructions[15])},
  {"move_from_mem", 2, "move.l", "move.l (A%src_reg), D%dst_reg", "Type_Move_Mem", 16, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[42]), 0, &(m68k_parms::m68k_isa::instructions[16])},
  {"halt", 2, "illegal", "illegal", "Type_Halt", 17, 1, 1, 1, &(m68k_parms::m68k_isa::dec_list[46]), 0, NULL}
};

const ac_instr_info
m68k_parms::m68k_isa::instr_table[m68k_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "moveq", "moveq", 2),
  ac_instr_info(2, "add_l", "add.l", 2),
  ac_instr_info(3, "sub_l", "sub.l", 2),
  ac_instr_info(4, "mul_l", "muls", 2),
  ac_instr_info(5, "and_l", "and.l", 2),
  ac_instr_info(6, "or_l", "or.l", 2),
  ac_instr_info(7, "eor_l", "eor.l", 2),
  ac_instr_info(8, "addq_l", "addq.l", 2),
  ac_instr_info(9, "subq_l", "subq.l", 2),
  ac_instr_info(10, "bra", "bra", 2),
  ac_instr_info(11, "bne", "bne", 2),
  ac_instr_info(12, "beq", "beq", 2),
  ac_instr_info(13, "blt", "blt", 2),
  ac_instr_info(14, "bge", "bge", 2),
  ac_instr_info(15, "move_to_mem", "move.l", 2),
  ac_instr_info(16, "move_from_mem", "move.l", 2),
  ac_instr_info(17, "halt", "illegal", 2)
};

const unsigned m68k_parms::m68k_isa::instr_format_table[m68k_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  4,
  4,
  4,
  4,
  4,
  5,
  5,
  6
};
