/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "arm.H"
#include  "arm_isa.cpp"

#include  "arm_syscall.H"

void* arm::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_DP.cond = ins_cache[1];
        instr_dec->F_Type_DP.op = ins_cache[2];
        instr_dec->F_Type_DP.cmd = ins_cache[3];
        instr_dec->F_Type_DP.s = ins_cache[4];
        instr_dec->F_Type_DP.rn = ins_cache[5];
        instr_dec->F_Type_DP.rd = ins_cache[6];
        instr_dec->F_Type_DP.op2 = ins_cache[7];
      break;
      case 2:
        instr_dec->F_Type_MEM.cond = ins_cache[8];
        instr_dec->F_Type_MEM.op = ins_cache[9];
        instr_dec->F_Type_MEM.i = ins_cache[10];
        instr_dec->F_Type_MEM.p = ins_cache[11];
        instr_dec->F_Type_MEM.u = ins_cache[12];
        instr_dec->F_Type_MEM.b = ins_cache[13];
        instr_dec->F_Type_MEM.w = ins_cache[14];
        instr_dec->F_Type_MEM.l = ins_cache[4];
        instr_dec->F_Type_MEM.rn = ins_cache[5];
        instr_dec->F_Type_MEM.rd = ins_cache[6];
        instr_dec->F_Type_MEM.offset = ins_cache[7];
      break;
      case 3:
        instr_dec->F_Type_BR.cond = ins_cache[8];
        instr_dec->F_Type_BR.op = ins_cache[15];
        instr_dec->F_Type_BR.l = ins_cache[11];
        instr_dec->F_Type_BR.offset = ins_cache[16];
      break;
      case 4:
        instr_dec->F_Type_HLT.cond = ins_cache[8];
        instr_dec->F_Type_HLT.op = ins_cache[17];
        instr_dec->F_Type_HLT.imm = ins_cache[18];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void arm::behavior() {

  void* vet[] = {&&I_Init, &&I_add, &&I_sub, &&I_mov, &&I_cmp_op, 
              &&I_and_op, &&I_orr, &&I_eor, &&I_ldr, &&I_str, 
              &&I_b, &&I_bl, &&I_hlt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add: // Instruction add
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_add(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_sub: // Instruction sub
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_sub(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_mov: // Instruction mov
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_mov(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_cmp_op: // Instruction cmp_op
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_cmp_op(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_and_op: // Instruction and_op
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_and_op(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_orr: // Instruction orr
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_orr(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_eor: // Instruction eor
    ISA._behavior_instruction(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op);
    ISA._behavior_arm_Type_DP(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    ISA.behavior_eor(instr_dec->F_Type_DP.cond, instr_dec->F_Type_DP.op, instr_dec->F_Type_DP.cmd, instr_dec->F_Type_DP.s, instr_dec->F_Type_DP.rn, instr_dec->F_Type_DP.rd, instr_dec->F_Type_DP.op2);
    goto *dispatch();

  I_ldr: // Instruction ldr
    ISA._behavior_instruction(instr_dec->F_Type_MEM.cond, instr_dec->F_Type_MEM.op);
    ISA._behavior_arm_Type_MEM(instr_dec->F_Type_MEM.cond, instr_dec->F_Type_MEM.op, instr_dec->F_Type_MEM.i, instr_dec->F_Type_MEM.p, instr_dec->F_Type_MEM.u, instr_dec->F_Type_MEM.b, instr_dec->F_Type_MEM.w, instr_dec->F_Type_MEM.l, instr_dec->F_Type_MEM.rn, instr_dec->F_Type_MEM.rd, instr_dec->F_Type_MEM.offset);
    ISA.behavior_ldr(instr_dec->F_Type_MEM.cond, instr_dec->F_Type_MEM.op, instr_dec->F_Type_MEM.i, instr_dec->F_Type_MEM.p, instr_dec->F_Type_MEM.u, instr_dec->F_Type_MEM.b, instr_dec->F_Type_MEM.w, instr_dec->F_Type_MEM.l, instr_dec->F_Type_MEM.rn, instr_dec->F_Type_MEM.rd, instr_dec->F_Type_MEM.offset);
    goto *dispatch();

  I_str: // Instruction str
    ISA._behavior_instruction(instr_dec->F_Type_MEM.cond, instr_dec->F_Type_MEM.op);
    ISA._behavior_arm_Type_MEM(instr_dec->F_Type_MEM.cond, instr_dec->F_Type_MEM.op, instr_dec->F_Type_MEM.i, instr_dec->F_Type_MEM.p, instr_dec->F_Type_MEM.u, instr_dec->F_Type_MEM.b, instr_dec->F_Type_MEM.w, instr_dec->F_Type_MEM.l, instr_dec->F_Type_MEM.rn, instr_dec->F_Type_MEM.rd, instr_dec->F_Type_MEM.offset);
    ISA.behavior_str(instr_dec->F_Type_MEM.cond, instr_dec->F_Type_MEM.op, instr_dec->F_Type_MEM.i, instr_dec->F_Type_MEM.p, instr_dec->F_Type_MEM.u, instr_dec->F_Type_MEM.b, instr_dec->F_Type_MEM.w, instr_dec->F_Type_MEM.l, instr_dec->F_Type_MEM.rn, instr_dec->F_Type_MEM.rd, instr_dec->F_Type_MEM.offset);
    goto *dispatch();

  I_b: // Instruction b
    ISA._behavior_instruction(instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op);
    ISA._behavior_arm_Type_BR(instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.l, instr_dec->F_Type_BR.offset);
    ISA.behavior_b(instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.l, instr_dec->F_Type_BR.offset);
    goto *dispatch();

  I_bl: // Instruction bl
    ISA._behavior_instruction(instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op);
    ISA._behavior_arm_Type_BR(instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.l, instr_dec->F_Type_BR.offset);
    ISA.behavior_bl(instr_dec->F_Type_BR.cond, instr_dec->F_Type_BR.op, instr_dec->F_Type_BR.l, instr_dec->F_Type_BR.offset);
    goto *dispatch();

  I_hlt: // Instruction hlt
    ISA._behavior_instruction(instr_dec->F_Type_HLT.cond, instr_dec->F_Type_HLT.op);
    ISA._behavior_arm_Type_HLT(instr_dec->F_Type_HLT.cond, instr_dec->F_Type_HLT.op, instr_dec->F_Type_HLT.imm);
    ISA.behavior_hlt(instr_dec->F_Type_HLT.cond, instr_dec->F_Type_HLT.op, instr_dec->F_Type_HLT.imm);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void arm::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void arm::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void arm::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void arm::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void arm::load(char* program) {
  DM_mport.load(program);
}

void arm::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned arm::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void arm::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void arm::PrintStat() {
  ac_arch<arm_parms::ac_word, arm_parms::ac_Hword>::PrintStat();
}

