/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "arm_isa.H"

//!Fields table declaration.
ac_dec_field arm_parms::arm_isa::fields[arm_parms::AC_DEC_FIELD_NUMBER] = {
  {"cond", 4, 30, 1, 0, 0, &(arm_parms::arm_isa::fields[1])},
  {"op", 2, 26, 2, 0, 0, &(arm_parms::arm_isa::fields[2])},
  {"cmd", 4, 24, 3, 0, 0, &(arm_parms::arm_isa::fields[3])},
  {"s", 1, 20, 4, 0, 0, &(arm_parms::arm_isa::fields[4])},
  {"rn", 4, 19, 5, 0, 0, &(arm_parms::arm_isa::fields[5])},
  {"rd", 4, 15, 6, 0, 0, &(arm_parms::arm_isa::fields[6])},
  {"op2", 12, 11, 7, 0, 0, NULL},
  {"cond", 4, 31, 8, 0, 0, &(arm_parms::arm_isa::fields[8])},
  {"op", 2, 27, 9, 0, 0, &(arm_parms::arm_isa::fields[9])},
  {"i", 1, 25, 10, 0, 0, &(arm_parms::arm_isa::fields[10])},
  {"p", 1, 24, 11, 0, 0, &(arm_parms::arm_isa::fields[11])},
  {"u", 1, 23, 12, 0, 0, &(arm_parms::arm_isa::fields[12])},
  {"b", 1, 22, 13, 0, 0, &(arm_parms::arm_isa::fields[13])},
  {"w", 1, 21, 14, 0, 0, &(arm_parms::arm_isa::fields[14])},
  {"l", 1, 20, 4, 0, 0, &(arm_parms::arm_isa::fields[15])},
  {"rn", 4, 19, 5, 0, 0, &(arm_parms::arm_isa::fields[16])},
  {"rd", 4, 15, 6, 0, 0, &(arm_parms::arm_isa::fields[17])},
  {"offset", 12, 11, 7, 0, 0, NULL},
  {"cond", 4, 31, 8, 0, 0, &(arm_parms::arm_isa::fields[19])},
  {"op", 3, 27, 15, 0, 0, &(arm_parms::arm_isa::fields[20])},
  {"l", 1, 24, 11, 0, 0, &(arm_parms::arm_isa::fields[21])},
  {"offset", 24, 23, 16, 0, 1, NULL},
  {"cond", 4, 31, 8, 0, 0, &(arm_parms::arm_isa::fields[23])},
  {"op", 4, 27, 17, 0, 0, &(arm_parms::arm_isa::fields[24])},
  {"imm", 24, 23, 18, 0, 0, NULL}
};

ac_dec_format arm_parms::arm_isa::formats[arm_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_DP", 31, &(arm_parms::arm_isa::fields[0]), &(arm_parms::arm_isa::formats[1])},
  {2, "Type_MEM", 32, &(arm_parms::arm_isa::fields[7]), &(arm_parms::arm_isa::formats[2])},
  {3, "Type_BR", 32, &(arm_parms::arm_isa::fields[18]), &(arm_parms::arm_isa::formats[3])},
  {4, "Type_HLT", 32, &(arm_parms::arm_isa::fields[22]), NULL}
};

ac_dec_list arm_parms::arm_isa::dec_list[arm_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[1])},
  {"cmd", 3, 4, NULL},
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[3])},
  {"cmd", 3, 2, NULL},
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[5])},
  {"cmd", 3, 13, NULL},
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[7])},
  {"cmd", 3, 10, NULL},
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[9])},
  {"cmd", 3, 0, NULL},
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[11])},
  {"cmd", 3, 12, NULL},
  {"op", 2, 0, &(arm_parms::arm_isa::dec_list[13])},
  {"cmd", 3, 1, NULL},
  {"op", 9, 1, &(arm_parms::arm_isa::dec_list[15])},
  {"l", 4, 1, NULL},
  {"op", 9, 1, &(arm_parms::arm_isa::dec_list[17])},
  {"l", 4, 0, NULL},
  {"op", 15, 5, &(arm_parms::arm_isa::dec_list[19])},
  {"l", 11, 0, NULL},
  {"op", 15, 5, &(arm_parms::arm_isa::dec_list[21])},
  {"l", 11, 1, NULL},
  {"op", 17, 15, NULL}
};

ac_dec_instr arm_parms::arm_isa::instructions[arm_parms::AC_DEC_INSTR_NUMBER] = {
  {"add", 3, "add", "add %rd, %rn, %op2", "Type_DP", 1, 1, 1, 1, &(arm_parms::arm_isa::dec_list[0]), 0, &(arm_parms::arm_isa::instructions[1])},
  {"sub", 3, "sub", "sub %rd, %rn, %op2", "Type_DP", 2, 1, 1, 1, &(arm_parms::arm_isa::dec_list[2]), 0, &(arm_parms::arm_isa::instructions[2])},
  {"mov", 3, "mov", "mov %rd, %op2", "Type_DP", 3, 1, 1, 1, &(arm_parms::arm_isa::dec_list[4]), 0, &(arm_parms::arm_isa::instructions[3])},
  {"cmp_op", 3, "cmp", "cmp %rn, %op2", "Type_DP", 4, 1, 1, 1, &(arm_parms::arm_isa::dec_list[6]), 0, &(arm_parms::arm_isa::instructions[4])},
  {"and_op", 3, "and", "and %rd, %rn, %op2", "Type_DP", 5, 1, 1, 1, &(arm_parms::arm_isa::dec_list[8]), 0, &(arm_parms::arm_isa::instructions[5])},
  {"orr", 3, "orr", "orr %rd, %rn, %op2", "Type_DP", 6, 1, 1, 1, &(arm_parms::arm_isa::dec_list[10]), 0, &(arm_parms::arm_isa::instructions[6])},
  {"eor", 3, "eor", "eor %rd, %rn, %op2", "Type_DP", 7, 1, 1, 1, &(arm_parms::arm_isa::dec_list[12]), 0, &(arm_parms::arm_isa::instructions[7])},
  {"ldr", 4, "ldr", "ldr %rd, [%rn, %offset]", "Type_MEM", 8, 1, 1, 1, &(arm_parms::arm_isa::dec_list[14]), 0, &(arm_parms::arm_isa::instructions[8])},
  {"str", 4, "str", "str %rd, [%rn, %offset]", "Type_MEM", 9, 1, 1, 1, &(arm_parms::arm_isa::dec_list[16]), 0, &(arm_parms::arm_isa::instructions[9])},
  {"b", 4, "b", "b %offset", "Type_BR", 10, 1, 1, 1, &(arm_parms::arm_isa::dec_list[18]), 0, &(arm_parms::arm_isa::instructions[10])},
  {"bl", 4, "bl", "bl %offset", "Type_BR", 11, 1, 1, 1, &(arm_parms::arm_isa::dec_list[20]), 0, &(arm_parms::arm_isa::instructions[11])},
  {"hlt", 4, "hlt", "hlt", "Type_HLT", 12, 1, 1, 1, &(arm_parms::arm_isa::dec_list[22]), 0, NULL}
};

const ac_instr_info
arm_parms::arm_isa::instr_table[arm_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "add", "add", 3),
  ac_instr_info(2, "sub", "sub", 3),
  ac_instr_info(3, "mov", "mov", 3),
  ac_instr_info(4, "cmp_op", "cmp", 3),
  ac_instr_info(5, "and_op", "and", 3),
  ac_instr_info(6, "orr", "orr", 3),
  ac_instr_info(7, "eor", "eor", 3),
  ac_instr_info(8, "ldr", "ldr", 4),
  ac_instr_info(9, "str", "str", 4),
  ac_instr_info(10, "b", "b", 4),
  ac_instr_info(11, "bl", "bl", 4),
  ac_instr_info(12, "hlt", "hlt", 4)
};

const unsigned arm_parms::arm_isa::instr_format_table[arm_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  3,
  3,
  4
};
