/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "x86_64_isa.H"

//!Fields table declaration.
ac_dec_field x86_64_parms::x86_64_isa::fields[x86_64_parms::AC_DEC_FIELD_NUMBER] = {
  {"opcode", 8, 31, 1, 0, 0, &(x86_64_parms::x86_64_isa::fields[1])},
  {"rex", 4, 23, 2, 0, 0, &(x86_64_parms::x86_64_isa::fields[2])},
  {"reg", 4, 19, 3, 0, 0, &(x86_64_parms::x86_64_isa::fields[3])},
  {"rm", 4, 15, 4, 0, 0, &(x86_64_parms::x86_64_isa::fields[4])},
  {"pad", 12, 11, 5, 0, 0, NULL},
  {"opcode", 8, 31, 1, 0, 0, &(x86_64_parms::x86_64_isa::fields[6])},
  {"reg", 4, 23, 2, 0, 0, &(x86_64_parms::x86_64_isa::fields[7])},
  {"pad", 4, 19, 3, 0, 0, &(x86_64_parms::x86_64_isa::fields[8])},
  {"imm", 16, 15, 6, 0, 1, NULL},
  {"opcode", 8, 31, 1, 0, 0, &(x86_64_parms::x86_64_isa::fields[10])},
  {"reg", 4, 23, 2, 0, 0, &(x86_64_parms::x86_64_isa::fields[11])},
  {"rm", 4, 19, 3, 0, 0, &(x86_64_parms::x86_64_isa::fields[12])},
  {"disp", 16, 15, 6, 0, 1, NULL},
  {"opcode", 8, 31, 1, 0, 0, &(x86_64_parms::x86_64_isa::fields[14])},
  {"offset", 24, 23, 7, 0, 1, NULL},
  {"opcode", 8, 31, 1, 0, 0, &(x86_64_parms::x86_64_isa::fields[16])},
  {"pad", 24, 23, 8, 0, 0, NULL}
};

ac_dec_format x86_64_parms::x86_64_isa::formats[x86_64_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_RR", 32, &(x86_64_parms::x86_64_isa::fields[0]), &(x86_64_parms::x86_64_isa::formats[1])},
  {2, "Type_RI", 32, &(x86_64_parms::x86_64_isa::fields[5]), &(x86_64_parms::x86_64_isa::formats[2])},
  {3, "Type_RM", 32, &(x86_64_parms::x86_64_isa::fields[9]), &(x86_64_parms::x86_64_isa::formats[3])},
  {4, "Type_J", 32, &(x86_64_parms::x86_64_isa::fields[13]), &(x86_64_parms::x86_64_isa::formats[4])},
  {5, "Type_HLT", 32, &(x86_64_parms::x86_64_isa::fields[15]), NULL}
};

ac_dec_list x86_64_parms::x86_64_isa::dec_list[x86_64_parms::AC_DEC_LIST_NUMBER] = {
  {"opcode", 1, 1, NULL},
  {"opcode", 1, 41, NULL},
  {"opcode", 1, 33, NULL},
  {"opcode", 1, 9, NULL},
  {"opcode", 1, 49, NULL},
  {"opcode", 1, 137, NULL},
  {"opcode", 1, 175, NULL},
  {"opcode", 1, 184, NULL},
  {"opcode", 1, 129, NULL},
  {"opcode", 1, 131, NULL},
  {"opcode", 1, 61, NULL},
  {"opcode", 1, 139, NULL},
  {"opcode", 1, 136, NULL},
  {"opcode", 1, 233, NULL},
  {"opcode", 1, 117, NULL},
  {"opcode", 1, 116, NULL},
  {"opcode", 1, 244, NULL}
};

ac_dec_instr x86_64_parms::x86_64_isa::instructions[x86_64_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_rr", 4, "addq", "addq %reg, %rm", "Type_RR", 1, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[0]), 0, &(x86_64_parms::x86_64_isa::instructions[1])},
  {"sub_rr", 4, "subq", "subq %reg, %rm", "Type_RR", 2, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[1]), 0, &(x86_64_parms::x86_64_isa::instructions[2])},
  {"and_rr", 4, "andq", "andq %reg, %rm", "Type_RR", 3, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[2]), 0, &(x86_64_parms::x86_64_isa::instructions[3])},
  {"or_rr", 4, "orq", "orq %reg, %rm", "Type_RR", 4, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[3]), 0, &(x86_64_parms::x86_64_isa::instructions[4])},
  {"xor_rr", 4, "xorq", "xorq %reg, %rm", "Type_RR", 5, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[4]), 0, &(x86_64_parms::x86_64_isa::instructions[5])},
  {"mov_rr", 4, "movq", "movq %reg, %rm", "Type_RR", 6, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[5]), 0, &(x86_64_parms::x86_64_isa::instructions[6])},
  {"imul_rr", 4, "imulq", "imulq %reg, %rm", "Type_RR", 7, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[6]), 0, &(x86_64_parms::x86_64_isa::instructions[7])},
  {"mov_ri", 4, "movq", "movq %imm, %reg", "Type_RI", 8, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[7]), 0, &(x86_64_parms::x86_64_isa::instructions[8])},
  {"add_ri", 4, "addq", "addq %imm, %reg", "Type_RI", 9, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[8]), 0, &(x86_64_parms::x86_64_isa::instructions[9])},
  {"sub_ri", 4, "subq", "subq %imm, %reg", "Type_RI", 10, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[9]), 0, &(x86_64_parms::x86_64_isa::instructions[10])},
  {"cmp_ri", 4, "cmpq", "cmpq %imm, %reg", "Type_RI", 11, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[10]), 0, &(x86_64_parms::x86_64_isa::instructions[11])},
  {"mov_rm", 4, "movq", "movq %disp(%rm), %reg", "Type_RM", 12, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[11]), 0, &(x86_64_parms::x86_64_isa::instructions[12])},
  {"mov_mr", 4, "movq", "movq %reg, %disp(%rm)", "Type_RM", 13, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[12]), 0, &(x86_64_parms::x86_64_isa::instructions[13])},
  {"jmp", 4, "jmp", "jmp %offset", "Type_J", 14, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[13]), 0, &(x86_64_parms::x86_64_isa::instructions[14])},
  {"jne", 4, "jne", "jne %offset", "Type_J", 15, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[14]), 0, &(x86_64_parms::x86_64_isa::instructions[15])},
  {"je", 4, "je", "je %offset", "Type_J", 16, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[15]), 0, &(x86_64_parms::x86_64_isa::instructions[16])},
  {"hlt", 4, "hlt", "hlt", "Type_HLT", 17, 1, 1, 1, &(x86_64_parms::x86_64_isa::dec_list[16]), 0, NULL}
};

const ac_instr_info
x86_64_parms::x86_64_isa::instr_table[x86_64_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 8),
  ac_instr_info(1, "add_rr", "addq", 4),
  ac_instr_info(2, "sub_rr", "subq", 4),
  ac_instr_info(3, "and_rr", "andq", 4),
  ac_instr_info(4, "or_rr", "orq", 4),
  ac_instr_info(5, "xor_rr", "xorq", 4),
  ac_instr_info(6, "mov_rr", "movq", 4),
  ac_instr_info(7, "imul_rr", "imulq", 4),
  ac_instr_info(8, "mov_ri", "movq", 4),
  ac_instr_info(9, "add_ri", "addq", 4),
  ac_instr_info(10, "sub_ri", "subq", 4),
  ac_instr_info(11, "cmp_ri", "cmpq", 4),
  ac_instr_info(12, "mov_rm", "movq", 4),
  ac_instr_info(13, "mov_mr", "movq", 4),
  ac_instr_info(14, "jmp", "jmp", 4),
  ac_instr_info(15, "jne", "jne", 4),
  ac_instr_info(16, "je", "je", 4),
  ac_instr_info(17, "hlt", "hlt", 4)
};

const unsigned x86_64_parms::x86_64_isa::instr_format_table[x86_64_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  3,
  3,
  4,
  4,
  4,
  5
};
