/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "x86_64.H"
#include  "x86_64_isa.cpp"

#include  "x86_64_syscall.H"

void* x86_64::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_RR.opcode = ins_cache[1];
        instr_dec->F_Type_RR.rex = ins_cache[2];
        instr_dec->F_Type_RR.reg = ins_cache[3];
        instr_dec->F_Type_RR.rm = ins_cache[4];
        instr_dec->F_Type_RR.pad = ins_cache[5];
      break;
      case 2:
        instr_dec->F_Type_RI.opcode = ins_cache[1];
        instr_dec->F_Type_RI.reg = ins_cache[2];
        instr_dec->F_Type_RI.pad = ins_cache[3];
        instr_dec->F_Type_RI.imm = ins_cache[6];
      break;
      case 3:
        instr_dec->F_Type_RM.opcode = ins_cache[1];
        instr_dec->F_Type_RM.reg = ins_cache[2];
        instr_dec->F_Type_RM.rm = ins_cache[3];
        instr_dec->F_Type_RM.disp = ins_cache[6];
      break;
      case 4:
        instr_dec->F_Type_J.opcode = ins_cache[1];
        instr_dec->F_Type_J.offset = ins_cache[7];
      break;
      case 5:
        instr_dec->F_Type_HLT.opcode = ins_cache[1];
        instr_dec->F_Type_HLT.pad = ins_cache[8];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void x86_64::behavior() {

  void* vet[] = {&&I_Init, &&I_add_rr, &&I_sub_rr, &&I_and_rr, &&I_or_rr, 
              &&I_xor_rr, &&I_mov_rr, &&I_imul_rr, &&I_mov_ri, &&I_add_ri, 
              &&I_sub_ri, &&I_cmp_ri, &&I_mov_rm, &&I_mov_mr, &&I_jmp, 
              &&I_jne, &&I_je, &&I_hlt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_rr: // Instruction add_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_add_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_sub_rr: // Instruction sub_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_sub_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_and_rr: // Instruction and_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_and_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_or_rr: // Instruction or_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_or_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_xor_rr: // Instruction xor_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_xor_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_mov_rr: // Instruction mov_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_mov_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_imul_rr: // Instruction imul_rr
    ISA._behavior_instruction(instr_dec->F_Type_RR.opcode);
    ISA._behavior_x86_64_Type_RR(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    ISA.behavior_imul_rr(instr_dec->F_Type_RR.opcode, instr_dec->F_Type_RR.rex, instr_dec->F_Type_RR.reg, instr_dec->F_Type_RR.rm, instr_dec->F_Type_RR.pad);
    goto *dispatch();

  I_mov_ri: // Instruction mov_ri
    ISA._behavior_instruction(instr_dec->F_Type_RI.opcode);
    ISA._behavior_x86_64_Type_RI(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    ISA.behavior_mov_ri(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    goto *dispatch();

  I_add_ri: // Instruction add_ri
    ISA._behavior_instruction(instr_dec->F_Type_RI.opcode);
    ISA._behavior_x86_64_Type_RI(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    ISA.behavior_add_ri(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    goto *dispatch();

  I_sub_ri: // Instruction sub_ri
    ISA._behavior_instruction(instr_dec->F_Type_RI.opcode);
    ISA._behavior_x86_64_Type_RI(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    ISA.behavior_sub_ri(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    goto *dispatch();

  I_cmp_ri: // Instruction cmp_ri
    ISA._behavior_instruction(instr_dec->F_Type_RI.opcode);
    ISA._behavior_x86_64_Type_RI(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    ISA.behavior_cmp_ri(instr_dec->F_Type_RI.opcode, instr_dec->F_Type_RI.reg, instr_dec->F_Type_RI.pad, instr_dec->F_Type_RI.imm);
    goto *dispatch();

  I_mov_rm: // Instruction mov_rm
    ISA._behavior_instruction(instr_dec->F_Type_RM.opcode);
    ISA._behavior_x86_64_Type_RM(instr_dec->F_Type_RM.opcode, instr_dec->F_Type_RM.reg, instr_dec->F_Type_RM.rm, instr_dec->F_Type_RM.disp);
    ISA.behavior_mov_rm(instr_dec->F_Type_RM.opcode, instr_dec->F_Type_RM.reg, instr_dec->F_Type_RM.rm, instr_dec->F_Type_RM.disp);
    goto *dispatch();

  I_mov_mr: // Instruction mov_mr
    ISA._behavior_instruction(instr_dec->F_Type_RM.opcode);
    ISA._behavior_x86_64_Type_RM(instr_dec->F_Type_RM.opcode, instr_dec->F_Type_RM.reg, instr_dec->F_Type_RM.rm, instr_dec->F_Type_RM.disp);
    ISA.behavior_mov_mr(instr_dec->F_Type_RM.opcode, instr_dec->F_Type_RM.reg, instr_dec->F_Type_RM.rm, instr_dec->F_Type_RM.disp);
    goto *dispatch();

  I_jmp: // Instruction jmp
    ISA._behavior_instruction(instr_dec->F_Type_J.opcode);
    ISA._behavior_x86_64_Type_J(instr_dec->F_Type_J.opcode, instr_dec->F_Type_J.offset);
    ISA.behavior_jmp(instr_dec->F_Type_J.opcode, instr_dec->F_Type_J.offset);
    goto *dispatch();

  I_jne: // Instruction jne
    ISA._behavior_instruction(instr_dec->F_Type_J.opcode);
    ISA._behavior_x86_64_Type_J(instr_dec->F_Type_J.opcode, instr_dec->F_Type_J.offset);
    ISA.behavior_jne(instr_dec->F_Type_J.opcode, instr_dec->F_Type_J.offset);
    goto *dispatch();

  I_je: // Instruction je
    ISA._behavior_instruction(instr_dec->F_Type_J.opcode);
    ISA._behavior_x86_64_Type_J(instr_dec->F_Type_J.opcode, instr_dec->F_Type_J.offset);
    ISA.behavior_je(instr_dec->F_Type_J.opcode, instr_dec->F_Type_J.offset);
    goto *dispatch();

  I_hlt: // Instruction hlt
    ISA._behavior_instruction(instr_dec->F_Type_HLT.opcode);
    ISA._behavior_x86_64_Type_HLT(instr_dec->F_Type_HLT.opcode, instr_dec->F_Type_HLT.pad);
    ISA.behavior_hlt(instr_dec->F_Type_HLT.opcode, instr_dec->F_Type_HLT.pad);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void x86_64::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void x86_64::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void x86_64::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void x86_64::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void x86_64::load(char* program) {
  DM_mport.load(program);
}

void x86_64::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned x86_64::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void x86_64::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void x86_64::PrintStat() {
  ac_arch<x86_64_parms::ac_word, x86_64_parms::ac_Hword>::PrintStat();
}

