/******************************************************
 * Syscall implementation file template.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "x86_64_syscall.H"

//!'using namespace' statement to allow access to all x86_64-specific datatypes
using namespace x86_64_parms;

void x86_64_syscall::get_buffer(int argn, unsigned char* buf, unsigned int size) { }
void x86_64_syscall::set_buffer(int argn, unsigned char* buf, unsigned int size) { }
void x86_64_syscall::set_buffer_noinvert(int argn, unsigned char* buf, unsigned int size) { }
int  x86_64_syscall::get_int(int argn) { }
void x86_64_syscall::set_int(int argn, int val) { }
void x86_64_syscall::return_from_syscall() { }
void x86_64_syscall::set_prog_args(int argc, char **argv) { } 
