/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "x86_64_arch.H"


x86_64_arch::x86_64_arch() :
  ac_arch_dec_if<x86_64_parms::ac_word, x86_64_parms::ac_Hword>(x86_64_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  RB("RB"),
  rflags("rflags", 0) {

  ac_mt_endian = x86_64_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = x86_64_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int x86_64_arch::globalId = 0;