/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "esp32c3.H"
#include  "esp32c3_isa.cpp"

#include  "esp32c3_syscall.H"

void* esp32c3::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_R.funct7 = ins_cache[1];
        instr_dec->F_Type_R.rs2 = ins_cache[2];
        instr_dec->F_Type_R.rs1 = ins_cache[3];
        instr_dec->F_Type_R.funct3 = ins_cache[4];
        instr_dec->F_Type_R.rd = ins_cache[5];
        instr_dec->F_Type_R.op = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_I.imm12 = ins_cache[7];
        instr_dec->F_Type_I.rs1 = ins_cache[3];
        instr_dec->F_Type_I.funct3 = ins_cache[4];
        instr_dec->F_Type_I.rd = ins_cache[5];
        instr_dec->F_Type_I.op = ins_cache[6];
      break;
      case 3:
        instr_dec->F_Type_S.imm7 = ins_cache[8];
        instr_dec->F_Type_S.rs2 = ins_cache[2];
        instr_dec->F_Type_S.rs1 = ins_cache[3];
        instr_dec->F_Type_S.funct3 = ins_cache[4];
        instr_dec->F_Type_S.imm5 = ins_cache[5];
        instr_dec->F_Type_S.op = ins_cache[6];
      break;
      case 4:
        instr_dec->F_Type_B.imm12 = ins_cache[9];
        instr_dec->F_Type_B.imm10 = ins_cache[10];
        instr_dec->F_Type_B.rs2 = ins_cache[2];
        instr_dec->F_Type_B.rs1 = ins_cache[3];
        instr_dec->F_Type_B.funct3 = ins_cache[4];
        instr_dec->F_Type_B.imm4 = ins_cache[11];
        instr_dec->F_Type_B.imm11 = ins_cache[12];
        instr_dec->F_Type_B.op = ins_cache[6];
      break;
      case 5:
        instr_dec->F_Type_U.imm20 = ins_cache[13];
        instr_dec->F_Type_U.rd = ins_cache[5];
        instr_dec->F_Type_U.op = ins_cache[6];
      break;
      case 6:
        instr_dec->F_Type_J.imm20 = ins_cache[9];
        instr_dec->F_Type_J.imm10 = ins_cache[14];
        instr_dec->F_Type_J.imm11 = ins_cache[15];
        instr_dec->F_Type_J.imm8 = ins_cache[16];
        instr_dec->F_Type_J.rd = ins_cache[5];
        instr_dec->F_Type_J.op = ins_cache[6];
      break;
      case 7:
        instr_dec->F_Type_H.op = ins_cache[1];
        instr_dec->F_Type_H.pad = ins_cache[17];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void esp32c3::behavior() {

  void* vet[] = {&&I_Init, &&I_add, &&I_sub, &&I_and_op, &&I_or_op, 
              &&I_xor_op, &&I_sll_op, &&I_srl_op, &&I_sra_op, &&I_slt, 
              &&I_sltu, &&I_mul_op, &&I_mulh_op, &&I_mulhu_op, &&I_div_op, 
              &&I_divu_op, &&I_rem_op, &&I_remu_op, &&I_addi, &&I_andi, 
              &&I_ori, &&I_xori, &&I_slli, &&I_srli, &&I_slti, 
              &&I_sltiu, &&I_jalr, &&I_lw, &&I_lh, &&I_lb, 
              &&I_sw, &&I_sh, &&I_sb, &&I_beq, &&I_bne, 
              &&I_blt, &&I_bge, &&I_bltu, &&I_bgeu, &&I_lui, 
              &&I_auipc, &&I_jal, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    IROM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add: // Instruction add
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_add(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_sub: // Instruction sub
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_sub(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_and_op: // Instruction and_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_and_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_or_op: // Instruction or_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_or_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_xor_op: // Instruction xor_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_xor_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_sll_op: // Instruction sll_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_sll_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_srl_op: // Instruction srl_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_srl_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_sra_op: // Instruction sra_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_sra_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_slt: // Instruction slt
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_slt(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_sltu: // Instruction sltu
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_sltu(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_mul_op: // Instruction mul_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_mul_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_mulh_op: // Instruction mulh_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_mulh_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_mulhu_op: // Instruction mulhu_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_mulhu_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_div_op: // Instruction div_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_div_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_divu_op: // Instruction divu_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_divu_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_rem_op: // Instruction rem_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_rem_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_remu_op: // Instruction remu_op
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_esp32c3_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_remu_op(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    goto *dispatch();

  I_addi: // Instruction addi
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_addi(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_andi: // Instruction andi
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_andi(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_ori: // Instruction ori
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_ori(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_xori: // Instruction xori
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_xori(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_slli: // Instruction slli
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_slli(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_srli: // Instruction srli
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_srli(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_slti: // Instruction slti
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_slti(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_sltiu: // Instruction sltiu
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_sltiu(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_jalr: // Instruction jalr
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_jalr(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_lw: // Instruction lw
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_lw(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_lh: // Instruction lh
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_lh(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_lb: // Instruction lb
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_esp32c3_Type_I(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_lb(instr_dec->F_Type_I.imm12, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    goto *dispatch();

  I_sw: // Instruction sw
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_esp32c3_Type_S(instr_dec->F_Type_S.imm7, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm5, instr_dec->F_Type_S.op);
    ISA.behavior_sw(instr_dec->F_Type_S.imm7, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm5, instr_dec->F_Type_S.op);
    goto *dispatch();

  I_sh: // Instruction sh
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_esp32c3_Type_S(instr_dec->F_Type_S.imm7, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm5, instr_dec->F_Type_S.op);
    ISA.behavior_sh(instr_dec->F_Type_S.imm7, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm5, instr_dec->F_Type_S.op);
    goto *dispatch();

  I_sb: // Instruction sb
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_esp32c3_Type_S(instr_dec->F_Type_S.imm7, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm5, instr_dec->F_Type_S.op);
    ISA.behavior_sb(instr_dec->F_Type_S.imm7, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm5, instr_dec->F_Type_S.op);
    goto *dispatch();

  I_beq: // Instruction beq
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_esp32c3_Type_B(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    ISA.behavior_beq(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    goto *dispatch();

  I_bne: // Instruction bne
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_esp32c3_Type_B(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    ISA.behavior_bne(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    goto *dispatch();

  I_blt: // Instruction blt
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_esp32c3_Type_B(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    ISA.behavior_blt(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    goto *dispatch();

  I_bge: // Instruction bge
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_esp32c3_Type_B(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    ISA.behavior_bge(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    goto *dispatch();

  I_bltu: // Instruction bltu
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_esp32c3_Type_B(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    ISA.behavior_bltu(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    goto *dispatch();

  I_bgeu: // Instruction bgeu
    ISA._behavior_instruction(instr_dec->F_Type_B.op);
    ISA._behavior_esp32c3_Type_B(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    ISA.behavior_bgeu(instr_dec->F_Type_B.imm12, instr_dec->F_Type_B.imm10, instr_dec->F_Type_B.rs2, instr_dec->F_Type_B.rs1, instr_dec->F_Type_B.funct3, instr_dec->F_Type_B.imm4, instr_dec->F_Type_B.imm11, instr_dec->F_Type_B.op);
    goto *dispatch();

  I_lui: // Instruction lui
    ISA._behavior_instruction(instr_dec->F_Type_U.op);
    ISA._behavior_esp32c3_Type_U(instr_dec->F_Type_U.imm20, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    ISA.behavior_lui(instr_dec->F_Type_U.imm20, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    goto *dispatch();

  I_auipc: // Instruction auipc
    ISA._behavior_instruction(instr_dec->F_Type_U.op);
    ISA._behavior_esp32c3_Type_U(instr_dec->F_Type_U.imm20, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    ISA.behavior_auipc(instr_dec->F_Type_U.imm20, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    goto *dispatch();

  I_jal: // Instruction jal
    ISA._behavior_instruction(instr_dec->F_Type_J.op);
    ISA._behavior_esp32c3_Type_J(instr_dec->F_Type_J.imm20, instr_dec->F_Type_J.imm10, instr_dec->F_Type_J.imm11, instr_dec->F_Type_J.imm8, instr_dec->F_Type_J.rd, instr_dec->F_Type_J.op);
    ISA.behavior_jal(instr_dec->F_Type_J.imm20, instr_dec->F_Type_J.imm10, instr_dec->F_Type_J.imm11, instr_dec->F_Type_J.imm8, instr_dec->F_Type_J.rd, instr_dec->F_Type_J.op);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_H.op);
    ISA._behavior_esp32c3_Type_H(instr_dec->F_Type_H.op, instr_dec->F_Type_H.pad);
    ISA.behavior_halt(instr_dec->F_Type_H.op, instr_dec->F_Type_H.pad);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void esp32c3::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void esp32c3::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  IROM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void esp32c3::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void esp32c3::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void esp32c3::load(char* program) {
  IROM_mport.load(program);
}

void esp32c3::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned esp32c3::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void esp32c3::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void esp32c3::PrintStat() {
  ac_arch<esp32c3_parms::ac_word, esp32c3_parms::ac_Hword>::PrintStat();
}

