/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "esp32c3_arch.H"


esp32c3_arch::esp32c3_arch() :
  ac_arch_dec_if<esp32c3_parms::ac_word, esp32c3_parms::ac_Hword>(esp32c3_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  IROM("IROM", 4194304U),
  IROM_mport(*this, IROM),
  IRAM("IRAM", 131072U),
  IRAM_mport(*this, IRAM),
  DRAM("DRAM", 278528U),
  DRAM_mport(*this, DRAM),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  RB("RB"),
  mstatus("mstatus", 0),
  mie("mie", 0),
  mtvec("mtvec", 0),
  mepc("mepc", 0),
  mcause("mcause", 0) {

  ac_mt_endian = esp32c3_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = esp32c3_parms::AC_PROC_ENDIAN;

  INST_PORT = &IROM_mport;
  DATA_PORT = &IROM_mport;
}

int esp32c3_arch::globalId = 0;