/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "esp32c3_arch.H"
#include  "esp32c3_arch_ref.H"

//!/Default constructor.
esp32c3_arch_ref::esp32c3_arch_ref(esp32c3_arch& arch) : ac_arch_ref<esp32c3_parms::ac_word, esp32c3_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  IROM(arch.IROM_mport),   IRAM(arch.IRAM_mport),   DRAM(arch.DRAM_mport),   DM(arch.DM_mport),   RB(arch.RB),   mstatus(arch.mstatus),   mie(arch.mie),   mtvec(arch.mtvec),   mepc(arch.mepc),   mcause(arch.mcause) {}

