/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "aarch64_arch.H"
#include  "aarch64_arch_ref.H"

//!/Default constructor.
aarch64_arch_ref::aarch64_arch_ref(aarch64_arch& arch) : ac_arch_ref<aarch64_parms::ac_word, aarch64_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   RB(arch.RB),   sp_reg(arch.sp_reg),   pstate(arch.pstate) {}

