/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "aarch64.H"
#include  "aarch64_isa.cpp"

#include  "aarch64_syscall.H"

void* aarch64::dispatch() {
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc / 4));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_DP_Reg.op = ins_cache[1];
        instr_dec->F_Type_DP_Reg.opt = ins_cache[2];
        instr_dec->F_Type_DP_Reg.rm = ins_cache[3];
        instr_dec->F_Type_DP_Reg.imm6 = ins_cache[4];
        instr_dec->F_Type_DP_Reg.rn = ins_cache[5];
        instr_dec->F_Type_DP_Reg.rd = ins_cache[6];
      break;
      case 2:
        instr_dec->F_Type_DP_Imm.op = ins_cache[1];
        instr_dec->F_Type_DP_Imm.imm14 = ins_cache[7];
        instr_dec->F_Type_DP_Imm.rn = ins_cache[5];
        instr_dec->F_Type_DP_Imm.rd = ins_cache[6];
      break;
      case 3:
        instr_dec->F_Type_LS_Imm.op = ins_cache[1];
        instr_dec->F_Type_LS_Imm.disp = ins_cache[8];
        instr_dec->F_Type_LS_Imm.rn = ins_cache[5];
        instr_dec->F_Type_LS_Imm.rd = ins_cache[6];
      break;
      case 4:
        instr_dec->F_Type_Branch_Cond.op = ins_cache[1];
        instr_dec->F_Type_Branch_Cond.imm19 = ins_cache[9];
        instr_dec->F_Type_Branch_Cond.o = ins_cache[10];
        instr_dec->F_Type_Branch_Cond.cond = ins_cache[11];
      break;
      case 5:
        instr_dec->F_Type_Branch_Imm.op = ins_cache[1];
        instr_dec->F_Type_Branch_Imm.imm24 = ins_cache[12];
      break;
      case 6:
        instr_dec->F_Type_Branch_Reg.op = ins_cache[13];
        instr_dec->F_Type_Branch_Reg.rn = ins_cache[14];
        instr_dec->F_Type_Branch_Reg.pad = ins_cache[15];
      break;
      case 7:
        instr_dec->F_Type_Halt.op = ins_cache[1];
        instr_dec->F_Type_Halt.pad = ins_cache[16];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  return instr_dec->end_rot;
}

void aarch64::behavior() {

  void* vet[] = {&&I_Init, &&I_add_reg, &&I_adds_reg, &&I_sub_reg, &&I_subs_reg, 
              &&I_and_reg, &&I_orr_reg, &&I_eor_reg, &&I_mul_reg, &&I_add_imm, 
              &&I_adds_imm, &&I_sub_imm, &&I_subs_imm, &&I_movz_imm, &&I_ldr_x, 
              &&I_str_x, &&I_ldr_w, &&I_str_w, &&I_b_cond, &&I_b_imm, 
              &&I_bl_imm, &&I_br_reg, &&I_ret_reg, &&I_halt};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION / 4)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_add_reg: // Instruction add_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_add_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_adds_reg: // Instruction adds_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_adds_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_sub_reg: // Instruction sub_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_sub_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_subs_reg: // Instruction subs_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_subs_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_and_reg: // Instruction and_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_and_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_orr_reg: // Instruction orr_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_orr_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_eor_reg: // Instruction eor_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_eor_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_mul_reg: // Instruction mul_reg
    ISA._behavior_instruction(instr_dec->F_Type_DP_Reg.op);
    ISA._behavior_aarch64_Type_DP_Reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    ISA.behavior_mul_reg(instr_dec->F_Type_DP_Reg.op, instr_dec->F_Type_DP_Reg.opt, instr_dec->F_Type_DP_Reg.rm, instr_dec->F_Type_DP_Reg.imm6, instr_dec->F_Type_DP_Reg.rn, instr_dec->F_Type_DP_Reg.rd);
    goto *dispatch();

  I_add_imm: // Instruction add_imm
    ISA._behavior_instruction(instr_dec->F_Type_DP_Imm.op);
    ISA._behavior_aarch64_Type_DP_Imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    ISA.behavior_add_imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    goto *dispatch();

  I_adds_imm: // Instruction adds_imm
    ISA._behavior_instruction(instr_dec->F_Type_DP_Imm.op);
    ISA._behavior_aarch64_Type_DP_Imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    ISA.behavior_adds_imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    goto *dispatch();

  I_sub_imm: // Instruction sub_imm
    ISA._behavior_instruction(instr_dec->F_Type_DP_Imm.op);
    ISA._behavior_aarch64_Type_DP_Imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    ISA.behavior_sub_imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    goto *dispatch();

  I_subs_imm: // Instruction subs_imm
    ISA._behavior_instruction(instr_dec->F_Type_DP_Imm.op);
    ISA._behavior_aarch64_Type_DP_Imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    ISA.behavior_subs_imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    goto *dispatch();

  I_movz_imm: // Instruction movz_imm
    ISA._behavior_instruction(instr_dec->F_Type_DP_Imm.op);
    ISA._behavior_aarch64_Type_DP_Imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    ISA.behavior_movz_imm(instr_dec->F_Type_DP_Imm.op, instr_dec->F_Type_DP_Imm.imm14, instr_dec->F_Type_DP_Imm.rn, instr_dec->F_Type_DP_Imm.rd);
    goto *dispatch();

  I_ldr_x: // Instruction ldr_x
    ISA._behavior_instruction(instr_dec->F_Type_LS_Imm.op);
    ISA._behavior_aarch64_Type_LS_Imm(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    ISA.behavior_ldr_x(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    goto *dispatch();

  I_str_x: // Instruction str_x
    ISA._behavior_instruction(instr_dec->F_Type_LS_Imm.op);
    ISA._behavior_aarch64_Type_LS_Imm(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    ISA.behavior_str_x(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    goto *dispatch();

  I_ldr_w: // Instruction ldr_w
    ISA._behavior_instruction(instr_dec->F_Type_LS_Imm.op);
    ISA._behavior_aarch64_Type_LS_Imm(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    ISA.behavior_ldr_w(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    goto *dispatch();

  I_str_w: // Instruction str_w
    ISA._behavior_instruction(instr_dec->F_Type_LS_Imm.op);
    ISA._behavior_aarch64_Type_LS_Imm(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    ISA.behavior_str_w(instr_dec->F_Type_LS_Imm.op, instr_dec->F_Type_LS_Imm.disp, instr_dec->F_Type_LS_Imm.rn, instr_dec->F_Type_LS_Imm.rd);
    goto *dispatch();

  I_b_cond: // Instruction b_cond
    ISA._behavior_instruction(instr_dec->F_Type_Branch_Cond.op);
    ISA._behavior_aarch64_Type_Branch_Cond(instr_dec->F_Type_Branch_Cond.op, instr_dec->F_Type_Branch_Cond.imm19, instr_dec->F_Type_Branch_Cond.o, instr_dec->F_Type_Branch_Cond.cond);
    ISA.behavior_b_cond(instr_dec->F_Type_Branch_Cond.op, instr_dec->F_Type_Branch_Cond.imm19, instr_dec->F_Type_Branch_Cond.o, instr_dec->F_Type_Branch_Cond.cond);
    goto *dispatch();

  I_b_imm: // Instruction b_imm
    ISA._behavior_instruction(instr_dec->F_Type_Branch_Imm.op);
    ISA._behavior_aarch64_Type_Branch_Imm(instr_dec->F_Type_Branch_Imm.op, instr_dec->F_Type_Branch_Imm.imm24);
    ISA.behavior_b_imm(instr_dec->F_Type_Branch_Imm.op, instr_dec->F_Type_Branch_Imm.imm24);
    goto *dispatch();

  I_bl_imm: // Instruction bl_imm
    ISA._behavior_instruction(instr_dec->F_Type_Branch_Imm.op);
    ISA._behavior_aarch64_Type_Branch_Imm(instr_dec->F_Type_Branch_Imm.op, instr_dec->F_Type_Branch_Imm.imm24);
    ISA.behavior_bl_imm(instr_dec->F_Type_Branch_Imm.op, instr_dec->F_Type_Branch_Imm.imm24);
    goto *dispatch();

  I_br_reg: // Instruction br_reg
    ISA._behavior_instruction(instr_dec->F_Type_Branch_Reg.op);
    ISA._behavior_aarch64_Type_Branch_Reg(instr_dec->F_Type_Branch_Reg.op, instr_dec->F_Type_Branch_Reg.rn, instr_dec->F_Type_Branch_Reg.pad);
    ISA.behavior_br_reg(instr_dec->F_Type_Branch_Reg.op, instr_dec->F_Type_Branch_Reg.rn, instr_dec->F_Type_Branch_Reg.pad);
    goto *dispatch();

  I_ret_reg: // Instruction ret_reg
    ISA._behavior_instruction(instr_dec->F_Type_Branch_Reg.op);
    ISA._behavior_aarch64_Type_Branch_Reg(instr_dec->F_Type_Branch_Reg.op, instr_dec->F_Type_Branch_Reg.rn, instr_dec->F_Type_Branch_Reg.pad);
    ISA.behavior_ret_reg(instr_dec->F_Type_Branch_Reg.op, instr_dec->F_Type_Branch_Reg.rn, instr_dec->F_Type_Branch_Reg.pad);
    goto *dispatch();

  I_halt: // Instruction halt
    ISA._behavior_instruction(instr_dec->F_Type_Halt.op);
    ISA._behavior_aarch64_Type_Halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    ISA.behavior_halt(instr_dec->F_Type_Halt.op, instr_dec->F_Type_Halt.pad);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void aarch64::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void aarch64::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void aarch64::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void aarch64::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void aarch64::load(char* program) {
  DM_mport.load(program);
}

void aarch64::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned aarch64::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void aarch64::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void aarch64::PrintStat() {
  ac_arch<aarch64_parms::ac_word, aarch64_parms::ac_Hword>::PrintStat();
}

