/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "aarch64_isa.H"

//!Fields table declaration.
ac_dec_field aarch64_parms::aarch64_isa::fields[aarch64_parms::AC_DEC_FIELD_NUMBER] = {
  {"op", 8, 31, 1, 0, 0, &(aarch64_parms::aarch64_isa::fields[1])},
  {"opt", 3, 23, 2, 0, 0, &(aarch64_parms::aarch64_isa::fields[2])},
  {"rm", 5, 20, 3, 0, 0, &(aarch64_parms::aarch64_isa::fields[3])},
  {"imm6", 6, 15, 4, 0, 0, &(aarch64_parms::aarch64_isa::fields[4])},
  {"rn", 5, 9, 5, 0, 0, &(aarch64_parms::aarch64_isa::fields[5])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(aarch64_parms::aarch64_isa::fields[7])},
  {"imm14", 14, 23, 7, 0, 0, &(aarch64_parms::aarch64_isa::fields[8])},
  {"rn", 5, 9, 5, 0, 0, &(aarch64_parms::aarch64_isa::fields[9])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(aarch64_parms::aarch64_isa::fields[11])},
  {"disp", 14, 23, 8, 0, 1, &(aarch64_parms::aarch64_isa::fields[12])},
  {"rn", 5, 9, 5, 0, 0, &(aarch64_parms::aarch64_isa::fields[13])},
  {"rd", 5, 4, 6, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(aarch64_parms::aarch64_isa::fields[15])},
  {"imm19", 19, 23, 9, 0, 1, &(aarch64_parms::aarch64_isa::fields[16])},
  {"o", 1, 4, 10, 0, 0, &(aarch64_parms::aarch64_isa::fields[17])},
  {"cond", 4, 3, 11, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(aarch64_parms::aarch64_isa::fields[19])},
  {"imm24", 24, 23, 12, 0, 1, NULL},
  {"op", 16, 31, 13, 0, 0, &(aarch64_parms::aarch64_isa::fields[21])},
  {"rn", 5, 15, 14, 0, 0, &(aarch64_parms::aarch64_isa::fields[22])},
  {"pad", 11, 10, 15, 0, 0, NULL},
  {"op", 8, 31, 1, 0, 0, &(aarch64_parms::aarch64_isa::fields[24])},
  {"pad", 24, 23, 16, 0, 0, NULL}
};

ac_dec_format aarch64_parms::aarch64_isa::formats[aarch64_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_DP_Reg", 32, &(aarch64_parms::aarch64_isa::fields[0]), &(aarch64_parms::aarch64_isa::formats[1])},
  {2, "Type_DP_Imm", 32, &(aarch64_parms::aarch64_isa::fields[6]), &(aarch64_parms::aarch64_isa::formats[2])},
  {3, "Type_LS_Imm", 32, &(aarch64_parms::aarch64_isa::fields[10]), &(aarch64_parms::aarch64_isa::formats[3])},
  {4, "Type_Branch_Cond", 32, &(aarch64_parms::aarch64_isa::fields[14]), &(aarch64_parms::aarch64_isa::formats[4])},
  {5, "Type_Branch_Imm", 32, &(aarch64_parms::aarch64_isa::fields[18]), &(aarch64_parms::aarch64_isa::formats[5])},
  {6, "Type_Branch_Reg", 32, &(aarch64_parms::aarch64_isa::fields[20]), &(aarch64_parms::aarch64_isa::formats[6])},
  {7, "Type_Halt", 32, &(aarch64_parms::aarch64_isa::fields[23]), NULL}
};

ac_dec_list aarch64_parms::aarch64_isa::dec_list[aarch64_parms::AC_DEC_LIST_NUMBER] = {
  {"op", 1, 139, &(aarch64_parms::aarch64_isa::dec_list[1])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 171, &(aarch64_parms::aarch64_isa::dec_list[3])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 203, &(aarch64_parms::aarch64_isa::dec_list[5])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 235, &(aarch64_parms::aarch64_isa::dec_list[7])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 138, &(aarch64_parms::aarch64_isa::dec_list[9])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 170, &(aarch64_parms::aarch64_isa::dec_list[11])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 202, &(aarch64_parms::aarch64_isa::dec_list[13])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 155, &(aarch64_parms::aarch64_isa::dec_list[15])},
  {"imm6", 4, 0, NULL},
  {"op", 1, 145, NULL},
  {"op", 1, 177, NULL},
  {"op", 1, 209, NULL},
  {"op", 1, 241, NULL},
  {"op", 1, 210, &(aarch64_parms::aarch64_isa::dec_list[21])},
  {"rn", 5, 31, NULL},
  {"op", 1, 249, NULL},
  {"op", 1, 248, NULL},
  {"op", 1, 185, NULL},
  {"op", 1, 184, NULL},
  {"op", 1, 84, &(aarch64_parms::aarch64_isa::dec_list[27])},
  {"o", 10, 0, NULL},
  {"op", 1, 20, NULL},
  {"op", 1, 148, NULL},
  {"op", 13, 54815, &(aarch64_parms::aarch64_isa::dec_list[31])},
  {"pad", 15, 0, NULL},
  {"op", 13, 54879, &(aarch64_parms::aarch64_isa::dec_list[33])},
  {"rn", 14, 30, &(aarch64_parms::aarch64_isa::dec_list[34])},
  {"pad", 15, 0, NULL},
  {"op", 1, 127, NULL}
};

ac_dec_instr aarch64_parms::aarch64_isa::instructions[aarch64_parms::AC_DEC_INSTR_NUMBER] = {
  {"add_reg", 4, "add", "add X%rd, X%rn, X%rm", "Type_DP_Reg", 1, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[0]), 0, &(aarch64_parms::aarch64_isa::instructions[1])},
  {"adds_reg", 4, "adds", "adds X%rd, X%rn, X%rm", "Type_DP_Reg", 2, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[2]), 0, &(aarch64_parms::aarch64_isa::instructions[2])},
  {"sub_reg", 4, "sub", "sub X%rd, X%rn, X%rm", "Type_DP_Reg", 3, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[4]), 0, &(aarch64_parms::aarch64_isa::instructions[3])},
  {"subs_reg", 4, "subs", "subs X%rd, X%rn, X%rm", "Type_DP_Reg", 4, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[6]), 0, &(aarch64_parms::aarch64_isa::instructions[4])},
  {"and_reg", 4, "and", "and X%rd, X%rn, X%rm", "Type_DP_Reg", 5, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[8]), 0, &(aarch64_parms::aarch64_isa::instructions[5])},
  {"orr_reg", 4, "orr", "orr X%rd, X%rn, X%rm", "Type_DP_Reg", 6, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[10]), 0, &(aarch64_parms::aarch64_isa::instructions[6])},
  {"eor_reg", 4, "eor", "eor X%rd, X%rn, X%rm", "Type_DP_Reg", 7, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[12]), 0, &(aarch64_parms::aarch64_isa::instructions[7])},
  {"mul_reg", 4, "mul", "mul X%rd, X%rn, X%rm", "Type_DP_Reg", 8, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[14]), 0, &(aarch64_parms::aarch64_isa::instructions[8])},
  {"add_imm", 4, "add", "add X%rd, X%rn, #%imm14", "Type_DP_Imm", 9, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[16]), 0, &(aarch64_parms::aarch64_isa::instructions[9])},
  {"adds_imm", 4, "adds", "adds X%rd, X%rn, #%imm14", "Type_DP_Imm", 10, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[17]), 0, &(aarch64_parms::aarch64_isa::instructions[10])},
  {"sub_imm", 4, "sub", "sub X%rd, X%rn, #%imm14", "Type_DP_Imm", 11, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[18]), 0, &(aarch64_parms::aarch64_isa::instructions[11])},
  {"subs_imm", 4, "subs", "subs X%rd, X%rn, #%imm14", "Type_DP_Imm", 12, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[19]), 0, &(aarch64_parms::aarch64_isa::instructions[12])},
  {"movz_imm", 4, "movz", "movz X%rd, #%imm14", "Type_DP_Imm", 13, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[20]), 0, &(aarch64_parms::aarch64_isa::instructions[13])},
  {"ldr_x", 4, "ldr", "ldr X%rd, [X%rn, #%disp]", "Type_LS_Imm", 14, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[22]), 0, &(aarch64_parms::aarch64_isa::instructions[14])},
  {"str_x", 4, "str", "str X%rd, [X%rn, #%disp]", "Type_LS_Imm", 15, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[23]), 0, &(aarch64_parms::aarch64_isa::instructions[15])},
  {"ldr_w", 4, "ldr", "ldr W%rd, [X%rn, #%disp]", "Type_LS_Imm", 16, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[24]), 0, &(aarch64_parms::aarch64_isa::instructions[16])},
  {"str_w", 4, "str", "str W%rd, [X%rn, #%disp]", "Type_LS_Imm", 17, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[25]), 0, &(aarch64_parms::aarch64_isa::instructions[17])},
  {"b_cond", 4, "b.%cond", "b.%cond %imm19", "Type_Branch_Cond", 18, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[26]), 0, &(aarch64_parms::aarch64_isa::instructions[18])},
  {"b_imm", 4, "b", "b %imm24", "Type_Branch_Imm", 19, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[28]), 0, &(aarch64_parms::aarch64_isa::instructions[19])},
  {"bl_imm", 4, "bl", "bl %imm24", "Type_Branch_Imm", 20, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[29]), 0, &(aarch64_parms::aarch64_isa::instructions[20])},
  {"br_reg", 4, "br", "br X%rn", "Type_Branch_Reg", 21, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[30]), 0, &(aarch64_parms::aarch64_isa::instructions[21])},
  {"ret_reg", 4, "ret", "ret", "Type_Branch_Reg", 22, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[32]), 0, &(aarch64_parms::aarch64_isa::instructions[22])},
  {"halt", 4, "halt", "halt", "Type_Halt", 23, 1, 1, 1, &(aarch64_parms::aarch64_isa::dec_list[35]), 0, NULL}
};

const ac_instr_info
aarch64_parms::aarch64_isa::instr_table[aarch64_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 8),
  ac_instr_info(1, "add_reg", "add", 4),
  ac_instr_info(2, "adds_reg", "adds", 4),
  ac_instr_info(3, "sub_reg", "sub", 4),
  ac_instr_info(4, "subs_reg", "subs", 4),
  ac_instr_info(5, "and_reg", "and", 4),
  ac_instr_info(6, "orr_reg", "orr", 4),
  ac_instr_info(7, "eor_reg", "eor", 4),
  ac_instr_info(8, "mul_reg", "mul", 4),
  ac_instr_info(9, "add_imm", "add", 4),
  ac_instr_info(10, "adds_imm", "adds", 4),
  ac_instr_info(11, "sub_imm", "sub", 4),
  ac_instr_info(12, "subs_imm", "subs", 4),
  ac_instr_info(13, "movz_imm", "movz", 4),
  ac_instr_info(14, "ldr_x", "ldr", 4),
  ac_instr_info(15, "str_x", "str", 4),
  ac_instr_info(16, "ldr_w", "ldr", 4),
  ac_instr_info(17, "str_w", "str", 4),
  ac_instr_info(18, "b_cond", "b.%cond", 4),
  ac_instr_info(19, "b_imm", "b", 4),
  ac_instr_info(20, "bl_imm", "bl", 4),
  ac_instr_info(21, "br_reg", "br", 4),
  ac_instr_info(22, "ret_reg", "ret", 4),
  ac_instr_info(23, "halt", "halt", 4)
};

const unsigned aarch64_parms::aarch64_isa::instr_format_table[aarch64_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  4,
  5,
  5,
  6,
  6,
  7
};
